### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by aradi** [grimme-lab/xtb#1]
Hey,

it is great, that you put xTB now on GitHub!

I have some problems to compile it on Ubuntu 18.04, intel 19, meson nin0.51.2 and ninja 1.9.0.

* `find_library()` does not find the MKL-libraries. I had to fix it by adding the library path of those libraries via the `dirs` keyword argument (as an ugly hack).

* As `find_library()` picked up the shared libraries instead of the static ones, the linking efforts with the manually specified `-static` option failed. I, therefore, also removed those options from the build file.

* However, although everything compiled, the linking of `xtb_test` failed, due to 

```
cc  -o xtb_test 'xtb_test@exe/TESTSUITE_tests_peeq.f90.o' 'xtb_test@exe/TESTSUITE_assertion.f90.o' 'xtb_test@exe/TESTSUITE_tbdef_molecule.f90.o' 'xtb_test@exe/TESTSUITE_geometry_reader.f90.o' 'xtb_test@exe/TESTSUITE_eeq_model.f90.o' 'xtb_test@exe/TESTSUITE_pbc_tools.f90.o' 'xtb_test@exe/TESTSUITE_dftd4.f90.o' 'xtb_test@exe/TESTSUITE_gfn2.f90.o' 'xtb_test@exe/TESTSUITE_gfn1.f90.o' 'xtb_test@exe/TESTSUITE_gfn0.f90.o' 'xtb_test@exe/TESTSUITE_peeq.f90.o' -Wl,--no-undefined -Wl,--as-needed -Wl,--start-group libxtb.a /opt/repo/intel/2018/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64/libmkl_intel_lp64.so /opt/repo/intel/2018/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64/libmkl_intel_thread.so /opt/repo/intel/2018/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64/libmkl_core.so /opt/repo/intel/2018/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64/libiomp5.so -lpthread -lm -ldl -pthread '-Wl,-rpath,$ORIGIN/:/opt/repo/intel/2018/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64:/opt/repo/intel/2018/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64' -Wl,-rpath-link,/mnt/local/aradi/volatile/xtb/build_intel/ -Wl,-rpath-link,/opt/repo/intel/2018/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64 -Wl,-rpath-link,/opt/repo/intel/2018/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64 -lifcore -limf -Wl,--end-group
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
```

Any advices, how I get the things compiled? I am not a great expert with Meson, so the issues may be trivial.

Thanks in advance.

**Comment by awvwgk** [comment]
Usually I use the Intel compilers via `. /path/to/intel/bin/compilervars.sh intel64` which works fine on all machines/distros I tested it so far.

But the linkline with `cc` looks wrong to me, normally `meson` should use the `icc` to link the program.
I might be more helpful if I could have a look at the `meson-logs/meson-log.txt`.

**Comment by aradi** [comment]
OK, if the PKG_CONFIG environment variable is set up correctly for the Intel libraries, it seems to work. Interestingly, it also links then properly. Don't ask me why...
