### ISSUE TITLE
Obtaining crest binary

### ISSUE THREAD

**Issue by eljost** [grimme-lab/xtb#100]
Dear xtb developers,
what is the intended way to obtain the crest binary? It isn't on github yet, or is it?

With best regards,
Johannes

**Comment by awvwgk** [comment]
Currently the `crest` binary is distributed together with `xtb`. It is indeed closed source and not available on GH, but free for academic, non-commercial use, like `xtb` was in the past.

You can find the latest crest version [here](https://github.com/grimme-lab/xtb/releases/download/v6.2.1/crest-191028.tar.xz).
