### ISSUE TITLE
--tblite ignores solvation (--alpb & --gbsa)

### ISSUE THREAD

**Issue by TimoSommer** [grimme-lab/xtb#1015]
**Describe the bug**
If I run an xtb calculation with the --tblite flag, it will ignore the --alpb and --gbsa flags. Whatever solvent I input, or if I don't specify it at all, always gives me the same energy out. If the --tblite flag is removed, the energies differ for each solvent, as you would expect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Input file for testing, but should work always: [test.xyz.gz](https://github.com/grimme-lab/xtb/files/15037736/test.xyz.gz)
2. Run "xtb test.xyz  --tblite". The final energy that I get is -133.722563075203 Eh
3. Run "rm xtbrestart; xtb test.xyz  --tblite --alpb water". The final energy that I get is exactly the same as above.

**Expected behaviour**
I would expect the energy to differ depending on the solvation model, just as without the --tblite specification.

**Additional context**
Versions: 
MacOs 14.4.1
xtb 6.6.1

**Comment by Albkat** [comment]
Hello,
as of now, tblite does not have a fully functioning solvation implementation. 
I would suggest addressing this in tblite repository.

**Comment by TimoSommer** [comment]
Thanks for your opinion on this! I would suggest to add an error then if someone specifies --tblite together with a solvent, and also mentioning this in the documentation. This can become a little confusing otherwise if people are not aware of this limitation.

**Comment by Albkat** [comment]
Yes, that sounds like a good idea.
Thank you.

**Comment by TimoSommer** [comment]
Cool, thank you!
