### ISSUE TITLE
Meson test failed after installation

### ISSUE THREAD

**Issue by szbalogh** [grimme-lab/xtb#1016]
Dear Developers, 

I have limited experience with Linux installations. Only managed to install NWChem from source. Works great.
Now i would like to make some pre-adjustments to my molecules using xTB. First solo, then alongside with NWChem or Orca.
Could you please take a look on the attached test log?
I was installing from source with meson/ninja. 

One test failed, many stopped.

Is it normal?
Should i make a clean Linux/xTB install (,since my Linux is now a big mess i think from the trial and errors of intallations)
Or it may work?

Thank you in advance,
Szabolcs
[testlog.txt](https://github.com/grimme-lab/xtb/files/15058596/testlog.txt)

**Comment by Albkat** [comment]
Hello,

This should be fine, as your log file shows only one failure, which is with **numsa/cds**. This is a known issue.
