### ISSUE TITLE
cpcmx energies are inconsistent across different files

### ISSUE THREAD

**Issue by leifjacobson** [grimme-lab/xtb#1018]
Running the command `xtb -scc -grad --json --cpcmx water bar1M tmp.xyz` I get two different energies reported.
The energy reported by `stdout `and `xtbout.json` are consistent.  The energies reported in the files `gradient` and `tmp.engrad` differ from the `stdout` and `xtbout.json` values but are consistent with themselves.  This makes me wonder if the gradients are also not quite right in these files.

I am using version 6.7.0

Here is my example `tmp.xyz` file:
```
15

C 0.95292900 1.05050300 0.00865700
C -0.01674500 0.51057800 1.07190600
Cl -1.64771800 1.21658600 0.87400900
O -0.08091300 -0.91184400 0.98045300
C -0.39506800 -1.39000500 -0.28969000
N 0.57302200 -0.96295800 -1.26686200
C 0.61449100 0.48714000 -1.37847000
H 1.96914400 0.75821100 0.27566000
H 0.93584100 2.14042000 -0.00291400
H 0.32573600 0.78580600 2.06959900
H -1.40104200 -1.07000700 -0.57082800
H -0.40301300 -2.47982600 -0.23283500
H 0.39269900 -1.37818000 -2.17251000
H -0.34723200 0.86640000 -1.72824700
H 1.36966100 0.78396900 -2.10711900
```

**Comment by Albkat** [comment]
Hello,
CPCM-X is the post-SCC correction and currently does not provide gradients. In this case it means _stdout_ and _xtb.json_  print the energy with the CPCM-X contribution, whereas the _gradient_ and _tmp.engrad_ files contain only the gas phase energy.

**Comment by leifjacobson** [comment]
Thanks for the clarification @Albkat
