### ISSUE TITLE
aiss aggregate - parallel optimizations

### ISSUE THREAD

**Issue by manuelperezesc** [grimme-lab/xtb#1025]
I have been trying the aiss docking module of xTB for a while and I think it is quite impresive. I would like to know whether you have considered to parallelize the final optimizations, similar to what for example ORCA does in a NEB-based calculation. By this, many different optimizations can be on different cores, speeding up the whole process, which could make the iterative search of complex aggregates more feasible. 

Thanks

**Comment by cplett** [comment]
Hi,
Unfortunately, _xtb_ is not designed to perform multiple geometry optimizations in parallel.
However, each geometry optimization itself runs on multiple cores which might not reach the efficiency of running multiple optimizations in parallel, but is still rather efficient up to a certain amount of cores used.
