### ISSUE TITLE
How can I calculate the applied force on a specific atom with GFN2-xtb?

### ISSUE THREAD

**Issue by OkKakao** [grimme-lab/xtb#1029]
**Is your feature request related to a problem? Please describe.**
Hi.

I'm trying to calculate potential of mean force (PMF) by integrating mean force.

I used --grad for the calculation of potential energy gradient, and integrated it to get  PMF curve.

But I'm not sure this is the right way since the calculation result is different from the reference.

Is this reasonable way to calculate the PMF or Is there any method that I can use for the calculation?

I want to calculate to force applied to the specific atom.

**Comment by OkKakao** [comment]
> **Is your feature request related to a problem? Please describe. ** Hi.
> 
> I'm trying to calculate potential of mean force (PMF) by integrating mean force.
> 
> I used --grad for the calculation of potential energy gradient, and integrated it to get PMF curve.
> 
> But I'm not sure this is the right way since the calculation result is different from the reference.
> 
> Is this reasonable way to calculate the PMF or Is there any method that I can use for the calculation?
> 
> I want to calculate to force applied to the specific atom.

I found that the gradient can be referred as force according to https://github.com/grimme-lab/xtb/issues/46, however, I'm not sure that the gradient is F or -F. 

What is the sign of the gradient?

**Comment by icamps** [comment]
@OkKakao the forces are calculated as:

$\vec{F} = -\nabla U(x,y,z)$

**Comment by OkKakao** [comment]
> @OkKakao the forces are calculated as:
> 
> F→=−∇U(x,y,z)

I already know how to calculate the force from the gradient, but I just wondering that the specified gradients in the grad file is ∇U or -∇U. 

And this was ∇U as far as checked.

Thank you for your answer
