### ISSUE TITLE
aISS docking issue on a biological structure

### ISSUE THREAD

**Issue by UlysseFerier** [grimme-lab/xtb#1034]
[aISS.txt](https://github.com/grimme-lab/xtb/files/15233671/aISS.txt)
[CO.txt](https://github.com/grimme-lab/xtb/files/15233674/CO.txt)
[1KF1.txt](https://github.com/grimme-lab/xtb/files/15233675/1KF1.txt)

This ticked is focused on the new aISS software where we try to dock a carbon monoxide on a biological structure (PDB entry : 1KF1). XTB version : XTB/6.7.0. 

The command line used is the following :
xtb dock 1KF1.xyz CO.xyz --gbsa h2o --opt loose 
The structures used are the CO.txt and 1KF1.txt ones and the results are in the aISS.txt file. Note that a .CHRG file was used to specify the charges for each compound (0 for CO and -18 for 1KF1).

15 optimized structures were given by the software, but these issues could be found : 

**1) Out of range interaction energies calculated for the last docked structures (13 to 15) :**

```
 ---------------------------
      Interaction energies
   ---------------------------
 Attention: monomers are not optimized
 Interaction energies are not physical
 
  Lowest Interaction Energy:     -87.54 kcal/mol
  #   E_int (kcal/mol)
  1       -87.54
  2       -86.56
  3       -85.76
  4       -82.27
  5       -81.02
  6       -80.84
  7       -79.30
  8       -77.53
  9       -77.46
  10       -77.45
  11       -77.18
  12       -73.44
  13   1144006.88
  14   1144006.88
  15   1144006.88
```
**2) Multiple errors messages at the end of the calculation :**

```
########################################################################
[WARNING] Runtime exception occurred
-21708- xtb_geoopt: Trying to recover from failed geometry optimization
-21707- relaxation_engine_lbfgs_relax: SCF not converged, aborting...
-21706- xtb_calculator_singlepoint: Electronic structure method terminated
-21705- scf: Setup of Coulomb evaluator failed
-21704- type_latticepoint_update: Could not generate lattice points
.
.
.
.
-4- type_latticepoint_update: Could not generate lattice points
-3- relaxation_engine_lbfgs_relax: SCF not converged, aborting...
-2- xtb_calculator_singlepoint: Electronic structure method terminated
-1- scf: Self consistent charge iterator did not converge
########################################################################
```
We tried to dock other molecules on 1KF1 but none of the calculations were successful.

**Comment by mdewergi** [comment]
Hi!
Is there anyone checking issues down here or should I contact Stefan directly for these ?
Many thanks 
Marc

**Comment by Albkat** [comment]
Hello, 
I look through the issues time to time, but it is better to address the person who implemented the docking.
@cplett, could you have a look at this?

**Comment by mdewergi** [comment]
Hi Albert, issues reported by Ulysse are very important for his thesis. Can you on your side have a look to the 1032?
Many thanks

**Comment by cplett** [comment]
Hi,
it seems that some structures were generated where the GFN2-xTB optimization failed. You may either use the reasonably optimized structures (found in the file `optimized_structures.xyz`) or try GFN1-xTB for the final geometry optimizations.
