### ISSUE TITLE
C-API Error handling

### ISSUE THREAD

**Issue by nabbelbabbel** [grimme-lab/xtb#104]
### Preface:
From what I understand there is no way to generate Fortran(-only) code that throws exceptions that can be caught using the C-API.
For this reason I expected the status `int` that is the return value of all C-API functions to be this exception handle.

### Problem:
Using the C-API, running a lot of jobs in an automated fashion I now noticed that for most errors, the Fortran code runs into `stop` calls.
These are really bad for the C-API as they can not be caught.
Moreover it is also not possible to fork these executions into external threads.
As far as I understand the `stop` directive has managed to kill calling Python interpreters and more, it seems to be quite effective at stopping, well, everything.

This issue is a major roadblock for automated usage of the code using the API instead of text parsing.
Errors (bad input, wonky coordinates etc) are to be expected in bigger tool chains, and killing an entire tool chain every time it encounters errors is not really a good option.

### Possible Solutions:
From what I understand, there are two main options that would resolve this problem:
1. It is [possible](https://www.flannaghan.com/2014/08/27/pyrrtm-exceptions) to add some C code similar to `signal.h` that adds exceptions to the Fortran code. 
2. Any and all functions can only return a bad status `int` never kill the process and the upmost calling function gets to decide how that error is handled. In the executable this function (`main`) would kill the process, in the API it would return empty data and a bad status.

**Comment by awvwgk** [comment]
This somewhat overlaps with #98 point 3 and should partly be fixed by #102. Better input checks in the API should also be able to prevent cold fusion events or similar, I will note this for #102.

I did a Fortran code handling errors gracefully with `dftd4`, but this one is build up from scratch and not grown over time like `xtb`. Definitely a huge project to impose it on `xtb`, but worth the effort.
