### ISSUE TITLE
Can I apply unilateral periodic box condition separately for each molecules?

### ISSUE THREAD

**Issue by OkKakao** [grimme-lab/xtb#1046]
Hi. 

I'm trying to get the energy of the air-water interface with alkali halide cluster, so I want to apply unilateral periodic boundary condition along z direction.

How can I apply unilateral pbc exclusivlely on water molecules aside from the cluster?

**Comment by Thomas3R** [comment]
Hi,

In xtb it is currently not possible to apply periodic boundary conditions exclusively to selected atoms.
