### ISSUE TITLE
Hessian calculations with GFN-FF fail

### ISSUE THREAD

**Issue by ppinski-hqs** [grimme-lab/xtb#1054]
**Describe the bug**
Attempting to run different types of Hessian calculations (`--hess`, `--bhess`, `--ohess`) in combination with GFN-FF leads to crashes, even with an optimized starting geometry.

**To Reproduce**

1. happens with input file `c2h4.xyz` in the attached archive [hess.zip](https://github.com/user-attachments/files/15903475/hess.zip)
2. start `xtb` (binary release 6.7.0 from GitHub) with any of the following options:
    ```
    xtb c2h4.xyz --hess --gfnff --verbose >stdout 2>stderr
    xtb c2h4.xyz --bhess --gfnff --verbose >stdout 2>stderr
    xtb c2h4.xyz --ohess --gfnff --verbose >stdout 2>stderr
    ```
3. output showing the failed calculations for all three variants in the archive attached

**Expected behaviour**
Successful Hessian calculations with GFN-FF.

**Additional context**
These problems do not appear to happen without the `--gfnff` flag (that is with GFN2-xTB).

**Comment by haneug** [comment]
Maybe @Thomas3R can take a look?
