### ISSUE TITLE
File reads fail with ifx compilation

### ISSUE THREAD

**Issue by TyBalduf** [grimme-lab/xtb#1059]
**Describe the bug**
There is [another issue](https://github.com/grimme-lab/xtb/issues/908) saying that ifx compilation doesn't succeed. But, on Linux (Centos7), I am able to compile xTB-v6.7.0 with ifx 2024.0.2 using meson. However, once it is built, it fails immediately for any job while trying to read the input file:
```
>>> xtb h2o.xyz
forrtl: severe (268): end of record during read, unit -129, file /home/balduf/repos/testing/h2o.xyz
Image              PC                Routine            Line        Source
libifcore.so.5     00007FB451CE6CC8  for__io_return        Unknown  Unknown
libifcore.so.5     00007FB451D26A2A  for_read_seq_fmt_     Unknown  Unknown
libifcore.so.5     00007FB451D24710  for_read_seq_fmt      Unknown  Unknown
xtb                00000000005A4671  getline                    50  systools.F90
xtb                000000000078A593  mirror_line               118  readin.f90
xtb                00000000007EBB71  rdcontrol                 771  set_module.f90
xtb                000000000042AEA7  xtbmain                   288  main.F90
xtb                000000000043D8AC  xtb_prog_primary           57  primary.f90
xtb                00000000004066ED  Unknown               Unknown  Unknown
libc-2.17.so       00007FB450C31555  __libc_start_main     Unknown  Unknown
xtb                0000000000406616  Unknown               Unknown  Unknown
```

It seems that `getline` isn't properly returning `iostat` and is just failing outright. 

If I add `eor` to the read in `getline` to force, it gets stuck in an infinite loop because the "end of file" [error code](https://www.intel.com/content/www/us/en/docs/fortran-compiler/developer-guide-reference/2023-0/list-of-runtime-error-messages.html) returned is 24, which is not recognized by `is_iostat_end`. 

If I add a check for 24, it correctly finishes trying to read the input file, but then fails again with the "severe (268): end of record" during `readmolecule`.

**To Reproduce**
`meson setup xtb build --buildtype=release` with Fortran compiler set to ifx. `xtb -h` should work fine, but `xtb any_input.xyz` should fail immediately with an end of record error.

**Additional context**
Compiling v6.7.0 with ifort-2022.0.2 runs just fine with all the same settings.

I also made a small test program that just opens a file and applies `getline` to it repeatedly. Compiling with ifx, this seems to correctly handle `iostat`. So it seems like there is an issue with ifx misinterpreting something about how xTB opens files.

**Comment by awvwgk** [comment]
This behavior is quite surprising, it seems that ifx is deviating in behavior from most of the common Fortran compilers, not sure whether this behavior is still compliant with the Fortran standard and could be considered a bug in ifx. One option would be to check the [`getline` implementation in stdlib](https://github.com/fortran-lang/stdlib/blob/d996e436d38d8aa8b47749cc3d93d02793d9ae2f/src/stdlib_io.fypp#L426-L471) whether there is any update we can port back to xtb.

**Comment by TyBalduf** [comment]
I believe his was a false alarm. I was somehow compiling with ifx 2024, but also linking against parts of ifort 2022. 
I have to imagine this could cause all sorts of strange behavior, including this iostat issue.
