### ISSUE TITLE
Mark OpenMP dependency as `language: 'fortran'` in meson/meson.build

### ISSUE THREAD

**Issue by TyBalduf** [grimme-lab/xtb#1064]
**Is your feature request related to a problem? Please describe.**
Meson has issues with finding the OpenMP dependency on Mac with the clang compiler. [This issue](https://github.com/mesonbuild/meson/issues/7435) resolves one particular manifestation of this problem, but doesn't seem to completely resolve the issue for me (building with OpenMP enabled for this project still fails using ifort/clang as the Fortran/C compilers). 

While this is ultimately a Meson problem, its my understanding the xTB (and its various subprojects) really only use OpenMP in the Fortran part of the code, rather than the C portions. If the `omp_dep` in meson/meson.build was marked with the `language: 'fortran'` argument, it seems like it would resolve the clang compilation issues with the added bonus of clarifying the build requirements (i.e. noting that OpenMP is only needed for Fortran).

If I'm mistaken and the C code actually makes some non-trivial use of OpenMP, I can find an alternative workaround for myself. But if the C code really doesn't use OpenMP at all, this seems like a straightforward way to resolve my issue. 

**Describe the solution you'd like**
Add `language: 'fortan'` to any OpenMP dependency declaration in xTB and its subprojects

**Describe alternatives you've considered**
I can make these patches locally.

**If possible state how you can assist in providing data or code to to implement the feature**
I could go through and make pull requests for xTB and all its subprojects if its confirmed that the C code for them doesn't need to use OpenMP.

**Comment by awvwgk** [comment]
Unfortunately the issue described is not that easy. Also the C compiler needs to be aware of OpenMP for linking the executable and the shared library. So far on Mac this has been an issue because the default C compiler comes without OpenMP support.

I am happy to give using Fortran as language argument for OpenMP a try, not sure whether this will address the linking issue on Mac.

**Comment by TyBalduf** [comment]
Yeah its looks like its more complicated than I initially thought, As you noted, it eventually runs into portions where the C compiler needs OpenMP to define executables, libraries, etc.

I'll close the issue, since even if there is an eventual solution found for this, it likely won't be as simple as the proposal here.
