### ISSUE TITLE
Some question while using the xtb PBC calculation with gfnff 

### ISSUE THREAD

**Issue by qianmou2718** [grimme-lab/xtb#1069]
When I optimize an adsorbate complex structure using xtb, I notice that the unit cell changes, but I just want to do a pure geometry optimization.I don't know how to do this.
I use this code to optimize structure。
`xtb POSCAR --mcgfnff --opt`
[File.zip](https://github.com/user-attachments/files/16383976/File.zip)

**Comment by Thomas3R** [comment]
You can use the `--nocellopt` keyword to disable the optimization of lattice parameters.
