### ISSUE TITLE
Compile with Intel compiler suite 19

### ISSUE THREAD

**Issue by udo-w-schmitt** [grimme-lab/xtb#107]
Just tried to compile xtb according to the instructions on the main page using cmake with 
ifort Version **19.1.**0.166 Build 20191121 on Ubuntu 19.04.

The compile unfortunately fails in the dftd4 module due to undeclared variable tx,ty,tz in the parallel openmp sections:

xtb/dftd4.f90(2433): error #6752: Since the OpenMP* DEFAULT(NONE) clause applies, the PRIVATE, SHARED, REDUCTION, FIRSTPRIVATE, or LASTPRIVATE attribute must be explicitly specified for every variable.   [TX]
      do concurrent(tx = -rep(1):rep(1), &

So it seems that Intel 19 is somewhat more restrictive with respect to OpenMP declarations?

**Comment by awvwgk** [comment]
Seems to affect the loop counter of the concurrencies, those variables were threadprivate by default in previous versions, just like the loop counters of normal loops.

Looks like the OMP usage needs an overhaul (again).

**Comment by awvwgk** [comment]
I've currently only Intel 19.0.5.281 20190815 around, so I have to install a new version first to check and fix it.

**Comment by awvwgk** [comment]
These parts have been removed from the codebase by now. Therefore, I'm going to close this.
