### ISSUE TITLE
Segfaults in aISS submodule with precompiled release 6.7.1

### ISSUE THREAD

**Issue by b-rousse** [grimme-lab/xtb#1078]
**Describe the bug**
The aISS docking submodule segfaults in the latest xtb release (6.7.1) above a certain system size. I can confirm it is not related to OMP environment variables nor the ulimit -s unlimited command. Reverting to version 6.7.0 fixed the problem.

**To Reproduce**
Steps to reproduce the behaviour:
Use latest release 6.7.1, try: 
xtb dock PFOA.xyz cluster_min_3layer.xyz 

This is with release version 6.7.1.

Please note I cannot upload .xyz or .inp files, so files minimal_1.xyz and PFOA.xyz have been provided in .txt format.
[cluster_min_3layer.txt](https://github.com/user-attachments/files/16516354/cluster_min_3layer.txt)
[PFOA.txt](https://github.com/user-attachments/files/16516267/PFOA.txt)

**Additional notes**
I tried this on a node with 256 GB RAM, set OMP_NUM_THREADS=1, OMP_STACKSIZE=256G, and ulimit -s unlimited. It still crashed.

**Comment by cplett** [comment]
Hi,
Thank you very much for reporting the bug. 
The pull request #1089 should fix it, and with the next release, the aISS should work properly again.
In the meantime, I suggest using xtb version 6.7.0 or a compiled binary containing the latest pull request to use the docking.
