### ISSUE TITLE
Dock module not working in xtb v6.7.1

### ISSUE THREAD

**Issue by icamps** [grimme-lab/xtb#1079]
**Describe the bug**
Running a simple dock calculation with two small molecules (CO2 and NO2) with `6.7.1 (edcfbbe)` and `6.7.1 (ec4f388) (bleed)`.

**To Reproduce**
Steps to reproduce the behaviour:

1. opt_CO2.sdf and opt_NO2.sdf: 
[opt_CO2.sdf.txt](https://github.com/user-attachments/files/16533136/opt_CO2.sdf.txt)
[opt_NO2.sdf.txt](https://github.com/user-attachments/files/16533137/opt_NO2.sdf.txt)

3. start `xtb` with: `dock opt_CO2.sdf opt_NO2.sdf --opt normal --etemp 298 --verbose`
4. run `xtb` with your options and the `--verbose` flag
5. output showing the error: 
[log-6.7.1.txt](https://github.com/user-attachments/files/16533139/log-6.7.1.txt)
[log-bleed.txt](https://github.com/user-attachments/files/16533140/log-bleed.txt)

Please provide all input and output file such that we confirm your report.

**Expected behaviour**
The docking calculation run ok.

**Additional context**

**Comment by cplett** [comment]
Hi,
Thank you very much for reporting the bug. It appears to be a similar issue to #1078.
With the latest pull request #1089, the docking should work properly again.
In the meantime, I suggest using xtb version 6.7.0 or a compiled binary containing the latest pull request to use the docking.

**Comment by marcelmbn** [comment]
Should be resolved by https://github.com/grimme-lab/xtb/pull/1089.
