### ISSUE TITLE
CREST QCG with xtb 6.7.1: error while reading input coordinates

### ISSUE THREAD

**Issue by lizhiq16** [grimme-lab/xtb#1080]
**Describe the bug**
when I run the following:
crest mol0.xyz --qcg mol1.xyz --nsolv 2 --T 12 --ensemble --mdtime 50 --wscal 1.0

>``` 
> Solute geometry
>   molecular radius (Bohr**1):    8.33
>   molecular area   (Bohr**2): 1122.04
>   molecular volume (Bohr**3): 2422.34
>  Solvent geometry
>   molecular radius (Bohr**1):    8.33
>   molecular area   (Bohr**2): 1122.04
>   molecular volume (Bohr**3): 2422.34
> 
>   radius of solute    :    13.43
>   radius of solvent   :    13.43
> 
>   =========================================
>   |            Preoptimization            |
>   =========================================
>   Total Energy of solute:     -53.3225785 Eh
>   Total energy of solvent:    -53.3225785 Eh
> 
>   ________________________________________________________________________
> 
>   __________________     Solute Cluster Generation   _____________________
> 
>   ________________________________________________________________________
> 
> 
>   =========================================
>   |   quantum cluster growth: GROW        |
>   =========================================
> 
>  Solute:
>        unit ellipsoid axis a,b,c     :   0.371   0.334   0.295
>  Solvent:
>        unit ellipsoid axis a,b,c     :   0.371   0.334   0.295
> 
>   solvent anisotropy            :     1.108
>   solute anisotropy             :     1.108
>   roff inner wall               :     2.684
>   solute max dist               :    23.243
>   solvent max dist              :    23.243
>   inner unit axis               :     0.409     0.333     0.259
>   inner ellipsoid/Bohr          :    16.783    13.666    10.617
>   scaling factor outer ellipsoid:     1.000
>   outer ellipsoid/Bohr          :    25.283    22.815    20.109
> 
>   Size       E        De       Detot      Density     Eatom    av. R  Rlast   Volume    Opt
>             [Eh]    [kcal]     [kcal]     [u/Å^3]     [kcal]   [bohr] [bohr] [bohr^3]
> error while reading input coordinates
>```

**To Reproduce**
CREST 3.0.1 with xtb 6.7.1, the bug consistently occurs. 
However, CREST 3.0.1 with xtb 6.6.1, the process runs smoothly.

**Please provide all input and output file such that we confirm your report**
Use any solute and solvent molecules can reproduce this bug.

**Comment by marcelmbn** [comment]
This should probably be moved to https://github.com/crest-lab/crest. Maybe, you can have a look, @cplett @pprcht?

**Comment by lizhiq16** [comment]
As I mentioned, CREST 3.0.1 with xtb 6.6.1 runs smoothly. Therefore, the issue seems to be related to xtb 6.7.1.

**Comment by pprcht** [comment]
the error message originates from CREST, but I can't tell if something is wrong with the xtb output or with the I/O. 
However, can confirm xtb 6.6.1 runs through the algo smoothly... Did anything at all change with the input output of xtb 6.7.1?

**Comment by marcelmbn** [comment]
Maybe @Albkat can comment best on this topic.

**Comment by cplett** [comment]
This issue appears to be related to the problem reported in #1078 and #1079.
In xtb version 6.7.1, the docking module yields a segmentation fault, which also affects QCG, causing it not to work properly. The bug should be fixed with #1089 and likely only occurs in xtb 6.7.1. Therefore, I recommend using xtb versions 6.7.0 or 6.6.1 for the QCG runs until the next xtb version comes up, or using a compiled version that includes the pull request #1089.

**Comment by lizhiq16** [comment]
OK, I will use xtb versions 6.6.1. When the next xtb version comes up, I'll give it a try. Thanks for the help : )

**Comment by marcelmbn** [comment]
Should be resolved by https://github.com/grimme-lab/xtb/pull/1089.
