### ISSUE TITLE
Error on calculating the single point energy of graphene sheet.

### ISSUE THREAD

**Issue by haobamkisan** [grimme-lab/xtb#1084]
I tried to obtain the single-point energy of a complex consisting of a graphene sheet and an organic molecule. When I performed the calculation, the following errors occurred:
  
 [ERROR] Program stopped due to fatal error
-3- Single point calculation terminated
-2- xtb_calculator_singlepoint: Electronic structure method terminated
-1- scf: Self consistent charge iterator did not converge

The command used in the calculation is 
xtb GC.pdb --gfn 2 --sp > output

The complex coordinate is attached and extracted from the paper J. Am. Chem. Soc. 2024, 146, 2986−2996:
[coordinate.zip](https://github.com/user-attachments/files/16577596/coordinate.zip)

Thanks

**Comment by haneug** [comment]
Graphene sheets have small HOMO-LUMO gaps, which can make SCF convergence challenging. To overcome this, you can:
1. Increase Electronic Temperature: Adjust --etemp to 5000 to help stabilize convergence.
2. Enable Implicit Solvation: Use implicit solvation with GBSA (e.g., --gbsa water) to stabilize the electronic structure.
3. Try Alternative Methods without SCF: Consider using GFN0-xTB or GFN-FF, they may be sufficient for your needs.

**Comment by haobamkisan** [comment]
Now it is working fine. Thank you, @haneug and @marcelmbn
