### ISSUE TITLE
Compiling xtb with GCC?

### ISSUE THREAD

**Issue by susilehtola** [grimme-lab/xtb#11]
Hi, I'm wondering why you say you cannot build xtb with gcc and there's no plans to support it in the future. Standards compliant code should compile straight away with any compiler. Any issues in the code should be pretty easy to solve...

**Comment by awvwgk** [comment]
We are currently using a few Intel specific compiler extensions (which one in principle can get rid of, see #10), but the last time a tried, I run into an ICE with GCC8/GCC9 which I couldn't figure out.

**Comment by awvwgk** [comment]
With #10 merged there are only two ISO-C interfaces offending to GCC and the ICE which stops using `xtb` with GCC.

**Comment by susilehtola** [comment]
Did you file a ticket about the ICEs?

**Comment by awvwgk** [comment]
I was not able to track it down by now, so no.

**Comment by susilehtola** [comment]
Once the code builds with GCC and Gfortran, xtb can be included with linux distributions.
