### ISSUE TITLE
Can pTB method in xTB software caculate electronic coupling integrals

### ISSUE THREAD

**Issue by zhengcheng233** [grimme-lab/xtb#1129]
Recently, I read the https://doi.org/10.1063/5.0167484 and find that pTB method can accurate calculate the electronic coupling integrals at low cost. So I am wondering whether the xTB software support this function. If not, Is there any approach for me to realize this calculations.

**Comment by demonic-daisy** [comment]
pTB is not regularly implemented into the tblite library yet. So unfortunately, at the moment there is no convenient option for calculating coupling integrals with pTB in xtb. The calculations from the paper were conducted with an output-modified variant of the alpha-version of the ptb standalone, a bash script to prepare the output for post-processing, and a standalone fortran code for the actual calculation of the DIPRO integrals.
