### ISSUE TITLE
XTB and CREST handling of deuterium and D2O

### ISSUE THREAD

**Issue by tobigithub** [grimme-lab/xtb#116]
Hello,
just an inquiry, not sure if this could be a feature.

Deuterium labeling is used quite often in mass spectrometry and nuclear magnetic resonance (NMR) for compound identification of small molecules and proteins/peptides. The same goes for modelling of hydrogen-deuterium exchange experiments using molecular dynamics. Here routines like CREST and XTB could be really useful. I  am wondering if XTB actually would be able handle D and D2O, or if it is not possible (ever).

The element symbol could be D and then radius and expectation values, electronegativities and van-der-Waals radii as well as the GFN parameters can be added? That's my simplified view.

Currently it can not handle it:
````
#ERROR! Unknown element symbol: 'D'
abnormal termination of xtb
````

Thank you
Tobias

**Comment by awvwgk** [comment]
Unless you want to have dedicated parameters for deuterium (?), it should behave exactly like hydrogen from an electronic structure point of view. The only difference is the mass, which can be adjusted in the detailed input.

We had a similar discussion over at https://github.com/dftbplus/dftbplus/pull/379#issuecomment-585290036

**Comment by tobigithub** [comment]
@awvwgk 
just the element H and D and T maybe hard coded so they can be used together in a file. Although other isotopes come to my mind 15N, 17O that would be also worthwhile to model, especially during MD investigations.

In [xcontrol7](https://github.com/grimme-lab/xtb/blob/master/man/man7/xcontrol.7.txt) I  only found the $hess block. Basically if I have C6H6 with a single D atom, basically C6H5D, how would I set that via the element mass if there is no atom symbol? Could you also give an example for CH2DT? If I need to count and mark specific atoms in the XYZ file, thats quite cumbersome.

````
*element mass*: 'int','real',...::
    set mass of elements 'int' to 'real'
````
If not,  a xcontrol or general solution via dummy atoms (placeholders) would also be fine, not sure what is easier to do and cleaner. Problem is of course then the other isotopes ( 15N, 17O). More specifically if I think about CREST, I actually do not want to create individual xcontrol files for all kind of protomers, tautomers etc., i think that would be impossible. 

Or maybe adding a prefix and handling those from the XYZ file directly. Something like H, 1H, 2H,  3H or 16O, 17O, 18O see [isotope table](https://physics.nist.gov/cgi-bin/Compositions/stand_alone.pl)

````
Quantity = Values {
  H = 1.0
  D = 2.0
  T = 3.0
  C = 12.0
  16O = 15.994
  17O = 16.999
  18O = 17.999
  }
````


In the cheminformatics world or SMILES we also use [H][17O][H] or [H][17O][2H], so an XYZ file could also have D, T, 15N etc, I see no problem with that. Same goes for MOL files, they also handle isotopes. Of course that would also require to code for the MOL file reader/writer to be updated.

````

  Mrv1823 02262022262D          

  3  2  0  0  0  0            999 V2000
    0.8705    1.4509    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.2574    0.8989    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.5380    0.9660    0.0000 D   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  1  0  0  0  0
M  ISO  1   1  17
M  END
````

**Comment by awvwgk** [comment]
Still, I don't see the advantage of explicitly handling isotopes. They only differ in the mass, but not in their electronic parameters. If you want to modify their mass, it will only affect frequency calculations and molecular dynamics, which is possible with the current input as documented here: https://xtb-docs.readthedocs.io/en/latest/hessian.html#advanced-options

What is indeed not possible is to adjust the mass of hydrogen atoms in MD calculations, as we usually scale them to allow larger time steps.

We could allow D and T as symbols for H and try to populate the mass array in the geometry reader already. Which would also allow to use the mol-file `M  ISO` modifier.

For `crest` it doesn't make sense to allow isotopes (at best only as synonyms), since it only calculates energies. One exception is maybe the property mode, just talked with @pprcht about this.

**Comment by tobigithub** [comment]
@awvwgk 
I think my first description was too complicated, if we can simply add masses that's fine. I was not really focusing on how it can be implemented, any possible way is good!

Most importantly it would be nice if **xtb could handle isotopes at all**, because lots of researchers use NMR, ion mobility and mass spectrometry experiments. There are literally hundreds of thousands of papers on that. People used semiempiricals and DFT to model such effects in the past, so its doable. 

A) **IM**: https://www.google.com/search?q=ion+mobility+isotope+effects
B) **NMR**: https://www.google.com/search?q=NMR+isotope+effects
C) **MS**: https://www.google.com/search?q=mass+spectrometry+isotope+effects

1) I think ease of use is one big reason for allowing easy handling of isotopes, based on structures that are already in compound databases. For these we have mol/sdf files and can use them directly without any intervention or complicated conversions, thats nice.

2) the isotope labels **must** be tracked, so if we do MD simulations I want to see the labels (element name) and what and where isotopes go. In practice that is very important for modelling anything related to [mass spectrometry](https://onlinelibrary.wiley.com/doi/pdf/10.1002/jlcr.1386). 

3) There are common isotopes and having simple naming conventions allows for less complicated conversions when handling MOL/XYZ files. Dealing just with element numbers and masses (isosub) is just confusing. Specifically naming isotopes D, T, 12C, 13C, 14C , 14N, 15N, 16O, 17O, 18O makes visualizations and reading files much easier. Maybe the other cases can be handles just by element numbers and mass.   
**XYZ:** For example JMOL handles such special cases [JMOL XYZ](http://wiki.jmol.org/index.php/Support_for_isotopes#XYZ_format) ( Bob Hanson, 25 Sep 2006, jmol-users list. A new file format: "isotope-xyz" or XYZI. ) "Although not a standard feature of xyz, Jmol will accept a special extension of the format1 where the isotope mass prefixes the element symbol.   Example:    13C"
**MOL/SDF:** See [MDL CTFile](http://c4.cabrillo.edu/404/ctfile.pdf) can handle isotopes natively already. 

4) For CREST, the ability to calculate isotopically labelled protomers, tautomers, conformers would be absolutely important, again having D and T as symbols and others (14C , 15N, 16O). This would be a powerful option. Again I am not focusing on the implementation, but on the ability to handle reactions, [isotopically labelled protomers and tautomers](https://onlinelibrary.wiley.com/doi/pdf/10.1002/jlcr.1386)

I see this topic already has a new label, so thank you!

**Comment by awvwgk** [comment]
For me we have two problems here, first is simple and solved by #123, which is preserving the element (isotope) symbols, the second is to generate the masses while reading the geometry and not separately afterwards, this will require a few more changes but those should be done anyway.

**Comment by awvwgk** [comment]
@tobigithub A workaround would be available if #140 is merged. This allows to use this input to set the masses for atoms with a matching element symbol:

```
$hess
  element mass: D, 2.0, 18O, 17.999
```

I still have to come up with a better way of handling atomic masses in the program to make it automatic.

**Comment by tobigithub** [comment]
@awvwgk 
Thank you!

**Comment by awvwgk** [comment]
This issue is still only partly done and chances are rather low that it will get a complete fix in the next release(s). I will remove it from the next release and mark it open for contributions, as I will probably not implement a fix too soon.

**Comment by awvwgk** [comment]
This issue has been resolved from the `xtb` side by supporting additional element symbols and easier reference of those groups in the detailed input file.
