### ISSUE TITLE
Energy instability with ASE

### ISSUE THREAD

**Issue by aozalevsky** [grimme-lab/xtb#134]
During the test of XTB Python API through ASE (as implemented in the [v6.3-pre.1](https://github.com/grimme-lab/xtb/releases/tag/v6.3-pre.1)) I encountered strange GFN2 calculator behavior. 

in 10 independent runs, it returned different energies for a simple system of water molecule (notebook and coordinates are in the attach)

```
Initial energy: eV, Eh -137.9672149700932 -5.070201673907619
Initial energy: eV, Eh -137.96721497009327 -5.070201673907622
Initial energy: eV, Eh -137.96721497009318 -5.0702016739076186
Initial energy: eV, Eh -137.96721497009318 -5.0702016739076186
Initial energy: eV, Eh -137.96721497009327 -5.070201673907622
Initial energy: eV, Eh -137.96721497009315 -5.070201673907618
Initial energy: eV, Eh -137.9672149700932 -5.070201673907619
Initial energy: eV, Eh -137.9672149700932 -5.070201673907619
Initial energy: eV, Eh -137.96721497009324 -5.070201673907621
Initial energy: eV, Eh -137.96721497009324 -5.070201673907621
```

at the same time, if i run XTB binary for 10 times (with the full cleanup of the runtime dir) i get very consistent results:

```
silwer@srv ~/tmp/test_xtb $ cat ../xtb.log | grep TOT 
          | TOTAL ENERGY               -5.070201677391 Eh   |
          | TOTAL ENERGY               -5.070201677391 Eh   |
          | TOTAL ENERGY               -5.070201677391 Eh   |
          | TOTAL ENERGY               -5.070201677391 Eh   |
          | TOTAL ENERGY               -5.070201677391 Eh   |
          | TOTAL ENERGY               -5.070201677391 Eh   |
          | TOTAL ENERGY               -5.070201677391 Eh   |
          | TOTAL ENERGY               -5.070201677391 Eh   |
          | TOTAL ENERGY               -5.070201677391 Eh   |
          | TOTAL ENERGY               -5.070201677391 Eh   |

```

Is this the issue with the machine precision somewhere in the ACE internals or am I missing something?

**Comment by awvwgk** [comment]
Make sure to disable the restart (`--norestart`) for the binary and set the restart variable in the Calculator also to `False`, otherwise `xtb` will use restart information from the previous run.

The other issue are the actual convergence criteria (`--acc` and `accuracy`), which influence the final result. Also we should expect minor differences if the run is in parallel.

Usually errors in this region are not relevant for any actual computation.

**Comment by aozalevsky** [comment]
Oh, i used to recreate calc object at every run like this `mol = read("/home/domain/silwer/tmp/h2o.xyz", format='xyz')`

but with the explicit restart `mol.calc = GFN2(restart="False")` now results are much more reproducible. 

```
Initial energy: eV, Eh -137.96721497009327 -5.070201673907622
Initial energy: eV, Eh -137.96721497009327 -5.070201673907622
Initial energy: eV, Eh -137.9672149700932 -5.070201673907619
Initial energy: eV, Eh -137.96721497009327 -5.070201673907622
Initial energy: eV, Eh -137.9672149700932 -5.070201673907619
Initial energy: eV, Eh -137.9672149700932 -5.070201673907619
Initial energy: eV, Eh -137.9672149700932 -5.070201673907619
Initial energy: eV, Eh -137.9672149700932 -5.070201673907619
Initial energy: eV, Eh -137.96721497009327 -5.070201673907622
Initial energy: eV, Eh -137.96721497009327 -5.070201673907622
```


Although I should mention that the False should be of string type, not bool. Otherwise, i get following error:
```
~/prog/miniconda3/envs/xtb/lib/python3.6/site-packages/ase-3.19.0-py3.6.egg/ase/calculators/calculator.py in label(self, label)
    525             return
    526 
--> 527         tokens = label.rsplit('/', 1)
    528         if len(tokens) == 2:
    529             directory, prefix = tokens

AttributeError: 'bool' object has no attribute 'rsplit'
```

but it seems to be on the ASE side, not XTB.

**Comment by awvwgk** [comment]
One caveat, the restart is persistent between instances, even if you recreate them, because it is in a file written to disk. I should remove this hacky trick at some point.

**Comment by aozalevsky** [comment]
ouch. I expected, that since the introduction of the python API I can get rid of all the unnecessary io (I'm using XTB with GROMACS for the metadynamics qm/mm calculations in the HPC environment, thus any IO is very hurtful). seems i should look closely on the implementation on the IO matter. 

Thanks for the clarification!

**Comment by awvwgk** [comment]
The Python API and the ASE wrappers are dropped from this repository, therefore I'll close this issue.

The Python API can be found in https://github.com/grimme-lab/xtb-python now.
