### ISSUE TITLE
Allow calculations with UFF

### ISSUE THREAD

**Issue by awvwgk** [grimme-lab/xtb#148]
**Is your feature request related to a problem? Please describe.**
For comparisons with UFF on a common basis with methods implemented in `xtb` it would be advantageous to have an interface to an UFF implementation.

**Describe the solution you'd like**
Easy and painless interface to Turbomole's UFF module.

**Describe alternatives you've considered**
We implement UFF in `xtb` instead.

**Additional context**
A Turbomole driver for `ridft` and `rdgrad` is already present.

**Comment by dgasmith** [comment]
Which UFF? The forcefield version is in [RDKit](https://www.rdkit.org/docs/source/rdkit.Chem.rdForceFieldHelpers.html) which provides easy Python access. I suspect you are talking about a different method however.

**Comment by awvwgk** [comment]
We currently use the Turbomole implementation in the `uff` module there, but the Turbomole interface is somewhat let's say cumbersome. Driving other programs out of `xtb` is possible, like Mopac, Orca and Turbomole, so we can easily use them on a common basis with our optimization and frequency calculation infrastructure.

**Comment by dgasmith** [comment]
Wouldn't you want the opt/freq infrastructure as a third party as with your integration into ASE and QCEngine? Placing all of this centrally makes XTB become a monolith. 

Re: Turbomole, yea thats why I suggest RDKit both Python and C bindings available.

**Comment by awvwgk** [comment]
`xtb` *is* a monolith.

Of course, we want features of other frameworks as well, but we already have a solid base of our own. Implementing the metadynamics, the ANCopt and the RRHO thermodynamic functions in ASE or QCEngine is a huge effort.

**Comment by ghutchis** [comment]
If you decide to implement UFF on your own, please ping me. There are a bunch of typos / errors in the paper and several of us have written implementations around this. (For example, the angle term has a minima at 0° with no repulsion!)

**Comment by tobigithub** [comment]
@ghutchis and @awvwgk should we still use UFF compared to MMFF94 
https://arxiv.org/ftp/arxiv/papers/1705/1705.04308.pdf
looking at table 1 should we use it because of initial 3D optimizations or
available implementations or speed? Just want to know. because I usually try to avoid it?

**Comment by awvwgk** [comment]
@tobigithub If I'm correctly informed MMFF94 does not cover the entire PSE (only C, H, N, O, F, Si, P, S, Cl, Br,  I, Fe, Li, Na, K, Zn, Ca, Cu, and Mg), while UFF pretty much does. And since we are aiming to test on sets like the [TMG145](https://onlinelibrary.wiley.com/doi/abs/10.1002/anie.201904021), the d-block should be covered completely.

The idea is to provide access to existing methods, which are as general as the new GFN-FF. We did something similar with the PM methods and the interface to the `mopac` program, such that we could make fair comparisons between xTB and PM methods.
