### ISSUE TITLE
crash in xtb with conda-forge builds

### ISSUE THREAD

**Issue by ghutchis** [grimme-lab/xtb#150]
**Describe the bug**

Running `xtb` on Mac from `conda-forge` crashes immediately.

**To Reproduce**
Steps to reproduce the behaviour:

1. Install `xtb` with `conda install -c conda-forge xtb`
2. start `xtb` with any option (e.g., `xtb benzene.xyz -opt`)
3. crash:

```
 * started run on 2020/03/16 at 13:20:56.841     
At line 215 of file ../src/filetools.f90
Fortran runtime error: Inquire statement identifies an internal file

Error termination. Backtrace:
#0  0x10a24f64b
#1  0x10a250475
#2  0x10a250c50
```

I've tried multiple options, different file types - there's a crash at the same point.

I don't see anything obvious on that particular line - if there's a good way to get the call trace, please let me know. We're happy to help debug, although we don't have a huge amount of f90 experience.

**Comment by awvwgk** [comment]
Originates in the file registry handling:
https://github.com/grimme-lab/xtb/blob/42bb5a4f22b41481cf27c9343b9463bcba22a6d4/src/filetools.f90#L209-L221

So the question is now, is this an issue related to the c-f build or a general issue for OSX.

**Comment by awvwgk** [comment]
Also happens for Linux, so this is an issue with the new conda-forge build.

**Comment by awvwgk** [comment]
Yeah, always enjoying working around compiler bugs...
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84412

Why does it have to be GCC 7.3.0?

**Comment by awvwgk** [comment]
We will have a brute force solution here, since GCC 7.3.0 is buggy and cannot inquire a negative unit at all, we will *drop* the check completely, because there is no way to know. This might cause the program to crash with a runtime error if it attempts to close an already closed file, but this is better than always crashing at the check to prevent such case.

**Comment by awvwgk** [comment]
@ghutchis New version is up. This bug is a vendor issue, so it can't really be fixed, still it is now working in some hacky way :upside_down_face:.

**Comment by ghutchis** [comment]
Can confirm it works on Mac - thanks for the fix!

(Now to get an Avogadro plugin going.. 👍 )
