### ISSUE TITLE
Python print_level=0 parameter still prints GBSA report

### ISSUE THREAD

**Issue by ikalvet** [grimme-lab/xtb#160]
**Describe the bug**
When running xtb jobs in a Python script using solvation and print_level=0 parameter I still get the GBSA report printed to STDOUT. It successfully mutes all other output from xtb but not that.

>  Solvent             : h2o
>  Using internal parameter file: .param_gbsa2_h2o
>  Gsolv ref. state (COSMO-RS): gsolv [1 M gas/solution]
>  temperature (mdtemp)       :    300.00000000000000     
>  dielectric constant        :    80.200000000000003     
>  rho                        :    1.0000000000000000     
>  mass                       :    18.000000000000000     
>  surface tension            :    15.568945408385856     
>  probe radius               :   0.97531378999999996     
>  Gshift (Eh)                :    1.8574431267947933E-003
>  c1                         :    1.5524381700000001     
>  soset                      :   0.13032636000000000     
>  HB correction              :  T

From what I can tell from the Fortran source is that there's no printlevel control implemented in solv/gbobc.f90 and it writes these lines out no matter what.

**To Reproduce**
Basically any way of running XTB over Python with solvation. These lines of code are one example of how to see this issue in action:

```
mol = ase.Atoms(["H"])
calculator = xtb.GFN2(restart="False", solvent='h2o', print_level=0)
mol.set_calculator(calc=calculator)
e = mol.get_potential_energy()
```
Tested with Python xtb version 6.2.1 (as returned by `xtb.__version__`)

--------------------------
**Unrelated question**
Is it normal that xtb returns the energy in Python with eV as the unit? Or is that controlled by ASE? I can't seem to find obvious documentation on that, and my rather shallow search didn't reveal a way I could control that. Of course knowing that it's in eV allows me to just convert it, but it was surprising at first to see vastly different numbers coming out of Python-xtb compared to the standalone version.

**Comment by awvwgk** [comment]
This should definitely be muted.

The Python-API actually returns the value in Hartree, it is converted by the ASE calculator to eV:
https://github.com/grimme-lab/xtb/blob/02fef372e407b87e7c8ea16049348eed5ce5efb6/python/xtb/calculators.py#L141-L143
Since we provide an ASE calculator we follow the ASE convention here and do not attempt to override it.

**Comment by ikalvet** [comment]
> This should definitely be muted.
> 
> The Python-API actually returns the value in Hartree, it is converted by the ASE calculator to eV:
> 
> https://github.com/grimme-lab/xtb/blob/02fef372e407b87e7c8ea16049348eed5ce5efb6/python/xtb/calculators.py#L141-L143
> 
> Since we provide an ASE calculator we follow the ASE convention here and do not attempt to override it.

Thank you for explaining the units, that was actually pretty apparent in the code in the end...

I played around and found a hacky solution to muting the GBSA output, based on an example here:
[https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/](https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/)

I added this function to the interface.py file:
```
import ctypes, os, tempfile, io
from contextlib import contextmanager

__libc = ctypes.CDLL(None)
__c_stdout = ctypes.c_void_p.in_dll(__libc, 'stdout')

@contextmanager
def _stdout_redirector(stream):
    """
    Implementation from:
    https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/
    """
    # The original fd stdout points to. Usually 1 on POSIX systems.
    # io.UnsupportedOperation exception makes sure that the program will not
    #  crash when executed on an IDE (where sys.stdout.fileno() fails).
    try:
        original_stdout_fd = sys.stdout.fileno()
    except io.UnsupportedOperation:
        yield stream
        return

    def _redirect_stdout(to_fd):
        """Redirect stdout to the given file descriptor."""
        # Flush the C-level buffer stdout
        __libc.fflush(__c_stdout)
        # Flush and close sys.stdout - also closes the file descriptor (fd)
        sys.stdout.close()
        # Make original_stdout_fd point to the same file as to_fd
        os.dup2(to_fd, original_stdout_fd)
        # Create a new sys.stdout that points to the redirected fd
        sys.stdout = io.TextIOWrapper(os.fdopen(original_stdout_fd, 'wb'))

    # Save a copy of the original stdout fd in saved_stdout_fd
    saved_stdout_fd = os.dup(original_stdout_fd)
    try:
        # Create a temporary file and redirect stdout to it
        tfile = tempfile.TemporaryFile(mode='w+b')
        _redirect_stdout(tfile.fileno())
        # Yield to caller, then redirect stdout back to the saved fd
        yield
        _redirect_stdout(saved_stdout_fd)
        # Copy contents of temporary file to the given stream
        tfile.flush()
        tfile.seek(0, io.SEEK_SET)
        stream.write(tfile.read())
    finally:
        tfile.close()
        os.close(saved_stdout_fd)
```

And then I edited the XTBLibrary.GFN2Calculation function followingly:
```
        if options['print_level'] == 0:
            f = io.BytesIO()
            with _stdout_redirector(f):
                stat = self.library.GFN2_calculation(*args)
        else:
            stat = self.library.GFN2_calculation(*args)
```

Same edits would also have to be added to GFN0 and GFN1 functions if ended up using them as well. But this is understandably only a temporary hacky solution that does the trick for me right now.
