### ISSUE TITLE
periodic boundary condition in repulsion.f90?

### ISSUE THREAD

**Issue by weilaigit** [grimme-lab/xtb#166]
**Describe the bug**
It seems that the repulsive part of the total energy is calculated inside repulsion.f90. However, it seems that the pair distance is calculated as "rij = mol%xyz(:, iAt) - mol%xyz(:, jAt)" without applying the periodic boundary condition (PBC).  So for the periodic GFN0 and GFN1, the repulsive energy is treated as non-periodic?

**Comment by awvwgk** [comment]
The GFN0-xTB implementation has its own repulsion routine, which is independent of boundary conditions, so nothing to worry about. I will further reduce the code duplication by merged the GFN0-xTB and GFN1/GFN2-xTB repulsion routines at some point.

Periodic GFN1-xTB is right now not available on master, my first take on this was too slow, but I will put up a faster version soon. Not sure if I want to merge the non-selfconsistent calculator and the selfconsistent calculator first, to put all xTB methods on equal footing.
