### ISSUE TITLE
Periodic boundary conditions for the GFN-FF

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [grimme-lab/xtb#185]
Congrats on the _angew. chem._ paper on GFN-FF! It looks very promising! I see that there is a pre-release with support for GFN-FF, but when I use it on periodic systems, it aborts saying that only GFN0-xTB can use PBCs. Are there plans to enable the use of GFN-FF with PBCs, as illustrated in the paper?

**Comment by awvwgk** [comment]
We will look into periodic boundary conditions for the GFN-FF at some point, but I'm not sure when. There are some tricky terms we have to figure out first under PBCs but then this should be pretty straight-forward with the infrastructure we already have.

**Comment by sespic** [comment]
All geometry optimizations in Fig. 1 are performed with an implicit GBSA solvation model. For the metal-organic frameworks, we used the finite cutouts, that are shown.

**Comment by arosen93** [comment]
@sespic -- thanks for the clarification! Haven't had a chance to read it in-depth yet. Looking forward to it though.

**Comment by anton-s-n** [comment]
@sespic -- in the mentioned Angew. Chem. paper solvent was specified in the case of biomolecules only (i.e. GBSA(H2O) approach).
Could you please clarify what solvent within GBSA solvation model was used for MOF calculations?

**Comment by sespic** [comment]
For the MOF/MOP calculations we used GFN-FF/GBSA(THF).

**Comment by miroi** [comment]
Hello, any news concerning GFN0-xTB with PBCs ?

**Comment by awvwgk** [comment]
The xTB based methods already have support for periodic boundary conditions. GFN1-xTB and GFN2-xTB have full k-point periodic implementations in DFTB+ and GFN0-xTB has a Γ-point only implementation in `xtb`.

This thread mainly concerns the GFN-FF force field, which Thomas @Thomas3R is working on.

**Comment by Thomas3R** [comment]
Dear @miroi, the periodic implementation of GFN-FF has been released with xtb version 6.7.0.
