### ISSUE TITLE
Possible bug in setting parameter set for gfn0

### ISSUE THREAD

**Issue by gunnar1987** [grimme-lab/xtb#186]
First of all thank you for making the `xtb` code publicly available. Great work! I started using it for some of my work, but probably encountered a bug described below:

**The parameter set for GFN0 might be set wrong**
I was using the python interface to `xtb` and had problems to use gfn0, which resulted in a termination

> abnormal termination of peeq
ERROR STOP

To investigate this, I looked a bit into the `xtb` code and found a strange thing in `src/gfn_paramset.f90` in the subroutine `use_parameterset`

```
   case('.param_gfn0.xtb')
      return
      globpar = gfn0Globals
      call initGFN0(xtbData)
```

I think the return statement is misplaced, after commenting it out I have more luck with using gfn0 via the python interface, but one of the test to check the build fails if I run `ctest`. 

>
> The following tests FAILED:
>          71 - GFN0-xTB_SP_PBC (Failed)

I tend to believe that the test itself might be broken, but without knowing more about the code this is wild guessing. Maybe someone of you can have a look at it.

**Comment by awvwgk** [comment]
Be assured this `return` statement is placed in exactly this line on purpose, if you remove it things are going to break (as you already noticed). I must know, because I put it there in the first place (probably should have added a warning comment as well).

**Comment by awvwgk** [comment]
For a correct GFN0-xTB run, even if run via the API, `xtb` must read the respective parameter file, which is found in one of the directories in the `XTBPATH` environment variable. Make sure the `XTBPATH` is set and contains the parameter files.

The termination via `error stop` if the parameter file is not found is somewhat suboptimal, that is definitely something I have to fix.

**Comment by gunnar1987** [comment]
Ah okay, thank you. With `XTBPATH` containing the parameter file it works
