### ISSUE TITLE
Include Python bindings in conda installation

### ISSUE THREAD

**Issue by jhjensen2** [grimme-lab/xtb#193]
They don't seem to be included. Is there some reason for this?

**Comment by awvwgk** [comment]
Except for the usual time issue? Not really. Would be nice to have this in the conda package, which would finally provide a sane way to install the python bindings.

**Comment by awvwgk** [comment]
Oh, there seems to be some interest. Let's put it that way, if you know how to do it, I'm happy to accept your contribution at https://github.com/conda-forge/xtb-feedstock

**Comment by jhjensen2** [comment]
I just meant that the python subdirectory should be included, so setup.py is there. That way one could do the pip install. But maybe there is some technical reason for why that is difficult. I don't know anything about making conda installs

**Comment by awvwgk** [comment]
Got a working version, depending on how fast I can fix my local conda environment it might be available today.

**Comment by awvwgk** [comment]
Let me know it this works for you.

**Comment by jhjensen2** [comment]
Yes, it seems to work, except that it now complains about "libxtb.so: cannot open shared object file: No such file or directory". I must be setting LD_LIBRARY_PATH wrong. Here is [a link to the code](https://colab.research.google.com/drive/1YeI4ceshB0G-YIdgVIC8aAJZs0RDKRrW?usp=sharing) in case you have any ideas.

Thank you very much for your help so far!

**Comment by awvwgk** [comment]
I was hoping for conda to take care of this. Fortunately, I implemented an overwrite for loading the library:
```python
from xtb import GFN0 as GFN
from xtb.interface import XTBLibrary, load_library
libxtb = XTBLibrary(library=load_library('/usr/local/lib/libxtb.so'))
calc = GFN(library=libxtb)
```
This might help as a workaround until I figured out how to do a proper `ctypes` interface.

**Comment by jhjensen2** [comment]
Yep, that seems to work. Thank you so much!

**Comment by jhjensen2** [comment]
The python binding seem to me missing from conda install for v. 6.3.

**Comment by awvwgk** [comment]
The Python bindings have been removed from the xtb package, I'm currently putting up [xtb-python](https://github.com/grimme-lab/xtb-python) on conda-forge which will provide the Python API.

**Comment by awvwgk** [comment]
Just registered the `xtb-python` package on cf. It might take another moment to appear here: https://anaconda.org/conda-forge/xtb-python

**Comment by jhjensen2** [comment]
Thank you
