### ISSUE TITLE
Spin in Python API

### ISSUE THREAD

**Issue by arosen93** [grimme-lab/xtb#2]
Currently, there is no way to specify the spin (`--uhf` flag) using the Python API. Are there any plans to add this feature? I can look through the source code now that it's publicly available and see if I can get it to work if not.

**Comment by awvwgk** [comment]
Yes, it's true. I overlooked it when writing up the API, due to the fact that it is not that important for the TB-Hamiltonian, but I will add it.

**Comment by awvwgk** [comment]
I consider adding this to the API a breaking change, but I have to break the API compatibility in the next weeks anyway.

**Comment by Vsoethout** [comment]
I'm currently trying to do geometry optimization using the Python API and would like to specify the spin of the system. I wasn't sure if i should open a new feature request when i saw this this thread. I'm running xtb version 6.2.2 (655bc02) on a server. I've been looking through the python documentation and cant figure out how to specify the spin state when creating the ASE calculator in a similar way to how you can specify the electronic temperature. I see that the magnetic moment is taken from the Atoms object with ".get_initial_magnetic_moments()" but no way to override this definition of the magnetic_moment variable. I'm relatively new to python so it could very well be that i'm overlooking something here.
I've attached a model system showing that the python API does indeed take spin into consideration if i hard code the initial magnetic moments of the Atoms object, however I'd prefer to not have to do it in this way.

My question is: Is there a function to explicitly specify the spin state of the system like you can do with the --uhf flag in the command-line? or is this already possible but i cant seem to figure it out?

[tescase.txt](https://github.com/grimme-lab/xtb/files/4323756/tescase.txt)

**Comment by awvwgk** [comment]
Please don't post off-topic in closed issues. I moved your comment to a new issue: #141.
