### ISSUE TITLE
please include ORCA scripts

### ISSUE THREAD

**Issue by ekwan** [grimme-lab/xtb#207]
To get gsm working with xtb, we need some scripts to convert xtb files to fake orca files.  Could you please provide `ograd` and `tm2orca.py` in the repository?  (If that's not possible, I would appreciate an email.). Thanks!

**Comment by awvwgk** [comment]
This is a support request which should be directed at xtb@thch.uni-bonn.de, the issue tracker concerns only content in this repository.
