### ISSUE TITLE
Regarding GFN-FF Implementation

### ISSUE THREAD

**Issue by rmw83** [grimme-lab/xtb#221]
To what extent has the code for GFN-FF changed from the preview 6.3 release? In other words, is the preview version the final version?

**Comment by awvwgk** [comment]
From a method point of view, there has been a minor change from the preview to the upcoming release. This adds a new contribution to the hydrogen bond correction (see d8e0332fdf4300c584ae37434e812cd63c77ba6d).

From a code point of view, the first appearance on master with b8be0b8d73e9f5664a941cd35c2f04c25c64b092 (almost) represents the code in the preview. To get an overview what we changed just make a `git diff`.

**Comment by awvwgk** [comment]
I guess this is answered, closing it for now.
