### ISSUE TITLE
ASE API not working

### ISSUE THREAD

**Issue by schneiderfelipe** [grimme-lab/xtb#224]
**Describe the bug**
The ASE API seems not to be working (no calculators, e.g., `ImportError: cannot import name 'GFN2'`).

**To Reproduce**
Either

```python3
from xtb import GFN2
```

or

```bash
$ python3 scripts/xtb_opt.py
```

throws an `ImportError: cannot import name 'GFN1'` kind of error.

**Expected behaviour**
I expect the [code snippet in the documentation](https://xtb-docs.readthedocs.io/en/latest/dev_python.html#using-as-ase-calculator) to work. The import line above is part of it.

**Additional context**
I'm currently using xtb version 6.3.0 (40a182b), built today against OpenBlas, gcc/gfortran (Ubuntu 8.4.0-1ubuntu1~18.04).

---

I recompiled the code against gfortran due to a previous error when importing `GFN2` from Python (`libifcore.so.5: cannot open shared object file: No such file or directory`), which I believed was due to lacking ifort. Is ifort needed for the ASE API? Is this API gone for good (37ae399a97f53657926fe77729b874d1b9773ede)?

**Comment by awvwgk** [comment]
Please, keep in mind that you are using the master of branch of a git repository, this can occasionally lead to unexpected changes as PRs get merged (like #222).

Happens that I just removed the ASE bindings for the `xtb` master. This was done on purpose to address #95 in a somewhat drastic way.

**Comment by awvwgk** [comment]
The Python bindings for `xtb` will get migrated to their own repository, which I'm working on in this very moment. Performing this migration, unfortunately, required me to break a few thing, like API compatibility, which is not a nice thing to do, but I promise to put everything back together.

**Comment by schneiderfelipe** [comment]
Thanks for the prompt response! That is understandable, and I am glad that the ASE API will be kept. Looking forward to it!

**Comment by awvwgk** [comment]
The basic Python API is online at https://github.com/grimme-lab/xtb-python now.

No ASE Calculators yet, but they are next.
