### ISSUE TITLE
negative charge in command line

### ISSUE THREAD

**Issue by hokru** [grimme-lab/xtb#234]
**Describe the bug**
Cannot set negative charges in command line (anymore)

 xtb version 6.3.0 (007a1746ce07a5e37ef07acbf67b7b80c5373fa6) compiled by '@Linux' on 05/28/2020

```
xtb coord.xyz -P 16 --uhf 5 --chrg -5 
########################################################################
[ERROR] Program stopped due to fatal error
-4- Command line argument parsing failed
-3- prog_main_parseArguments: Unknown option '-5' provided
-2- prog_main_parseArguments: Molecular charge is not provided
```

**Comment by awvwgk** [comment]
Oh no, I should have seen this coming. As a workaround for now, you can put the total charge in a `.CHRG` file or append a `$chrg -5` to your geometry for this case.
