### ISSUE TITLE
Crest should test if input file provided exists

### ISSUE THREAD

**Issue by vingman** [grimme-lab/xtb#24]
**Is your feature request related to a problem? Please describe.**
I am attempting to include crest in an automated workflow, and am calling the command from inside a script. Due to an unfortunate typo, my script changed into the wrong directory. Thus, the input file I told crest to use did not exist in the current directory. When crest ran, it segfaulted. I spent some time playing with my settings for parallelization, assuming that was the issue, before noticing my typo.

**Describe the solution you'd like**
I think it would be nice to check if the necessary input files exist before proceeding to the actual meat of the code. A simple "file does not exist" error message would have told me exactly where to look to fix my issue and saved me some time.

I know this is kinda silly, but I think it would be very helpful! Especially since, to my knowledge, crest doesn't have a -define flag like xtb does to help me understand what settings/files are being appropriately read. Adding a feature similar to xtb's -define flag would also be helpful.

Thanks!

**Comment by awvwgk** [comment]
@pprcht  any thoughts here?

**Comment by pprcht** [comment]
Newer versions do this (plus some other changes).
Will be up sometime in the next couple days.

**Comment by awvwgk** [comment]
Should be fixed with the new binaries.
