### ISSUE TITLE
xtb with gfnff crahes with large (~1000 atoms) molecules

### ISSUE THREAD

**Issue by robpollice** [grimme-lab/xtb#242]
**Describe the bug**
Trying to optimize a large molecule (~1000 atoms) with gfnff crashes. Notably, the structure has been optimized with gfn0 without any problems. (Also crest crashes, probably because xtb crashes). Input XYZ and output are provided here: [xtb.zip](https://github.com/grimme-lab/xtb/files/4719731/xtb.zip)

I am using the pre-compiled version 6.3.0 of xtb.

**To Reproduce**
Steps to reproduce the behaviour:

1. Run `xtb mol_xtb.xyz -o normal --gfnff`
2. Output in `xtb_gfnff_opt.out`

**Comment by awvwgk** [comment]
Possibly relevant: https://xtb-docs.readthedocs.io/en/latest/gfnff.html#parallelisation

@sespic any idea other than the usual OMP stackoverflow?

**Comment by robpollice** [comment]
I had used 1G before, I changed it to 4G but still no change.

**Comment by sespic** [comment]
Works absolutely fine for me. Try OMP_NUM_THREADS=1 and MKL_NUM_THREADS=1. If this works, than you still have to increase OMP_STACKSIZE. Your output ends exactly at the position were the stacksize error usually occurs.

**Comment by robpollice** [comment]
That solved the issue, thank you.
