### ISSUE TITLE
total energy for GFN-FF is incorrect with gbsa

### ISSUE THREAD

**Issue by nmardirossian** [grimme-lab/xtb#249]
I can't tell if this is just on my system or a general issue, but on Ubuntu 16 using the new 6.3.0 binary, 

xtb --scc --gbsa H2O --gfnff h2o.xyz

3
0 1
H 0.6746410000 1.2911040000 3.5652750000
O 0.1014890000 1.9431500000 3.9777450000
H -0.4085620000 2.3032160000 3.2466410000

produces the following output:

         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         ::                     SUMMARY                     ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         :: total energy              -0.351464301031 Eh    ::
         :: total w/o Gsasa/hb        -0.343691596128 Eh    ::
         :: gradient norm              0.007992718279 Eh/a0 ::
         ::.................................................::
         :: bond energy               -0.269572637410 Eh    ::
         :: angle energy               0.000386577499 Eh    ::
         :: torsion energy             0.000000000000 Eh    ::
         :: repulsion energy           0.030383716542 Eh    ::
         :: electrostat energy        -0.087602809496 Eh    ::
         :: dispersion energy         -0.000139331174 Eh    ::
         :: HB energy                  0.000000000000 Eh    ::
         :: XB energy                  0.000000000000 Eh    ::
         :: bonded atm energy          0.000000000000 Eh    ::
         :: external energy            0.000000000000 Eh    ::
         :: -> Gsolv                  -0.012347621449 Eh    ::
         ::    -> Gborn               -0.004574916546 Eh    ::
         ::    -> Gsasa                0.000224574092 Eh    ::
         ::    -> Ghb                 -0.009854722123 Eh    ::
         ::    -> Gshift               0.001857443127 Eh    ::
         :: add. restraining           0.000000000000 Eh    ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::

If I sum up the energy contributions (bond energy through Gsolv), I get -0.338892105. But the total energy says -0.351464301031. The only way I can get -0.351464301031 is by taking -0.338892105 and adding Gsolv and subtracting Gsasa.

With the 6.3.0 preview binary, I get: -0.338890705044 for the total energy (which is pretty close to the above 'correct answer'), but I think with that version, the Gsolv printout is wrong (i.e., Gsolv == Gsasa):

         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         ::                     SUMMARY                     ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         :: total energy              -0.338890705044 Eh    ::
         :: total w/o Gsasa/hb        -0.331118000140 Eh    ::
         :: gradient norm              0.007992294433 Eh/a0 ::
         ::.................................................::
         :: bond energy               -0.269572637410 Eh    ::
         :: angle energy               0.000386577499 Eh    ::
         :: torsion energy             0.000000000000 Eh    ::
         :: repulsion energy           0.030383716542 Eh    ::
         :: electrostat energy        -0.087602809496 Eh    ::
         :: dispersion energy         -0.000137930729 Eh    ::
         :: HB energy                  0.000000000000 Eh    ::
         :: XB energy                  0.000000000000 Eh    ::
         :: bonded atm energy          0.000000000000 Eh    ::
         :: external energy            0.000000000000 Eh    ::
         **:: -> Gsolv                   0.000224574092 Eh    ::**
         ::    -> Gborn               -0.004574916546 Eh    ::
         **::    -> Gsasa                0.000224574092 Eh    ::**
         ::    -> Ghb                 -0.009854722123 Eh    ::
         ::    -> Gshift               0.001857443127 Eh    ::
         :: add. restraining           0.000000000000 Eh    ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::

**Comment by nmardirossian** [comment]
I think in lines 540-542 of gfnff_eg.f90, if the following modification is made:

      etot = ees + edisp + erep + ebond &
     &           + eangl + etors + ehb + exb + ebatm + eext &
     &           + gsolv + gshift + gborn + ghb

to

      etot = ees + edisp + erep + ebond &
     &           + eangl + etors + ehb + exb + ebatm + eext &
     &           + gsolv

then this will fix the issue, since gsolv is already gsasa + gshift + gborn + ghb at this point.

**Comment by sespic** [comment]
> ```
>   etot = ees + edisp + erep + ebond &
>  &           + eangl + etors + ehb + exb + ebatm + eext &
>  &           + gsolv
> ```

This is absolutely correct. We fixed the issue and added a GFN-FF/GBSA testsuite.
