### ISSUE TITLE
SDF CHG block atom indices are lost in the optimized output file

### ISSUE THREAD

**Issue by edwardclem** [grimme-lab/xtb#253]
**Describe the bug**
The atom indices of CHG blocks in output SDF files are incorrect. 

**To Reproduce**
Steps to reproduce the behaviour with test molecule `c1cccc[nH+]1`. Initial conformation produced with RDKit. 

XTB version 6.3.0 installed via conda.

Input structure: 
```


     RDKit          3D

 12 12  0  0  0  0  0  0  0  0999 V2000
    0.7335   -1.1520    0.0147 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3524    0.0923   -0.0186 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6067    1.2633   -0.0335 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7663    1.1351   -0.0139 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3353   -0.1137    0.0188 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5960   -1.2469    0.0330 N   0  0  0  0  0  4  0  0  0  0  0  0
    1.3356   -2.0595    0.0259 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.4232    0.1868   -0.0337 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.0544    2.2422   -0.0592 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3791    2.0497   -0.0252 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4077   -0.1982    0.0338 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0213   -2.1991    0.0579 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  6  1  1  0
  1  7  1  0
  2  8  1  0
  3  9  1  0
  4 10  1  0
  5 11  1  0
  6 12  1  0
M  CHG  1   6   1
M  END
$$$$

```

XTB command: `xtb -P 1 --norestart --namespace testmol --chrg 1 --gfn 1 --opt tight testmol.sdf`

Output structure:

```

  xtb     06092011403D
xtb: 6.3.0 (e296fc5)
 12 12  0     0  0            999 V2000
    0.7617   -1.1328    0.0139 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3815    0.0986   -0.0191 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6040    1.2521   -0.0332 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7826    1.1428   -0.0139 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3606   -0.1088    0.0190 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5776   -1.1973    0.0318 N   0  3  0  0  0  4  0  0  0  0  0  0
    1.2991   -2.0741    0.0267 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.4630    0.1535   -0.0335 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.0749    2.2283   -0.0591 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4126    2.0237   -0.0242 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4318   -0.2736    0.0356 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0190   -2.1124    0.0561 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  2  3  1  0  0  0  0
  3  4  2  0  0  0  0
  4  5  1  0  0  0  0
  5  6  2  0  0  0  0
  6  1  1  0  0  0  0
  1  7  1  0  0  0  0
  2  8  1  0  0  0  0
  3  9  1  0  0  0  0
  4 10  1  0  0  0  0
  5 11  1  0  0  0  0
  6 12  1  0  0  0  0
M  CHG   1   1   1
M  END
> <total energy / Eh>
    -16.525743548330

> <gradient norm / Eh/a0>
      0.000333073949

$$$$

```

The CHG block `M  CHG   1   1   1` does not match the CHG block from the original structure, and marks the charge as having been attached to the incorrect atom.

**Comment by awvwgk** [comment]
Two things, first the CHG block is actually ignored for this `xtb` invocation as the command line option charge will overwrite any other source of the total molecular charge. Second, we currently don't save the position of the charge block, if there is a total molecular charge, we will put it on the only atom that will exist for sure, which is the first one.

The reasoning for not saving the position of the charge is that we actually don't know where it will end up after we solve for the tight binding wavefunction, it might end up on a different atom or will be delocalized.

We maybe should follow a similar strategy on this like with the bond topology here, which is cached and just echoed in the end. Additionally we should perform a check not only on the bond topology, but also on possible charge localisation and amend the CT input.

**Comment by edwardclem** [comment]
Hi Sebastian,

Ah, that does make sense, thank you for the clarification! From my tests, it seems like `xtb` does not parse the total molecular charge from the CHG anyway, and sets charge to 0 by default if the option `--chrg 1` is not specified.

**Comment by edwardclem** [comment]
There's also another bug with how the CHG block is written - there are three spaces in between the "CHG" and the number following it, which trips up Openbabel and RDKit's SDF parsers. 

For instance, `M  CHG   1   1   1` does not work, while `M  CHG  1   1   1` does.

**Comment by awvwgk** [comment]
Haven't had time to look into this, the issue with the illformatted CHG block might something easy. Getting the charge read and stored correctly will require a little bit more attention, but shouldn't be to difficult.

I won't find enough time to work on this too soon, but I'll try to assist if anyone is taking on this issue in the mean time.
