### ISSUE TITLE
Dispersion Corrections

### ISSUE THREAD

**Issue by shaychaudhuri** [grimme-lab/xtb#260]
Hi,

I've been looking into different dispersion corrections implemented in this and from what I can tell, the only scheme that is implemented is DFT-D4. I think it would be great if other schemes could be implemented, namely DFT-D3 and the Tkatchenko-Scheffler method, but other methods that other software packages implement would also be great (e.g. many-body dispersion in FHI-aims). While Turbomole (which supports xTB) does include D3 corrections, there doesn't seem to be a way to implement this alongside xTB calculations. I think it would be a great feature if other dispersion correction schemes could be included.

Thanks,

Shay

**Comment by awvwgk** [comment]
DFT-D3 is already supported in `xtb`, but it is only used for GFN1-xTB. Not sure if there is much value in switching dispersion corrections for the methods.

Regarding TS and especially MBD in their standard formulation happen to be computationally demanding (compared to the tight binding calculation). I'm aware of a specialized version of TS and MBD which has been optimized for the DFTB Hamiltonian and would be therefore also applicable in the xTB context, yet I have not seen a self-consistent implementation in DFTB+.

**Comment by shaychaudhuri** [comment]
Is there a DFT-D3 implementation in GFN1-xTB that has zero damping i.e. no Becke-Johnson damping? From what I can tell, it's all DFT-D3(BJ) in xTB. 

To provide context, I'm trying to compare different code methods, and the reason why I'm preferring D3 to D4 at the moment is because I'm not sure how much I can trust the partial charges in my DFTB model, and the reason why I'm not interested in BJ damping is because it appears to only pertain to the short-range component of the interactions. 

I suppose if D3 is included in GFN1 then there probably doesn't need to be included in GFN2 as well, but is there room for flexibility with regards to the dispersion settings like damping?

**Comment by awvwgk** [comment]
I'm not sure if I can completely follow your arguments here.

> the reason why I'm preferring D3 to D4 at the moment is because I'm not sure how much I can trust the partial charges in my DFTB model

DFTB? Are we talking about GFN2-xTB here? There is one known issue with the self-consistent dispersion in the GFN2-xTB, which could be fixed by replacing the SC-D4 with the D4(EEQ).

> BJ damping [...] appears to only pertain to the short-range component of the interactions

Like it should, shouldn't it?

> I suppose if D3 is included in GFN1 then there probably doesn't need to be included in GFN2 as well, but is there room for flexibility with regards to the dispersion settings like damping?

We could allow some freedom in combining dispersion and Hamiltonians, in principle, like switching the SC-D4 in GFN2-xTB for a D3 or switching the D3 in GFN1-xTB for a SC-D4, but does this really make sense?

**Comment by shaychaudhuri** [comment]
Hi,

What I was trying to say was that like in my case for example, DFT-D3 was a more favourable dispersion correction to DFT-D4 due to the limitations of the model, so it might be a good idea for xTB to include both dispersion corrections so the more favourable one could be chosen. What I didn't realise was that GFN1 already supported D3 and only saw that GFN2 supported D4, but I think the D3 implementation in GFN1 includes damping, and it might be a good idea to introduce greater flexibility i.e. having D3, D3 & damping and D4, as dispersion correction options (like Turbomole does). 

Thanks,

Shay

**Comment by awvwgk** [comment]
I guess we are using different vocabularies here. I'm still confused by D3 vs D3 & damping, do you mean D3(0) and D3(BJ), respectively? Because they both have damping, like D4 or most other dispersion corrections.

**Comment by shaychaudhuri** [comment]
Hi,

Yes, sorry that's what I mean, D3(0) and D3(BJ)

**Comment by awvwgk** [comment]
My main concern with this is that it is might cause significant confusion on what method to use with which dispersion correction as we usually don't specify the details of the dispersion correction, because they are an integral part of the parametrisation/model and rises the issue of reproducibility, in case the method is not correctly specified in a publication.

**Comment by shaychaudhuri** [comment]
Hi,

Ah OK, that's a valid point I suppose. Thank you for your responses!
