### ISSUE TITLE
Hessian calculation

### ISSUE THREAD

**Issue by eljost** [grimme-lab/xtb#271]
**Describe the bug**
I played around and wanted to see if XTB 6.3.1 (release from github) can be utilized for quick&dirty calculations of redox potentials with the Born-Haber-cycle. At one point a Hessian with solvent model on top of a gas-phase geometry is needed. Calling `xtb xtb.xyz --hess --gbsa dmso` leads to a `SIGSEGV`.

**To Reproduce**

***xtb.xyz***
```
21

  C  1.07803251 -0.55333490 -1.67537535
  C  0.86072365  0.84517216 -1.67928221
  C -0.53649004  1.07063254 -1.68550953
  C -1.18269978 -0.18851868 -1.68544021
  C -0.18486049 -1.19219168 -1.67915459
 Fe  0.00005522 -0.00001031  0.00004867
  C  0.84643246  0.85298325  1.68271595
  C  1.06456736 -0.54540159  1.68661106
  C -0.19794827 -1.18500895  1.68283579
  C -1.19637936 -0.18192919  1.67657473
  C -0.55090690  1.07760466  1.67650381
  H -0.36854516 -2.24645565  1.67674048
  H  2.02133033 -1.03571699  1.68388357
  H -1.02177616  2.02995332 -1.68187196
  H -2.24503150 -0.35357873 -1.68177489
  H -0.35617680 -2.25349848 -1.66985527
  H  2.03444574 -1.04417698 -1.66269903
  H  1.62308968  1.60314250 -1.67011673
  H -1.03671094  2.03659945  1.66475454
  H  1.60839764  1.61138567  1.67652810
  H -2.25854920 -0.34765144  1.66488303
```

***xtb call***
```
 xtb xtb.xyz --hess  --gbsa dmso
```

The error is given in the attached [verbose.log](https://github.com/grimme-lab/xtb/files/4803986/verbose.log).

**Expected behaviour**
No segfault.

**Additional context**
 I guess implicit solvent model + numerical hessian is not the wisest choice but I guess the current crash of the program is not intended.

**Comment by awvwgk** [comment]
Fixed with db14a9e767797c87162fb6ecc71f96d27f54c879 in #261
