### ISSUE TITLE
charptr is ignored in loadGFNXXTB_api

### ISSUE THREAD

**Issue by felixmusil** [grimme-lab/xtb#278]
**Describe the bug**

In `src/api/calculator.f90` the subroutines loadGFN0xTB_api, loadGFN1xTB_api, loadGFN2xTB_api accept an optional parameter `charptr` meant to allow the user to provide the path to the parameter file for the Calculator. This parameter is ignored because of a typo.

**To Solve the bug**

Following the example of loadGFNFF_api at lines 119-126 replace lines 186, 246, 306 with:
```
else
   filename = dummy
end if
```

**Comment by awvwgk** [comment]
Nice catch, thanks. Feel free to open a PR.
