### ISSUE TITLE
Periodic option: forrtl: severe (174): SIGSEGV, segmentation fault occurred

### ISSUE THREAD

**Issue by by-student-2017** [grimme-lab/xtb#280]
**Describe the bug**
  `"forrtl:` severe (174): SIGSEGV, segmentation fault occurred" on xtb_6.2.3
  The xtb-6.3.1 showed "core dumped."

**To Reproduce**
Steps to reproduce the behaviour:

1. happens with input (include input files)
  Al_3x3x3.poscar
2. start `xtb` with (all the options here)
  export OMP_STACKSIZE=4G
  xtb Al_3x3x3.poscar --periodic 2>&1 | tee Al_3x3x3.out
3. run `xtb` with your options and the `--verbose` flag
  export OMP_STACKSIZE=4G
  xtb Al_3x3x3.poscar --periodic --verbose 2>&1 | tee Al_3x3x3.out
4. output showing the error
  Al_3x3x3.out

Please provide all input and output file such that we confirm your report.
[xtb_error_verbose.zip](https://github.com/grimme-lab/xtb/files/4828774/xtb_error_verbose.zip)

**Expected behaviour**
  I would like to use this useful code "xtb" to calculate a periodic system using supercells so that it can be used for "potfit", "phono3py", etc.
  I was able to output the position and force of each atom, the lattice constant and its stress with the "--grad" option, but an error is output in the periodic structure of a large supercell (probably more than 100 atoms).

**Additional context**

**Comment by awvwgk** [comment]
The `--periodic` option has been removed from `xtb`, it should be invoked as `--gfn 0` instead as the detection of the boundary conditions only relies on the geometry input.

This error looks like an OMP stackoverflow, try to increase the size specified in `OMP_STACKSIZE`.

**Comment by by-student-2017** [comment]
Thank you for  reply.

The problem was solved by compiling "xtb-6.3.0" with GNU+Netlib instead of the binary and your advice and fixes.

Best Regards.
By Student
