### ISSUE TITLE
6.3.1-r1 GBSA: forrtl: severe (174): SIGSEGV, segmentation fault occurred

### ISSUE THREAD

**Issue by shuxiansheng2** [grimme-lab/xtb#284]
**Describe the bug**
when i try to print out  the solvent accessable surface area in a singlepoint calculation with gbsa, i get the error like below
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
xtb                0000000002FD9C54  Unknown               Unknown  Unknown
xtb                00000000031C1380  Unknown               Unknown  Unknown
xtb                0000000000497DE5  xtb_propertyoutpu        1224  property.f90
xtb                000000000048F7D8  xtb_propertyoutpu         155  property.f90
xtb                000000000041CD4A  xtb_prog_main_mp_         798  main.F90
xtb                000000000042B029  MAIN__                     55  primary.f90
xtb                00000000004020CE  Unknown               Unknown  Unknown
xtb                00000000031C2820  Unknown               Unknown  Unknown
xtb                0000000000401FB7  Unknown               Unknown  Unknown

it is ok when i try it using 6.3.0pre2 binary!!!

**To Reproduce**
Steps to reproduce the behaviour: 

1. happens with input (include input files)
2. start `xtb` with (all the options here)
3. run `xtb` with your options and the `--verbose` flag
4. output showing the error

export PATH=$PATH:/app/xtb-6.3.1/bin
export XTBPATH=/app/xtb-6.3.1/share/xtb
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_STACKSIZE=1000m
ulimit -s unlimited

Please provide all input and output file such that we confirm your report.
[xtbtest.zip](https://github.com/grimme-lab/xtb/files/4841891/xtbtest.zip)

**Expected behaviour**

**Additional context**
someone compile the code for windows platform, i get a similar error too.
http://bbs.keinsci.com/thread-18116-1-1.html

**Comment by awvwgk** [comment]
Thanks for the report, should be fixed by #285.

Regarding the windows build, I have neither access to the necessary software/hardware nor the time to tackle this issue. If you or your community (which is not accessible to me due to language barriers and a private thread) can come up with a windows build, I'm happy to accept a PR for this and will try to keep it working using a CI solution (GH actions or Travis CI seem to be a good start).
