### ISSUE TITLE
About windows version of xtb

### ISSUE THREAD

**Issue by njustcodingjs** [grimme-lab/xtb#287]
Dear developers of xtb:
  Recently, I have successfully compiled xtb under the cygwin64 environment and passed all the tests provided by the xtb source code. Can I pull a request for windows version? The attachments is the windows version I have compiled.
Compiliing environment: cygwin64
Compiler: GNU 7.4
HOW TO USE: Compress the package and add the directory in the PATH. Run xtb by type "xtb 1.xyz" in the terminial.
[xtb6.3.1-r1.zip](https://github.com/grimme-lab/xtb/files/4842086/xtb6.3.1-r1.zip)

**Comment by awvwgk** [comment]
Thanks a lot for your effort. I would suggest the following strategy:

1. Open a PR to implement all necessary changes to the build system (include also a short description in the meson and/or CMake guide)
2. Let's try to get a CI running, we have Travis-CI and GH actions for this purpose running already, but we are not limited to those two. This stage is probably a lot trial-and-error for me but I might give it a try.
   - for Travis CI windows support: https://docs.travis-ci.com/user/reference/windows/
   - for GH actions windows support: https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
3. Create a Windows build on the conda-forge feedstock (I will probably do this)

**Comment by awvwgk** [comment]
`xtb` is now built and tested with MinGW64, therefore I will close this issue as resolved.
