### ISSUE TITLE
Can we bring back atomization energies in the output?

### ISSUE THREAD

**Issue by ghutchis** [grimme-lab/xtb#29]
**Is your feature request related to a problem? Please describe.**
Older (before GitHub) versions of XTB would produce the atomization energy as part of the GFN1 output - in conjunction with the total SCF energy.

For many things (e.g., machine learning), the atomization energy is a more useful quantity than the total SCF energy. While workflows can calculate the atomization energy from the total SCF, it needs to be adjusted any time a molecule with different elements is presented (e.g. someone hands you something with Se or I, etc.)

**Describe the solution you'd like**
Ideally, I'd like the atomization energies to be automatically added to the output - or failing that, as an optional property.

**Describe alternatives you've considered**
It's obviously possible to manually calculate this, but workflows are much easier if it's done automatically.

**If possible state how you can assist in providing data or code to to implement the feature**
I'm happy to provide the atom self-energies, but I'd think you already have them as part of the various parameterizations.

**Comment by awvwgk** [comment]
I am usually not removing any printout, but I have the bad habit of reformatting it. The atomisation energy went at some point (when I redid the energy printout) to the verbose mode.

So I guess you are looking for the last line here:

```
         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         ::                     SUMMARY                     ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::
         :: total energy            -107.380580102557 Eh    ::
         :: gradient norm              0.045322044437 Eh/a0 ::
         :: HOMO-LUMO gap              0.216020816380 eV    ::
         ::.................................................::
         :: HOMO orbital eigv.        -9.083061053375 eV    ::
         :: LUMO orbital eigv.        -8.867040236995 eV    ::
         ::.................................................::
         :: SCC energy              -108.636375305275 Eh    ::
         :: -> isotropic ES            0.085922324799 Eh    ::
         :: -> anisotropic ES          0.006990366875 Eh    ::
         :: -> anisotropic XC          0.027445459200 Eh    ::
         :: -> dispersion             -0.080296019906 Eh    ::
         :: repulsion energy           1.254956308631 Eh    ::
         :: add. restraining           0.000000000000 Eh    ::
         ::.................................................::
         :: atomisation energy        18.532714363360 Eh    ::
         :::::::::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by ghutchis** [comment]
Great, thanks. I think the previous version used an abbreviation "atom. E" or something like that, so my Python parser didn't match anymore.

Thanks!
