### ISSUE TITLE
Interface with sTDA?

### ISSUE THREAD

**Issue by ghutchis** [grimme-lab/xtb#3]
With the update to XTB v6, the previous interface to sTDA seemingly broke (i.e., it didn't save the same temporary files).

Is there a new way to run STDA from an XTB calculation? Are you supposed to dump a `molden` file?

**Comment by awvwgk** [comment]
We dropped the sTDA-xTB Hamiltonian in v6, it is moved to the `stda` code. There might be some leftovers from the time I tried to redo it, but this is non-functional in v6.

`xtb` can dump a `molden` file. For more details see [here](https://xtb-docs.readthedocs.io/en/latest/properties.html#general-printout) or the `xcontrol(7)` manpage in the `$write` data group.

What is definitely missing is the binary dump from sTDA-xTB for `stda`, I might put it back in at some point.

**Comment by awvwgk** [comment]
Should be up soon: https://github.com/grimme-lab/stda
