### ISSUE TITLE
Ustable charge result at GFN2 v6.3.1.r1

### ISSUE THREAD

**Issue by jtyang-chem** [grimme-lab/xtb#302]
**Describe the bug**
- when run restart from `--etemp 1000.0`, the charge result is unstable, and make energy difference above 1 Eh
- simply restart with all set default(except `--acc 30`), in `v6.3.1.r1` the charge of Titanium is minus
- in `v6.2.2/meason`, the problems above are not seen, and energy is very different with `v6.3.1.r1` result

**To Reproduce**
Steps to reproduce the behaviour:
**Titanium charge results of GFN2 xtb**
||bare restart| restart from eTemp=1000K| restart from GFN0|
|-|-|-|-|
|6.2.2/meson|1.15649974| 1.15649974| - (1)|
|6.3.0/cmake|-3.37578359|  -3.37578246 or -6.91452539 (2)|-3.37573567|
|6.3.1.r1/binary| -3.37580313|  -12.85539578 (2)| -3.37580313|

(1) gfn0 not added in v6.2.2
(2) this answer is not stable for reproduce
*all test under `--acc 30`, the best accuracy which user can select.*
*Mulliken charges result at `b3lyp-D3BJ` level is : 1.919296*

**Energy results**
||bare restart| restart from eTemp=1000K| restart from GFN0|
|-|-|-|-|
|6.2.2/meson|-33.772220868798 | -33.772220868798| -|
|6.3.0/cmake| -36.548015442401|  -36.548015419753 or -38.919260841591| -36.548015296240 |
|6.3.1.r1/binary| -36.548015397706 |  -38.697447547064| -36.548015397706|

[bugTest.zip](https://github.com/grimme-lab/xtb/files/4907961/bugTest.zip)

**Expected behaviour**
- `v6.3.1.r1`  has a stable same or similar answer  as `v6.2.2/meason` has, no matter run what kind of restart
- positive Titanium charge value, (Mulliken charges result at `b3lyp-D3BJ` level is : 1.919296)

**Additional context**
- what forum about GFN program prefer? May some questions in science or in future are more suit ask on a forum

**Comment by awvwgk** [comment]
This might already be fixed with version 6.3.2, another thing worth to notice, especially for early transition metals is that the guess might be instable. Starting from a superposition of atomic densities (q=0) might improve the result.

```
$scc
  guess=sad
```

Also note, for the accuracy holds the lower the better, 30 is the worst possible accuracy for `xtb`.

**Comment by awvwgk** [comment]
@jtyang-chem  Is this issue still open or was it indeed fixed with the 6.3.2 release?

**Comment by jtyang-chem** [comment]
@awvwgk yes, it fixed in 6.3.2, sry for late reply.
