### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by Mircaz** [grimme-lab/xtb#304]
Hi!
I am trying to compile xtb on Centos 7 with meson using GCC 8.
After addition of all needed libraries "meson setup" finished successfully,
but "ninja -C build" is finishing with error that I am not able to interpret.
Could you please check both logs and help me with the issue?
Thanks!

the used meson setup:
----
export FC=gfortran CC=gcc
meson setup build --buildtype release --optimization 2 -Dla_backend=openblas
----
ninja build:
----
ninja -C build
----
Logs:
[meson_setup_log.txt](https://github.com/grimme-lab/xtb/files/4923344/meson_setup_log.txt)
[ninja_build_log.txt](https://github.com/grimme-lab/xtb/files/4923345/ninja_build_log.txt)

**Comment by awvwgk** [comment]
While your GCC seems to be version 8, your Fortran compiler is still version 4.8 and this can certainly not compile `xtb`.

**Comment by Mircaz** [comment]
Thanks a lot for so fast reply, Sebastian!
Indeed, it was old Fortran, I updated it and now build finished without errors but with many warnings and
and "ninja -C build test" finished with errors.
Files are attached.

Very appreciate!

[meson_gfc8_log.txt](https://github.com/grimme-lab/xtb/files/4923618/meson_gfc8_log.txt)
[build_gfc8_log.txt](https://github.com/grimme-lab/xtb/files/4923619/build_gfc8_log.txt)
[Ninja_test.txt](https://github.com/grimme-lab/xtb/files/4923620/Ninja_test.txt)

**Comment by awvwgk** [comment]
Try to increase the test timeout with `meson configure -Dtest_timeout=60` and maybe limit the number of parallel and/or concurrent testing with `OMP_NUM_THREADS=2,1 ninja test -j 2`.

**Comment by Mircaz** [comment]
Great, it looks better now:

Ok:                 89  
Expected Fail:      3   
Fail:               0   
Unexpected Pass:    0   
Skipped:            3   
Timeout:            0 

Is it OK?

**Comment by awvwgk** [comment]
This is indeed the expected outcome.

**Comment by Mircaz** [comment]
Thanks a lot!
