### ISSUE TITLE
Compile Windows version of xtb

### ISSUE THREAD

**Issue by liuyujie714** [grimme-lab/xtb#315]
Dear developers of  xtb:
Although xtb can be compiled with gfortran on windows by using Cygwin， its performance is very poor.  I think it is because gfortran is not a good choice on Windows, not on Linux.
Recently, I have successfully compiled xtb under Visual Studio 2019 + Intel Fortran compiler 19.1， Its performance is as good as on Linux.  Here I writed a Readme.md file about how to compile,  hope you can test it and add it into Release version

My Readme file: 
https://github.com/liuyujie714/MyScripts/blob/master/xtb_windows_vs_ifort.md

windows version of xtb attachment:
 https://www.dropbox.com/s/wwjsaqpd9v1h23a/xtb6.3.2_intel_nmake_4R8_win64.7z?dl=0

**Comment by awvwgk** [comment]
Thanks for putting this guide together, some of these changes can be included in `xtb` directly. I was always expecting issues with the handling of paths in the program because Windows uses different path separators, like `\` instead of `/` and `;` instead of `:`, these probably have to fixed in the `xtb` source as well.

**Comment by liuyujie714** [comment]
Yes,  although both / and \  can work fine on Windows, these minor problem can be solved by adding some  Macro definition.

**Comment by retinavr** [comment]
Hi
The readme file is not available any more. Has this been added to the master? I am very interested in help with compiling for windows as i want to use C API on windows.

**Comment by awvwgk** [comment]
So far it was not possible to establish support for Windows. To truly support Windows for `xtb` we either need a CI based solution, using MinGW or cygwin, or have a developer with access to Windows and compiler tool chains for this platform. Without access to Windows myself I can't really work on the latter solution.

I've made some progress to support Windows in CI builds in other projects (see [gcp](https://github.com/grimme-lab/gcp), [mctc-lib](https://github.com/grimme-lab/mctc-lib), [s-dftd3](https://github.com/awvwgk/simple-dftd3) and [toml-f](https://github.com/toml-f/toml-f)), but they are far less complex than `xtb`. The next step in my opinion would be to allow routine Windows builds for [dftd4](https://github.com/dftd4/dftd4), which is complexity-wise between `xtb` and the other projects I ported so far.

Help with this effort is still very welcome.

**Comment by kjelljorner** [comment]
As a workaround I would suggest using [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10). I've used xtb extensively with WSL and it runs perfectly.

**Comment by liuyujie714** [comment]
Sorry, I closed the readme.md file. Because official can not  adopt. 
However, I tested a simple C api program from xtb docs on Windows  and work fine.
I shared xtb version above has a xtb.lib file and i think you can use it directly in your C api program but need Intel MKL library.

**Comment by retinavr** [comment]
Hi

Thank you for the answers. Do you think it will be possible to write a C++ program using the C API and the xtb.lib file?
The reason i want to write C++ is that I want to use xtb in Unreal Engine for a project i am working on and UE4 only codes in C++. That is also the reason why i cannot use wsl. Please correct me if am wrong.

**Comment by liuyujie714** [comment]
> Hi
> 
> Thank you for the answers. Do you think it will be possible to write a C++ program using the C API and the xtb.lib file?
> The reason i want to write C++ is that I want to use xtb in Unreal Engine for a project i am working on and UE4 only codes in C++. That is also the reason why i cannot use wsl. Please correct me if am wrong.
> 
> Ps. Will it be possible for you to send the Readme file if you still have it?

I an not familiar with C++, but it can combine with xtb c api,  for example this github source https://github.com/conradhuebler/curcuma

Okay, I can open readme file please see this link: https://github.com/liuyujie714/temp/blob/main/Compiled_xtb_6.3.2_with_vs2019+Intel%20fortran.md

Please Note:
THIS METHOD  is not suitable for the latest xtb6.3.3 Because some linker reason but you can modify cmakelists.txt to let it works.

**Comment by retinavr** [comment]
Thank you for the help. I got past my previous error but am now getting an error saying fatal error LNK1104: cannot open file 'libiomp5md.lib'.

**Comment by awvwgk** [comment]
I created a CI workflow to build `xtb` with the MinGW toolchain distributed with [MSYS2](https://msys2.org), see #400. The POSIX environment Cygwin works as well, but is quite taxing on the CI installation. Notably the msys POSIX environment is not suitable to run `xtb` (missing openblas, lapack packages).

The Intel Fortran Windows compiler could be easily added to the meson build (not sure about CMake), since meson can actually distinguish between Intel Fortran Unix and Intel Fortran Windows compilers (see https://mesonbuild.com/Reference-tables.html#compiler-ids). Contributions are always welcome.

**Comment by awvwgk** [comment]
`xtb` is now built and tested on Windows using MinGW64, therefore I will close this issue as resolved.
