### ISSUE TITLE
gfn0 does not work if param_gfn0-xtb.txt not exist in working directory

### ISSUE THREAD

**Issue by liuyujie714** [grimme-lab/xtb#319]
Dear developer of xtb:
I want to know why the parameter of param_gfn0-xtb.txt  has not been compiled in xtb binary program.  Because we need copy param_gfn0-xtb.txt into working directory, `--gfn 0` option will work.
I checked `gfn_paramset.f90` file, then found this code started in line 68:
```fortran
   case('param_gfn0-xtb.txt')
      return
      globpar = gfn0Globals
      call initGFN0(xtbData)
```
I seems you skip this parameter compilation. Although code can be compiled after deleting ` return` ,  xtb binary does not work in the absence of param_gfn0-xtb.txt in working directory. 

So I hope you can solve this problem.

Thanks

**Comment by awvwgk** [comment]
I can assume you are working with your windows binary?

Than the relevant comments is https://github.com/grimme-lab/xtb/issues/315#issuecomment-669392185, the parameters files are searched for in a path variable using:

https://github.com/grimme-lab/xtb/blob/8e7263f12b82f61d157789985d018806468d0b73/src/mctc/mctc_systools.f90#L69-L83

The parameters `colon` and `slash` are set to their Unix specific values, therefore this routine will probably always fail on windows.

> I want to know why the parameter of param_gfn0-xtb.txt has not been compiled in xtb binary program.

For a discussion why I'm not going to add the GFN0-xTB parameters to the source code see https://github.com/grimme-lab/xtb/issues/186

**Comment by liuyujie714** [comment]
Okay, thank you very much！
