### ISSUE TITLE
Errors when compiling with PGI

### ISSUE THREAD

**Issue by patrickatkinson** [grimme-lab/xtb#325]
**Describe the bug**
There are three issues in total:

1. acf1ac7e1ac0e0c4bb98423fa3e7e44e812212be re-enabled the use of OpenMP for several files. When compiling with PGI compiler versions 19.10, 20.4, and 20.5, an internal compiler error is raised in `src/eeq_model.f90`. Commenting out the OpenMP statements in `get_coulomb_matrix_3d` and `get_coulomb_derivs_3d` is a workaround and lets the whole project compile. I have reported this compiler bug to PGI. 

2. In `src/generate_wsc.f90`, on the following line:
https://github.com/grimme-lab/xtb/blob/2f3864265352d3504da10c988632d89908801527/src/generate_wsc.f90#L97
`c` can sometimes equal 0, this causes an out-of-bounds access and segfaults with PGI.

3. With workarounds for the above issues, `xtb` still fails the following tests:

```
15/83 Wigner-Seitz Cell (3D)    FAIL           0.12s (exit status 1)
79/83 GFN0-xTB: API (PBC)       FAIL           0.12s (exit status 1)
80/83 GFN0-xTB: SRB (PBC)       FAIL           0.27s (exit status 1)
```

**To Reproduce**
Steps to reproduce the behaviour:

```
FC=pgfortran CC=pgcc meson setup build --buildtype release --optimization 2 -Dla_backend=netlib
ninja -C build test
```

**Expected behaviour**
The segfault shouldn't occur in `src/generate_wsc.f90`.
All tests should pass.

**Comment by awvwgk** [comment]
Thanks for reporting. The second issue might be fixed by ee011dafcbae4095725ba579301f03ee9d2d2ae5 in #269.

**Comment by patrickatkinson** [comment]
Apologies, looks like I was still working from acf1ac7e1ac0e0c4bb98423fa3e7e44e812212b

Working from the most recent commit (2f3864265352d3504da10c988632d89908801527) I am getting two additional internal compiler errors:

1. In `src/api/calculator.f90`, there is a bug with using deferred-length character variables in derived type constructors. For now this is easy enough to work around by assigning components one-by-one. I have reported this bug internally. 

2. In `src/hessian.f90`, there is an internal compiler error caused by calling `singlepoint` within the OpenMP region. For now, it is possible to workaround by commenting out the following OpenMP regions:

https://github.com/grimme-lab/xtb/blob/2f3864265352d3504da10c988632d89908801527/src/hessian.F90#L188
https://github.com/grimme-lab/xtb/blob/2f3864265352d3504da10c988632d89908801527/src/hessian.F90#L247

I'll dig into this a bit further and see if I can reproduce and report it. Looks like it was working fine before db14a9e767797c87162fb6ecc71f96d27f54c879

After the above workarounds (plus the workaround for `eeq_model.f90`), I am now getting the following failures:

```
15/94 Wigner-Seitz Cell (3D)    FAIL           0.07s (exit status 1)
66/94 GFN2-xTB: Solvation       FAIL           0.17s (exit status 1)
69/94 GFN2-xTB: API (GBSA)      FAIL           0.17s (exit status 1)
70/94 GFN2-xTB: API (GBSA+salt) FAIL           0.22s (exit status 1)
71/94 GFN2-xTB: d-Metal         FAIL           0.17s (exit status 1)
73/94 GFN1-xTB: Solvation       FAIL           0.22s (exit status 1)
78/94 GFN1-xTB: API (GBSA)      FAIL           0.12s (exit status 1)
81/94 GFN0-xTB: Solvation       FAIL           0.22s (exit status 1)
86/94 GFN0-xTB: API (PBC)       FAIL           0.17s (exit status 1)
87/94 GFN0-xTB: SRB (PBC)       FAIL           0.27s (exit status 1)
89/94 GFN-FF: Solvation         FAIL           0.12s (exit status 1)
92/94 GFN-FF: GBSA              FAIL           0.32s (exit status 1)
93/94 GFN-FF: Scale-up          FAIL           0.07s (exit status 1)
94/94 GFN-FF: PDB               FAIL           0.17s (exit status 1)
```

**Comment by patrickatkinson** [comment]
PS, yes ee011da in #269 did fix the issue in `src/generate_wsc.f90`, thanks!

**Comment by awvwgk** [comment]
With #327 merged the project does compile again with PGI 20.7, yet some tests are failing. Disabling shared memory parallelisation is fixing some of the issues but not all.

**Comment by awvwgk** [comment]
The remaining failures are due to the bug with using deferred-length character variables in derived type constructors, as all test using this feature currently fail.
