### ISSUE TITLE
CREST argument parsing -- xyz with '-H' in the name

### ISSUE THREAD

**Issue by bertadenes** [grimme-lab/xtb#35]
**Describe the bug**
If there is a '-H' in the name of the xyz file, (example-H2O.xyz), crest displays the help as one had called crest -H

**Expected behaviour**
Parsing input geometry as independet unicode/ASCII string

Present in CREST version 2.7.1, pre-compiled executables ran on Ubuntu 18.04 LTS.

**Comment by awvwgk** [comment]
This behaviour can't be reproduced in `crest` version 2.8
