### ISSUE TITLE
Do not see "adding snapshot to metadynamics bias" printout (Dynamic.f90)

### ISSUE THREAD

**Issue by AlessandroPonti** [grimme-lab/xtb#365]
Hello,
I am new to xTB. I have run a few metadynamic runs using xtb version 6.3.2 (452493c). The system is acetone bound to a constrained tungsten oxide cluster. A (partial) typical input can be found below.
I was surprised not to find any "adding snapshot to metadynamics bias" print in the output files, as described in lines 429-446 of dynamic.f90
I am wondering whether there is a serious flaw in my input and I am running meaningless calculations. The output trajectory seems reasonable but the absence of "adding snapshot" printouts in my output is disturbing since I am not sure that reference structures are updated.
Maybe my question is trivial (i am an xTB newby): if so, excuse me :-)
Thanks
Alessandro

-------------------------------------------
$md
   shake=0
   time=15.0   # in ps
   step=0.50   # in fs
   dump= 10.0  # in fs
  sdump= 250.  # in fs
   temp=573.   # in K
$metadyn
   atoms: 88-97
   save=100
   kpush=0.02
   alp=0.7
$end

**Comment by awvwgk** [comment]
The printout was added with 63baa29d216aadbd63e63bf636115689c19cda1c after the 6.2.3 release and is therefore not present.

**Comment by AlessandroPonti** [comment]
Thanks for the explanation @awvwgk!
