### ISSUE TITLE
IPEA parametrization through C and Python APIs?

### ISSUE THREAD

**Issue by kjelljorner** [grimme-lab/xtb#366]
Would it be possible to add the IPEA parametrization to the xtb Python interface? As I understand it, it would first need to be added to the C API as a subroutine and then added to the Python interface (hence why I am posting the issue here). Am I right that it would be completely analogous to the code that is already present for some of the other parametrizations? I'm not a Fortran coder, but could potentially come up with some code.

**Comment by awvwgk** [comment]
The C-API can already read a parameter file. The IPEA parameter file could just be passed to the setup for a GFN1-xTB calculator and it should work. The Python API is just not exposing this functionality and always passing a null pointer instead.

I'm not sure if it is worth to add the IPEA-xTB parameters to the `xtb` source code and allow to automatically load them without having to specify a parameter file.

**Comment by kjelljorner** [comment]
Probably if an easy workaround could be found via the GFN1-xTB I think that would be a good solution. I'm not really familiar with Fortran/C but do I understand it correctly that a line could be added in the Python interface here with appropriate parameters?
https://github.com/grimme-lab/xtb-python/blob/4b13e2a803ab361f572264d892d7305d3e674b7d/xtb/interface.py#L641

**Comment by kjelljorner** [comment]
Thanks, that's brilliant. I was trying to work on it yesterday but had problems installing xtb-python from source. Seems like you beat me to it 😄 Is it in the conda version already?

**Comment by awvwgk** [comment]
No, the conda-forge version is deployed on releases of `xtb-python`. I'm not sure when I will come around to make a 20.2 release for this project, meaning for now you have to build `xtb-python` from source if you want to try this feature:
https://xtb-python.readthedocs.io/en/latest/installation.html#building-from-source

Let me know if you encounter any problems building `xtb-python`.
