### ISSUE TITLE
6.3.3 do not return point charge gradient

### ISSUE THREAD

**Issue by xiki-tempula** [grimme-lab/xtb#374]
**Describe the bug**
I used to use xtb 6.2.1 and is interested in switching to 6.3.3.
I used to run `xtb orc_job_XTB.xyz --grad -c 0 -u 0 -P 1 --namespace orc_job --input orc_job_XTB.input`, which will give me point charge gradint `orc_job.pcgrad`.
However, running the same command with 6.3.3 will not give pcgrad file.

**Comment by mpurg** [comment]
Same problem here. 
ORCA 4.2.1 QM/MM fails with XTB 6.3.x due to missing .pcgrad file.

Works fine with 6.2.1.

**Comment by awvwgk** [comment]
Could you provide an example input for this case? I just tested with current master version and got a `pcgrad` file written.

To reproduce:
1. Create pcem input ``echo "1.0 0.0 0.0 0.0" > pcem.txt``
2. Create input file ``echo "\$embedding\ninput=pcem.txt" > pcem.inp``
3. Run `xtb` with ``xtb -I pcem.inp <coord> -v --namespace test``
4. Find
```
 unit  open   action     filename
  129 false : read       pcem.inp
  130 false : read       ./assets/inputs/xyz/caffeine.xyz
  131 false : read       pcem.inp
  132 false : read       param_gfn2-xtb.txt
  133 false : read       pcem.txt
  134 false : written    test.pcgrad
```

**Comment by xiki-tempula** [comment]
So I have a sample file water.pdb
```
ATOM      1  O   QMR     1       0.993  -0.556   1.776  0.00  0.00           O  
ATOM      2  H   QMR     1       0.742   0.390   1.928  0.00  0.00           H  
ATOM      3  H   QMR     1       0.147  -0.937   2.016  0.00  0.00           H  
END
```
If I run 
```
echo "1\n1.0 0.0 0.0 0.0" > pcem.txt
echo "\$embedding\ninput=pcem.txt" > pcem.inp
xtb -I pcem.inp water.pdb -v --namespace test -grad

```
I won;t get pcgrad

**Comment by awvwgk** [comment]
Thanks for providing the input and output.

Surprisingly, the very same input produces on my machine a `pcgrad` file. I'm a bit confused now...

**Comment by awvwgk** [comment]
Part of the problem reveals when the `pcharge` input name is left unspecified in the input file. In this case the default input name is only initialized/provided after the calculator setup and the the point charge file not read at all.

**Comment by awvwgk** [comment]
Finally got around to fix this bug. A version will be available shortly on the [continuous release tag](https://github.com/grimme-lab/xtb/releases/tag/bleed) or next month with the stable [v6.4.0 release](https://github.com/grimme-lab/xtb/milestone/5).

**Comment by xiki-tempula** [comment]
Thank you for the hard work
