### ISSUE TITLE
GFN2-xTB not available for PBCs

### ISSUE THREAD

**Issue by davidemitoli** [grimme-lab/xtb#376]
I'm trying to get familiar with xtb (v6.3.3). Everything seems to work fine, except for periodic systems.
Even with the inputs shown in the documentation, I cannot perform the calculation (single-point or optimization).
I was wondering if this is OS-related.

**To Reproduce**
Steps to reproduce the behaviour:

1. happens with diamond and CaF inputs (doc)
2. start `xtb` without any additional options
3. run `xtb` with `--verbose` flag
4. output showing the error

```
[ERROR] Program stopped due to fatal error
-3- Single point calculation terminated
-2- xtb_calculator_singlepoint: Electronic structure method terminated
-1- scf: Multipoles not available with PBC
########################################################################
abnormal termination of xtb
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP
```

Thank you for your valuable work and support.

**Comment by awvwgk** [comment]
As it says in the output, GFN2-xTB is currently not available under periodic boundary conditions. You can try ``--gfn 1`` instead.

**Comment by matterhorn103** [comment]
Was GFN2-xTB support actually implemented? I can still only periodic structures to work with `--gfn 1`.
