### ISSUE TITLE
meson shows @mkl_rt' not found 

### ISSUE THREAD

**Issue by chempc** [grimme-lab/xtb#378]
Only just started on Linux. Installed Intel  Parallel studio
iFort working 
library put in $PATH

ran meson :  program git found : NO (log appears not to point to a "archaic" (archive?) address

meson/meson.build:57:2: Error:  Fortran library not found
 (iFort is working)

(Intel parallel studio now seems to call libraries: libMKL_rt.so  when I look in install directory myself.

Maybe Intel have changed names in parallel studio 2020: trying to obtain Intel 17 to check.

**Comment by chempc** [comment]
I then tried cmake route and this seems to have worked.  (1 fail 86 -CAPI)
Tests run on N2 and H2O showed expected results.

**Comment by awvwgk** [comment]
Interesting, I'm using Intel Parallel Studio 2020, which has a `libmkl_rt.so`:
```
ls $MKLROOT/lib/intel64/libmkl_rt.so
```
Usually, if you setup Intel Parallel Studio with the shell script, things work fine:
```
source /opt/intel/bin/compilervars.sh intel64 -platform linux
```
But I remember having to patch the `compilervars.sh` script for my installation.

**Comment by awvwgk** [comment]
This seems to be resolved. Please reopen if you think otherwise.
