### ISSUE TITLE
Compability with ORCA/NAMD interface ?

### ISSUE THREAD

**Issue by qduez** [grimme-lab/xtb#380]
Dear all,

I'm trying to use XTB within ORCA in interface with NAMD to run QMMM simulations. When I launch a geometry optimization with NAMD, the first SCF of the ORCA/XTB simulation ends without any problem. 

The only warning I obtain is the following:

WARNING: Found dipole moment calculation with XTB calculation
  ===> : Switching off dipole moment calculation

However, NAMD crashes with the following error: 

ERROR: Could not find QM output file!

So I'm guessing that XTB does not produce the same output type like any other method ? I also tried using PBE, as implemented in ORCA, and I don't get any error. The only differences between the XTB and PBE output files are that .ges and .pcgrad files are missing from the XTB folder.

For info : Here's my config line for ORCA in NAMD:

qmConfigLine    "! XTB2 def2-tzvp ENGRAD"
qmConfigLine    "%%scf MaxIter 500 end"
qmConfigLine    "%%output PrintLevel Mini Print\[ P_Mulliken \] 1 Print\[P_AtCharges_M\] 1 end"
qmConfigLine    "%%pal nprocs 6 end"

I'm using NAMD 2.13, ORCA 4.2.1 and XTB 6.3.3.

Any help would be appreciated!

Thanks,

Quentin

**Comment by awvwgk** [comment]
Related to https://github.com/grimme-lab/xtb/issues/374

**Comment by qduez** [comment]
It works with version 6.2.1, thanks a lot !
