### ISSUE TITLE
problems parsing negative total charges on command line for charges <= -10

### ISSUE THREAD

**Issue by manuelmelle** [grimme-lab/xtb#389]
The --charge flag does not accept negative charges lower than -9 and stops with a fatal error. 

Command: 
xtb file.xyz -c -10 -gfn0

 

########################################################################
[ERROR] Program stopped due to fatal error
-6- Command line argument parsing failed
-5- prog_main_parseArguments: The use of '--gfn0' is discouraged, please use '--gfn 0' next time
-4- prog_main_parseArguments: the use of '-gfn0' is discouraged, please use '--gfn0' next time
-3- prog_main_parseArguments: Unknown option '--10' provided
-2- prog_main_parseArguments: the use of '-10' is discouraged, please use '--10' next time
-1- prog_main_parseArguments: Molecular charge is not provided
########################################################################
Command exited with non-zero status 128

regards

Manuel

**Comment by awvwgk** [comment]
You can set the charge in the detailed input with `$chrg -10` as a workaround for now.

**Comment by manuelmelle** [comment]
Thanks, yes, I was doing already something equivalent with the .CHRG file.
