### ISSUE TITLE
$fix atom does not work in MD simulation

### ISSUE THREAD

**Issue by amateurcat** [grimme-lab/xtb#391]
**Describe the bug**
I tried to run MD simulation for a ethane molecule with two carbon atom(atom 1 and 2) fixed in the space by $fix command, however those two atoms were still moving during the simulation

**To Reproduce**
Steps to reproduce the behaviour:
Any coordination file (e.g. xyz file of ethane)
input:
$fix
   atoms: 1,2
$end
$md
  temp=298.15
  time= 0.25
  dump= 50
  step=1
  hmass=1.0
  shake=0
$end

Shell command to run it:
xtb --CMA --md --input md_fix_1-2.inp ethane.xyz

Please provide all input and output file such that we confirm your report.

**Expected behaviour**
Coordinates of atom 1 and 2 should not change during the simulation

**Additional context**

**Comment by awvwgk** [comment]
This is the expected behaviour, fixing atoms is automatically disabled for dynamics, either use SHAKE or setup a constraint instead.

**Comment by awvwgk** [comment]
For a more detailed documentation of this behaviour see: https://xtb-docs.readthedocs.io/en/latest/xcontrol.html#exact-fixing
