### ISSUE TITLE
Bond order Formatting issue v6.3.3

### ISSUE THREAD

**Issue by dbuttar** [grimme-lab/xtb#397]
**Describe the bug**
I have moved to  xtb 6.3.3 and have noticed a formatting issue and change in the bond order ouput. 
Thanks,
            David

xtb 6.3.3
In the Wiberg/Mayer (AO) data of the output in 6.3.3 [data for atoms 4 and 5 on same line ]
No end of line for atom 4.

     3   6 C    3.878 --     5 N    1.389     2 N    1.372    13 N    0.963
     4  17 Cl   0.012 --     5   7 N    3.066 --     6 C    1.453     3 C    1.389
     6   6 C    3.895 --     5 N    1.453     7 C    1.330    12 H    0.949

xtb 6.2
In the Wiberg/Mayer (AO) data of the output in 6.2 [data for atoms 4 and 5 on separate lines]

     3  C   3.877        N    5 1.388    N    2 1.373    N   13 0.964
     4  Cl  0.013
     5  N   3.065        C    6 1.454    C    3 1.388

**To Reproduce**
6.3.3
xtb  product_complex.xyz --opt --chrg 0 --etemp 4000 --gbsa water --gfn 2 --input xcontrol --verbose

[product_complex.xyz.gz](https://github.com/grimme-lab/xtb/files/5702575/product_complex.xyz.gz)
[xcontrol.gz](https://github.com/grimme-lab/xtb/files/5702576/xcontrol.gz)
[xtb.out.gz](https://github.com/grimme-lab/xtb/files/5702577/xtb.out.gz)

**Comment by awvwgk** [comment]
Strange running your example locally results in the correctly formatted printout for me (both latest master and 6.3.3 release version):

```
     3   6 C    3.950 --     5 N    1.334     2 N    1.312    13 N    0.999
                             4 Cl   0.181
     4  17 Cl   0.460 --     3 C    0.181
     5   7 N    3.100 --     6 C    1.493     3 C    1.334
     6   6 C    3.962 --     5 N    1.493     7 C    1.304    12 H    0.947
```

**Comment by aslozada** [comment]
Wiberg/Mayer (AO) data. (xtb version 6.3.3 (5b13467))
    
     1   6 C    3.900 --     2 N    1.465     7 C    1.324    11 H    0.950
     2   7 N    3.054 --     1 C    1.465     3 C    1.371
     3   6 C    3.877 --     5 N    1.390     2 N    1.371    13 N    0.963
     4  17 Cl   0.012 --     5   7 N    3.066 --     6 C    1.453     3 C    1.390
     6   6 C    3.895 --     5 N    1.453     7 C    1.330    12 H    0.949
     7   6 C    3.914 --     6 C    1.330     1 C    1.324     8 N    1.024

**Comment by awvwgk** [comment]
@dbuttar @aslozada Sorry, still can't reproduce this with neither the release version (6.3.3) nor with the latest git version (fd185ae5e4b9f1dcbcece74b3a701cbe7e017274). The formatting is working all fine.
