### ISSUE TITLE
Segmentation fault with GFN1 

### ISSUE THREAD

**Issue by Tao4040** [grimme-lab/xtb#398]
**Describe the bug**
gfn 1 does not work with PBC.
xtb returns *** longjmp causes uninitialized stack frame *** and 'segmentation fault (core dumped)' when executed

**To Reproduce**
Steps to reproduce the behaviour:
1. H2O.coord from [H2O.zip](https://github.com/grimme-lab/xtb/files/5709865/H2O.zip)
2. start `xtb` as "xtb --gfn 1 H2O.coord --omd --charge 0 > H2O.out"
3. run `xtb` with your options and the `--verbose` flag
4. H2O.out [H2O.zip](https://github.com/grimme-lab/xtb/files/5709865/H2O.zip)

**Expected behaviour**
It suppose to run xtb gfn1 simulation with PBC. 
gfn 0 works.

**Additional context**
I have tried this in 4 different computer with ubuntu 6.3.3 and precompiled xtb

**Comment by awvwgk** [comment]
Is `xtb` setup according to: https://xtb-docs.readthedocs.io/en/latest/setup.html#setting-up-xtb

Duplicate of https://github.com/grimme-lab/xtb/issues/393, https://github.com/grimme-lab/xtb/issues/369, https://github.com/grimme-lab/xtb/issues/83, https://github.com/grimme-lab/xtb/issues/191

**Comment by Tao4040** [comment]
> Is `xtb` setup according to: https://xtb-docs.readthedocs.io/en/latest/setup.html#setting-up-xtb

Sorry for not mentioning that I have followed the documentation. In my .bashrc I have "set ulimit -s unlimited" and XTBPATH defined. I do not specify the parallelization parameters, yet xtb uses all 8 CPUs.

**Comment by awvwgk** [comment]
You have to either disable parallelisation by setting `OMP_NUM_THREADS=1` or increase the `OMP_STACKSIZE` to a reasonable number or you will run into the same issue as linked above.

**Comment by Tao4040** [comment]
Many thanks for the help.
Working commands:
xtb --gfn 1 H2O.coord --omd --charge 0 > H2O.out
OMP_STACKSIZE=10G xtb --gfn 1 H2O.coord --omd --charge 0 > H2O.out

**Comment by Tao4040** [comment]
The issue can be closed
