### ISSUE TITLE
Parallel performance of conda-forge build

### ISSUE THREAD

**Issue by kjelljorner** [grimme-lab/xtb#401]
The conda-forge build (6.3.3) of xtb seems to have poor parallel performance vs the pre-compiled binary (6.3.3). My preliminary calculations show that conda-forge actually gets much slower with more processors, while pre-compiled achieves a speed-up which plateaus with increasing number of processors.
![image](https://user-images.githubusercontent.com/36157530/102895386-82f97a80-445c-11eb-86a3-35612687d471.png)

The data was obtained by running a geometry optimization with `xtb test.xyz --opt --gbsa water`. Additionally, the number of processors was set through the environment variables, for example:
```
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_STACKSIZE=1000m
ulimit -s unlimited
```
Input xyz file, output files and sample submit script are attached.
[scaling.zip](https://github.com/grimme-lab/xtb/files/5730174/scaling.zip)

**Comment by awvwgk** [comment]
This information is not sufficient to be of any help. For issues with the conda-forge distribution I require some more information than the version number, `conda info` and `conda list` would be nice. Troubleshooting this without the processor family and the linear algebra libraries known is more like guessing.

As some general advice: the performance might dependent on the chosen linear algebra backend (OpenBLAS, MKL or BLIS for conda-forge) and the used processor. The release binary is always using MKL and includes default SSE2 and Intel AVX2 instruction sets. If you don't have an Intel CPU the release binary *will* use SSE2 instructions (so don't try the release version on AMD CPUs without recompiling for the correct instruction set first). Also the release version is autoparallized and autovectorized which is probably not done for the conda-forge version.

**Comment by kjelljorner** [comment]
Unfortunately I delayed reporting this error for some time and don't have access to the original conda environment. This is run on Intel CPUs (Skylake) with CentOS. I have replicated with a new conda environment and get different timings but still slower with more procs. The conda environment is generated with `conda create --name xtb-test python=3.7` and subsequent `conda install xtb -c conda-forge` with no additional packages so should be maximally pure.

| n_cpus | Wall time (s) |
| ------- |-------|
| 1 | 5.442 |
| 2 | 15.859 |
| 4 | 16.619 |
| 8 |  18.640 |
| 16 | 16.029 | 

I attach the new output files together with output from `conda info` and `conda list`.

[conda-forge-new.zip](https://github.com/grimme-lab/xtb/files/5730421/conda-forge-new.zip)

**Comment by awvwgk** [comment]
From your `conda list` output you can see that the OpenBLAS linear algebra backend is used. I wonder if you could try a new environment with MKL instead to get a fairer comparison between GCC and Intel compiled programs?

```
conda create --name xtb-mkl xtb "libblas=*=*mkl"
```

**Comment by kjelljorner** [comment]
Ok, that seems to be it. With mkl it is comparable to the pre-compiled. Didn't know that you could manually select the linear algebra library in this way so might be a useful addition to the xtb-python documentation.

| n_cpus | Wall time (s) |
| ------- |-------|
| 1 | 5.377 |
| 2 | 4.812 |
| 4 | 4.143 |
| 8 | 2.971 |
| 16 | 2.664 | 

[conda-forge-mkl.zip](https://github.com/grimme-lab/xtb/files/5730564/conda-forge-mkl.zip)

**Comment by awvwgk** [comment]
Default conda environments are usually not optimal, but robust. Have a look at the [conda-forge knowledge base](https://conda-forge.org/docs/maintainer/knowledge_base.html#switching-blas-implementation) for details.

**Comment by awvwgk** [comment]
Closing this as resolved.

**Comment by peastman** [comment]
Sorry to revive an old issue, but I'm still encountering this issue even when using MKL.  Here are the relevant packages from my conda environment.

```
libblas                   3.9.0            16_linux64_mkl    conda-forge
libcblas                  3.9.0            16_linux64_mkl    conda-forge
liblapack                 3.9.0            16_linux64_mkl    conda-forge
xtb                       6.5.1                h03160e7_1    conda-forge
xtb-python                22.1            py311h2582759_0    conda-forge
```

I have a 4 core, 8 thread Intel i7 running Ubuntu 18.04.  The following script repeatedly computes the energy of a molecule with 52 atoms.  Excluding the first iteration which is always slower than the rest, the "SCC iter." time varies from 0.034 to 0.098 with a mean of 0.062.  But if I `export OMP_NUM_THREADS=1,1`, the time is completely steady 0.025 with almost no variation at all.

<details><summary>script</summary>

```python
import numpy as np
from xtb.interface import Calculator, Param

numbers = np.array([8, 6, 6, 8, 6, 8, 6, 8, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
positions = np.array(
    [[-3.9257539, 4.01776479, 6.66035945],
    [-2.03344272, 7.15980123, 3.77887917],
    [4.42881379, 5.50264746, 1.58367912],
    [4.5071201, 2.96306842, 2.5762306],
    [1.70559203, 6.5964394, 1.26803138],
    [0.53485371, 6.27123653, 3.40972733],
    [4.58034553, 0.99855213, 0.83737662],
    [0.99888885, 7.4946225, -0.63771874],
    [3.3646105, 1.20486783, -1.51695305],
    [4.95843014, -3.65372263, 0.24041306],
    [4.4457012, -3.26784355, -2.33161898],
    [4.69654943, -5.45053659, -3.89762012],
    [-5.10690131, -0.39695066, -4.02402998],
    [4.88037269, -7.80919041, -2.85407697],
    [-6.93833189, 2.00028655, -3.36264049],
    [-3.72121921, 4.75711225, 4.49144472],
    [-5.29428295, 4.06239203, -2.12738085],
    [3.34876563, -0.95112553, -3.14117449],
    [-4.91497445, 3.55061472, 2.55390573],
    [-1.76435654, -0.60821572, 2.43802319],
    [-3.59082918, 3.07268988, 0.03703101],
    [-3.7802094, -1.32726819, -1.63926706],
    [-3.02063844, 0.30266573, 0.22994718],
    [-3.48805599, -3.88990138, -1.4652721],
    [-2.41356745, -4.91326537, 0.71267079],
    [5.52996148, -8.13586989, -0.25261697],
    [5.40261916, -6.10164948, 1.32390061],
    [-1.7844334, -3.18865499, 2.68727999],
    [4.99043304, -1.42708866, 1.76712029],
    [-2.0645267, 8.17530939, 5.56248646],
    [5.36766544, 6.75819716, 2.89613093],
    [3.00805753, 2.99944277, -2.27086107],
    [5.56510002, 5.61202776, -0.13293167],
    [3.31319067, -0.52456138, -5.16329012],
    [4.26537889, -5.24501088, -5.79253459],
    [-4.02495175, -0.15682954, -5.76507112],
    [-4.26885428, 5.18027713, -3.50066291],
    [-8.13350489, 1.33471526, -1.80288148],
    [-7.85950238, 2.56548982, -4.96126395],
    [-6.44553197, 5.36668891, -1.03584688],
    [-1.76313058, 4.04520735, -0.09869919],
    [-1.21831565, -4.12860227, 4.40513027],
    [-2.82239827, 8.39167896, 2.29490594],
    [-1.17953029, 0.49300389, 3.96962527],
    [-6.42830109, -1.96025221, -4.46101128],
    [-6.04546476, 2.06538535, 3.32317175],
    [-3.76287084, -5.01039069, -3.10544371],
    [5.86710118, -6.12628467, 3.39132765],
    [-2.14618829, -6.94038298, 0.72893785],
    [4.83781157, -9.29724226, -4.22376331],
    [5.87109416, -10.0360006, 0.47758472],
    [5.66170444, -1.73101894, 3.66936733]]
)
for i in range(10):
    calc = Calculator(Param.GFN2xTB, numbers, positions)
    res = calc.singlepoint()
```

</detail>
