### ISSUE TITLE
gfnff and solvation problem

### ISSUE THREAD

**Issue by gnarw** [grimme-lab/xtb#404]
I'm running xtb --gfnff mol.pdf --alpb water --opt tight
on a molecule with 930 atoms, charge -30 and spin 0.5.
The calculation completes normally but the geometry optimisation does not converge (stops after 4680 cycles)
Using --gbsa water, instead the geometry optimisation completes successfully.

xtb version is 6.3.3

Any suggestions how to solve this problem ?

**Comment by awvwgk** [comment]
We updated the ALPB water parameters for GFN-FF recently, I would suggest to try the latest commit as a remedy.

**Comment by gnarw** [comment]
This is in my output
 * xtb version 6.3.3 (5b13467) compiled by 'ehlert@majestix' on 2020-09-17
 Is this not the latest release ?

**Comment by awvwgk** [comment]
We updated the parameters for the upcoming 6.4 release, the latest version from this git repository already contains the updated parameters.

**Comment by awvwgk** [comment]
@gnarw Have a look at https://github.com/awvwgk/xtb/releases/tag/bleed for a build from the latest source.

**Comment by xiki-tempula** [comment]
@awvwgk Thank you for the work. I have recently encountered the same problem and am wondering if there is an estimate of the xtb 6.4 release? I was thinking that if it takes several months for the new release, I will use the bleeding edge release otherwise I will wait for the official release.

**Comment by awvwgk** [comment]
Some of the items on the [6.4.0 milestone](https://github.com/grimme-lab/xtb/milestone/5) are rather large, to get a release out soon I will have to defer some of them. But I have not created a strict timeline for the next official release yet.

**Comment by xiki-tempula** [comment]
@awvwgk Thank you for the explanation. I was wondering if it is worth to have a minor release of such as 6.3.4 where the alpb parameterisation for gfnff is fixed?

**Comment by awvwgk** [comment]
This should be resolved with the 6.4.0 release. Feel free to reopen if this is not the case.
