### ISSUE TITLE
Add the number of point charge as the first line of the pcgrad

### ISSUE THREAD

**Issue by xiki-tempula** [grimme-lab/xtb#41]
**Is your feature request related to a problem? Please describe.**
When using the QM/MM Orca interface of amber, it is required that the first line of the pcgrad should indicate the number of point charge in the system, which is not present in the pcgrad file.

**Describe the solution you'd like**
Normal Orca pcgrad used in amber has the format

```
996
0.002110738107 -0.000907351801 0.001687018358
-0.001089983662 0.000596535645 -0.000837938612
-0.001269634418 0.000426933814 -0.000967084019
-0.000165255832 0.000111137830 0.001623392385
```

Whereas xtb gives the format

```
0.00219465 -0.00095322 0.00174035
-0.00114767 0.00062388 -0.00085454
-0.00131498 0.00044651 -0.00096461
-0.00021916 0.00009229 0.00159509
```

**Describe alternatives you've considered**
I wonder if it is possible to alter the output format or at least have such an option during the compilation.

The way amber read the pc gradient is followed.

```
      ! MM gradients (none if do_grad)
      if ( nclatoms > 0 ) then
        open(iunit, file=basename//'.pcgrad', iostat=ios)
        if ( ios /= 0 ) then
          call sander_bomb('read_results (qm2_extern_orc_module)', &
            'Error opening Orca output file '//basename//'.pcgrad for reading', &
            'Will quit now')
        end if
        do
          read (iunit, '(a)', iostat = ios) read_buffer !First line is nclatoms
          ! End of file; data not found
          if (ios < 0) then
            call sander_bomb('read_results (qm2_extern_orc_module)', &
              'Error reading Orca output from file '//basename//'.pcgrad', &
              '(Empty file)')
          end if
          ! Read MM gradient data
          do i = 1, nclatoms
            read (iunit, '(3(f17.12))') dxyzcl(:,i)
          end do
          exit
        end do
        close(iunit)
      end if
```

**If possible state how you can assist in providing data or code to to implement the feature**
I can test if the xtb is working with amber as desired.

**Comment by awvwgk** [comment]
Writing of the point charge gradient is done here:

https://github.com/grimme-lab/xtb/blob/2609186b7e10f10aa7e7fcd6c1601f207efe553c/xtb/single.f90#L142-L149

Should be fixed by adding a line like
```fortran
write(ich, '(i0)') pcem%n
```

**Comment by xiki-tempula** [comment]
@awvwgk Thank you very much for the help. I wonder if it is possible to compile the altered xtb in old-kernel, please? I have tried to compile the altered file but failed in the last step where the compiler complains about `ld: cannot find -lpthread`.

**Comment by awvwgk** [comment]
To compile `xtb` you currently have to provide the static libraries on your system. Related to #39.

**Comment by awvwgk** [comment]
@xiki-tempula please checkout #40 for a possible solution on dynamic linking.

**Comment by awvwgk** [comment]
Since #42 is closed, I will close this one to.
