### ISSUE TITLE
Using Statically linked and Shared linked xtb 6.3.x result in different behavior with --opt options 

### ISSUE THREAD

**Issue by liuyujie714** [grimme-lab/xtb#415]
**Describe the bug**
On Windows,  I use Statically linked and Shared linked result in different result.
* Compiled with : **Intel Fortran Compiler + cl compiler + MKL + Openmp by Visual Studio 2019**
* Statically linked binary ：**reported fatal error**
* Shared linked binary ：   **normal end**

**Command line**
```xtb taxol.xyz --opt --verbose```
```--gfn``` option is not important for this test, Statically linked binary xtb still fatal error

**Output log file**
[file.zip](https://github.com/grimme-lab/xtb/files/5819408/file.zip)

**Expected behaviour**
I only want to know the original reason that caused different behavior

**Comment by awvwgk** [comment]
This is indeed surprising. Seems like the MKL libraries are named differently depending on the linking on Windows:

dynamic linking:
```
 mkl_intel_lp64_dll.lib mkl_intel_thread_dll.lib mkl_core_dll.lib libiomp5md.lib
```

static linking
```
 mkl_intel_lp64.lib mkl_intel_thread.lib mkl_core.lib libiomp5md.lib
```

`xtb` is always searching for the latter names, which works nicely on Unix systems due to the different suffixes for static and shared libraries.

**Comment by awvwgk** [comment]
Now I see, this was built with CMake rather than meson. For CMake this should boil down to the `FindLAPACK`/`FindBLAS` modules and how they interact with statically linking. Since CMake doesn't really support static linking this might be a CMake specific issue.

**Comment by liuyujie714** [comment]
I have tested master branch for this github repository, full static linking xtb binary works fine!
