### ISSUE TITLE
Get a full list of orbital energies for a PBC calculation

### ISSUE THREAD

**Issue by talipovm** [grimme-lab/xtb#427]
Hello xTB team,

first of all, thank you for creating and working on this great product!

xTB prints only a partial list of orbitals in the properties output while I would like to look at the full list of orbitals together with their energies. For the non-periodic calculations, I used the --molden keyword as a workaround. For the periodic calculations, the molden file is not generated with the --molden keyword (guess due to the incompatibility of the molden file format with the PBC calculations). If I did not miss a keyword for printing the full orbital list, I would like to request such a feature.

Thank you,
MRT

**Comment by awvwgk** [comment]
Try `xtb --json` to get the orbital energies.

**Comment by talipovm** [comment]
Thank you, it worked!
