### ISSUE TITLE
References swapped

### ISSUE THREAD

**Issue by seriussuires** [grimme-lab/xtb#430]
Hi there,

I noticed that the references for GFN2-xTB and GFN-xTB in the file xhelp.f90 are swapped. You have now
"for GFN2-xTB:
   * S. Grimme, C. Bannwarth, P. Shushkov, J. Chem. Theory Comput., 2017,
     13, 1989-2009. DOI: 10.1021/acs.jctc.7b00118
   for GFN1-xTB:
   * C. Bannwarth, S. Ehlert and S. Grimme., J. Chem. Theory Comput., 2019,
     15, 1652-1671. DOI: 10.1021/acs.jctc.8b01176"

where you should have instead    
"for GFN2-xTB:
   * C. Bannwarth, S. Ehlert and S. Grimme., J. Chem. Theory Comput., 2019,
     15, 1652-1671. DOI: 10.1021/acs.jctc.8b01176
   for GFN1-xTB:
   * S. Grimme, C. Bannwarth, P. Shushkov, J. Chem. Theory Comput., 2017,
     13, 1989-2009. DOI: 10.1021/acs.jctc.7b00118"

**Comment by awvwgk** [comment]
Nice catch, thanks a lot.

**Comment by seriussuires** [comment]
more than welcome =)
