### ISSUE TITLE
Overflow in molecular dynamics at 6 ns

### ISSUE THREAD

**Issue by awvwgk** [grimme-lab/xtb#434]
**Describe the bug**
Molecular dynamic run fails after 5.9 ns for a 16 ns simulation.

**To Reproduce**

Any geometry + this detailed input:
```
$md
   temp=490.0  # in K
   time=16000.0  # in ps
   dump= 200.0  # in fs
   step=  4.0  # in fs
   velo=false
   nvt =true
   hmass=4
   shake=2
   sccacc=2.0
$end
```

Failure at 5.9 ns:
```
1476000 5904.00    -59.26762   0.0450  490.  473.   -59.21444
block <Epot> / <T> :     -59.25605  493.     drift: -0.18D+02   Tbath : 490.
1476200 5904.80    -59.26762   0.0381  490.  401.   -59.22034
1476400 5905.60    -59.26762   0.0415  490.  437.   -59.21926
1476600 5906.40    -59.26762   0.0475  490.  499.   -59.21298
1476800 5907.20    -59.26761   0.0425  490.  447.   -59.21927
1477000 5908.00    -59.26761   0.0488  490.  514.   -59.21960
1477200 5908.80    -59.26761   0.0502  490.  528.   -59.21564
1477400 5909.60    -59.26761   0.0583  490.  614.   -59.22442
block <Epot> / <T> :     -59.26119  501.     drift: -0.18D+02   Tbath : 490.
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
xtb                0000000002F7412D  Unknown               Unknown  Unknown
xtb                0000000003188920  Unknown               Unknown  Unknown
xtb                00000000006BCA9D  xtb_dynamic_mp_md         432  dynamic.f90
xtb                000000000040E0E8  xtb_prog_main_mp_         911  main.F90
xtb                0000000000422B1B  MAIN__                     55  primary.f90
xtb                00000000004020CE  Unknown               Unknown  Unknown
xtb                0000000003189DC0  Unknown               Unknown  Unknown
xtb                0000000000401FB7  Unknown               Unknown  Unknown
```

**Expected behaviour**
Either preventing the overflow by using larger integer's as counters or by aborting the run when an integer overflow is likely to occur.

**Additional context**
Thanks to @drmewes for reporting.

**Comment by clavigne** [comment]
hey so I was trying to see if I could make progress on this. I can reproduce it on gfortran but not on ifort.

@awvwgk did you reproduce this on ifort? 

thanks

**Comment by awvwgk** [comment]
This issue was encountered with the `ifort` compiled release version (6.4.0).

**Comment by tsitsvero** [comment]
Seems I got it...

The array [`rege`](https://github.com/grimme-lab/xtb/blob/master/src/dynamic.f90#L179) is defined as having 1000 elements. After many MD steps counter `nreg` exceeds `rege`'s dimensionality, and call of [`regress`](https://github.com/grimme-lab/xtb/blob/master/src/dynamic.f90#L486) fails. This seems to cause this segfault error.

The simplest workaround is just to define bigger `rege`:
```fortran
real(wp) :: tstep0,tmax,nfreedom,t0,w0,t1,w1,ep_prec,rege(1000000)
```
Or set even bigger value...

A better workaround could be probably to rewrite the `subroutine regress(n1,n2,rege,slope)` by passing just 4 rolling numbers for regression.

**Comment by awvwgk** [comment]
Thanks, created a patch in #554.
