### ISSUE TITLE
Frequencies computation with constrain

### ISSUE THREAD

**Issue by aurelegermain** [grimme-lab/xtb#438]
Hi!

I am trying to understand what xtb is doing during a frequency calculation (--hess) for two identical structures, one constrained and the other one not.

Both structure are simply 4 water molecules optimised using gfn2 at the extreme level and using "xtb version 6.4.0 (d4b70c2) compiled by 'ehlert@majestix' on 2021-02-01".
```
12
 energy: -20.322911381564 gnorm: 0.000043687778 xtb: 6.4.0 (d4b70c2)
H         1.26086094411757    2.04534184442772   -0.77671310352129
O         0.85322885689183    1.19428292600105   -0.94367920888250
H         0.00589694966788    1.38764269253748   -1.40150694253969
H        -3.09190072547552   -0.66825124424749   -0.16546072940828
O        -2.71018082732070    0.19100311832524    0.01997854695884
H        -1.86622453801604    0.01327779671124    0.49034354044364
H        -0.00796344738929    0.22736296619111    1.87165218854644
O        -0.26169221470428   -0.23417250055899    1.07101161590415
H         0.24638870128212    0.17870767777696    0.34002896617838
H        -2.10658073612681    1.23318270476981   -1.24219720637332
O        -1.60026326051863    1.66397564901325   -1.96419098743938
H        -1.86877865323108    1.23373218520943   -2.77731181315521
```
And for one I constrain 3 water molecules during the frequency calculation "xtb --input xtb.inp input.xyz --hess --verbose" using this xtb.inp file:
```
$constrain
    atoms: 1-9
$end
```

After the computation I obtain this output for the constrained structure: 
[freq_constrained_output.txt](https://github.com/grimme-lab/xtb/files/5959476/freq_constrained_output.txt)

And this output for the structure without any constrain:
[freq_output.txt](https://github.com/grimme-lab/xtb/files/5959481/freq_output.txt)

Since both structures are identical I would have expected both frequency calculations to be the same (So same frequencies). And if not the same, I would have expected the constrained frequency calculation to not take into account the constrained part of the structure and compute less frequencies.

**Comment by awvwgk** [comment]
Welcome :wave:

The constraint is applied as harmonic potential on all the interatomic distances and the hessian is evaluated by numerical differentiation. The additional potential doesn't change the first derivative but the second derivatives, therefore it will be present in the hessian.

To remove atoms from the hessian calculation have a look at the `freeze` keyword in the `$fix` block.

**Comment by aurelegermain** [comment]
Thank you very much for your quick answer.
I did not know about the freeze keyword, I will look into it.
I think I can safely close this "issue" now.
