### ISSUE TITLE
optimization with ORCA using ANCOPT

### ISSUE THREAD

**Issue by fabothch** [grimme-lab/xtb#440]
**Describe the bug**

When using ORCA for ENGRAD and ANCOPT for optimization while supplying an xtb -I input, the provided orca-input file is not found and a xTB internal orca input guess is used. 

**To Reproduce**
Steps to reproduce the behaviour:

using   xtb version 6.4.0
1. happens with input (include input files)

```
$coord
-1.47630234909564  2.28940021446899  -0.00314631406347  c
 1.16895031480438  2.44006567358628  -0.00132196490305  c
 2.70062369993330  0.09439814015565   0.00193499905014  c
 1.48395888932131 -2.28661601860739   0.00318719469772  c
-1.16129377401180 -2.43728147640187   0.00136308043025  c
-2.69296715951866 -0.09161394353816  -0.00189415035226  c
-2.61760001370091  4.03475792409260  -0.00557105831573  h
 2.12340112469568  4.29134907893104  -0.00228900031138  h
 4.77919417466587  0.21896961200066   0.00336254389668  h
 2.62525655260376 -4.03197372936483   0.00561187602210  h
-2.11574458352515 -4.28856488174663   0.00233066026868  h
-4.77153763406226 -0.21618541443830  -0.00332220202335  h
$external
orca input file= inp
orca bin= /path_to/orca
$end
```

and inp:

```
! b97-3c
! grid4 nofinalgrid
! loosescf
! smallprint printgap noloewdin
! NOSOSCF
%MaxCore 8000
%output
       print[P_BondOrder_M] 1
       print[P_Mayer] 1
       print[P_basis] 2
end
! ENGRAD
%pal
    nprocs 2
end
%cpcm
    smd    true
    smdsolvent "WATER"
end
* xyzfile 0 1 inp.xyz
```
as well as opt.inp:

```
$opt 
maxcycle=8 
microcycle=8 
average conv=true 
hlow=0.01 
s6=30.00 
engine=lbfgs
$end

```

2. start `xtb` with xtb coord --opt lax --orca -I opt.inp > opt.out
3. run `xtb` with your options and the `--verbose` flag
generates:

```
orca input file           : orca.inp
orca input present        : false

.....

|  1> # orca input generated by xtb, this is not the right way of using orca!
|  2> %pal
|  3>    nprocs 1
|  4> end
|  5> %MaxCore 3000
|  6> ! b97-3c
|  7> %method
|  8>    runtyp gradient
|  9> end

....
```

The input (for orca inp) is not found. 

**Expected behaviour**

It does work when adding the lines:

```
$external
orca input file= inp
orca bin= /path_to/orca
```
both to the coord file and the opt.inp xtb detailed input file. 

When only adding it to the detailed input file an error for the geometry read is printed!

I would expect, that the coord file is read normally and all information concerning orca can be handled in the detailed input file.

**Comment by awvwgk** [comment]
Cannot be reproduced.
