### ISSUE TITLE
Evaluate meson 0.57.2

### ISSUE THREAD

**Issue by awvwgk** [grimme-lab/xtb#442]
Just released, meson 0.57.0 comes with a new dependency scanner for Fortran which replaces the dependecy hack feature used before.

Also, with meson 0.57.0 the `xtb` build fails with

```
[1/331] Module scanner.
[2/331] Module scanner.
[3/331] Module scanner.
ninja: build stopped: 'lib_xtb.a.p/src_mctc_signal.c.o' not mentioned in its dyndep file 'lib_xtb.a.p/depscan.dd'.
Command exited with non-zero status 1
```

Which is our only piece of C code in `xtb`. This is probably a bug in meson, we should try to get a minimal reproducer for reporting upstream.

- build failure reported upstream at https://github.com/mesonbuild/meson/issues/8377 

---

The meson 0.57.1 patch release is still broken for `xtb`.

- build is currently blocked by https://github.com/mesonbuild/meson/issues/8395

**Comment by craldaz** [comment]
I am also getting this error.

**Comment by awvwgk** [comment]
For the moment, just downgrade to meson 0.56.x or use a ninja version (<=1.9) that doesn't support dynamic dependencies to make meson 0.57.0 fallback to the old dependency tracking mechanism.

You can watch out for this work in progress patch https://github.com/mesonbuild/meson/pull/8383.

**Comment by craldaz** [comment]
How do I downgrade meson? When I install from pip I get version 0.47 but when I install from the GitHub I get 0.57.

**Comment by awvwgk** [comment]
To downgrade

```
pip install meson==0.56
```

or

```
mamba install meson=0.56
```

should work.

**Comment by awvwgk** [comment]
Meson 0.57.2 was just released, it should contain the required fixes to build `xtb` again :tada:. I will check the released version ASAP and close this issue once I have verified everything works as expected.
