### ISSUE TITLE
Allow writing of mdrestart in the molecular dynamics

### ISSUE THREAD

**Issue by awvwgk** [grimme-lab/xtb#444]
**Is your feature request related to a problem? Please describe.**

The mdrestart file is currently only written after the molecular dynamics has finished.

**Describe the solution you'd like**

Allow writing the mdrestart file in the dynamics simulation to allow restarting in case the jobs halts for any reason.

Was previously always written together with the trajectory dump:

https://github.com/grimme-lab/xtb/blob/c05f7c7049ebfe886a437d3d3da51c8202bf0133/src/dynamic.f90#L536

**Comment by MtoLStoN** [comment]
We added this in #760.
