### ISSUE TITLE
Detection of SCF non-convergence via C-API

### ISSUE THREAD

**Issue by steinmig** [grimme-lab/xtb#451]
**Is your feature request related to a problem? Please describe.**
I could not find a way to detect a non-converged SCF via the C-API.

**Describe the solution you'd like**
Get a proper error code for a non-converged SCF

**Describe alternatives you've considered**
In case this is against your design philosophy since the program ended normally, I tried two other things:

1) I tried the `xtb_getError()` call to get some std err information, but that was empty although the SCF did not converge. I cannot outrule that I made a mistake here, but I figured that you do not write the unconverged SCF into the error out, since your program is also continuing normally.

2) I then went around both of that and tried to parse the output of xtb. Here, I encountered the problem that I could not manage to release the output. I was able to call `xtb_setOutput()` and `xtb_releaseOutput()`. However, I did not get any error for the release, but still could not access the content of the outputfile (I only managed to get the very first line). Even after proper:
```
    xtb_delResults(&res);
    xtb_delCalculator(&calc);
    xtb_delMolecule(&mol);
    xtb_delEnvironment(&env);
```
I could not access the xtb output file. Only after my script itself was finished the complete output file was accessible in the console.

So the three solutions I see:
 - Change exit code (faster and easier for anything wrapping xtb, but maybe against your guidelines)
 - Write unconverged SCF into the stderr
 - Fixing the release of the output file (in case I did not make any mistakes)

**If possible state how you can assist in providing data or code to to implement the feature**
Since my wrapper is not released yet and has some more dependencies, it's hard for me to provide you with a MWE. I can try to set something up, in case it is necessary.

**Comment by awvwgk** [comment]
A non-convergend SCF is a particular case, I can see good reasons to raise it as an error, but there are also cases where an initially non-converged SCF can still be used, even if they are rare.

The easiest way to resolve this:
1. make failing SCF convergence an error rather than just warn
2. allow the `xtb` main driver to rescue this error and continue
3. propagate this error to the C-API with a dedicated error code to allow proper handling

**Comment by steinmig** [comment]
@awvwgk Thanks for the easy solution for the API user!

Do you have any update for me concerning a time estimate when this will be implemented?

**Comment by awvwgk** [comment]
The relevant logic is here:
https://github.com/grimme-lab/xtb/blob/f63f532eb023642304911129b8a6c99c78d82aaf/src/scf_module.F90#L645-L648

There are a lot of evaluations happening afterwards, so this might not be the best place to produce the error.  `env%warning` -> `env%error` might not give the desired outcome here, but this piece could easily be moved to a later point in the SCF.
