### ISSUE TITLE
different GFN2 energies for different xtb versions

### ISSUE THREAD

**Issue by ucb-mgcf** [grimme-lab/xtb#452]
**Describe the bug**
I'm getting different GFN2 energies for the same structure in xtb versions 6.2, 6.3.1, 6.4.0.  I'm using the precompiled binaries in all cases.  Here are the version specifics:
6.2:     Version 6.2 (SAW190828)                  |     
6.3.1:   * xtb version 6.3.1 (2faf18d) compiled by 'ehlert@majestix' on 2020-06-10
6.4.0:   * xtb version 6.4.0 (d4b70c2) compiled by 'ehlert@majestix' on 2021-02-01

So far, I've only observed this for transition-metal complexes.

**To Reproduce**
Steps to reproduce the behaviour:

1.  command used: xtb AFISEO.xyz --gfnN --pop > output, where N = 0,1, or 2
[AFISEO.txt](https://github.com/grimme-lab/xtb/files/6093783/AFISEO.txt)
I changed the xyz extension to txt to be able to upload the file

2. GFN2 energies are:
6.2/output:          | TOTAL ENERGY              -41.460233858085 Eh   |
6.3.1/output:          | TOTAL ENERGY              -41.447546196287 Eh   |
6.4.0/output:          | TOTAL ENERGY              -41.458259003342 Eh   |

The GFN0 and GFN1 discrepancies are much smaller:

GFN0:
6.2/output:          | TOTAL ENERGY              -38.503967569597 Eh   |
6.3.1/output:          | TOTAL ENERGY              -38.503575322124 Eh   |
6.4.0/output:          | TOTAL ENERGY              -38.503575322124 Eh   |

GFN1:
6.2/output:          | TOTAL ENERGY              -42.689257797584 Eh   |
6.3.1/output:          | TOTAL ENERGY              -42.689262015495 Eh   |
6.4.0/output:          | TOTAL ENERGY              -42.689262015495 Eh   |

**Expected behaviour**
Assuming the GFN2 parameterization for e.g. Nb hasn't changed across versions, one generally would expect the energies to be the same across versions.  But could this discrepancy be a result of differing accuracy settings (e.g. SCF convergence, integral accuracy, etc.)?  I printed all xtb keywords/options, and I don't see any option for increasing these criteria.  I tried doing --opt extreme, because of the following indication in the documentation: "The accuracy is handed to the singlepoint calculations for integral cutoffs and self consistent field convergence criteria", but I observed no change in the first-structure energy.

Could it alternatively be that I'm getting different converged SCF solutions?  That is, different solutions to the SCF equations, which is a fairly common result in full DFT calculations. The charges file shows only minor differences across versions, so if they are legitimately different solutions, they are still quite similar.

**Additional context**

**Comment by awvwgk** [comment]
We all make errors and I'm very sorry for the inconvenience and confusion they might have caused. All bugs and corresponding fixes which are relevant for the changes in total energies documented in the release notes as accurate as possible.

For example the 6.3.1 discrepancy for GFN2-xTB has been resolved with https://github.com/grimme-lab/xtb/pull/283 in version 6.3.2 and higher. The 6.2 to 6.3 transition is a while back (almost two years now), I wouldn't recommend to use any 6.2 version anymore.

**Comment by ucb-mgcf** [comment]
Thanks for the reply.  I'll start being more regular in checking for new releases and release notes.

Is it correct then that this 6.3.1 bug only affects structures with certain transition-metal (TM) atoms, namely those with a free-atom configuration with s1 (as opposed to s2) in the outer shell?  I ask because I work at a computational facility (MGCF) with several xtb/crest users, some of whom study TM complexes while others only study organic molecules, and I want to determine which people I should notify.

By the way, xtb/crest usage at MGCF has overall been a nice success.  I've written several tutorials for it, and more people there are beginning to use the software every month.  Thanks for providing this very useful software.

**Comment by awvwgk** [comment]
The 6.3.1 bug affects only TM calculations, main group chemistry should be fine.

**Comment by awvwgk** [comment]
I'll close this issue as “resolved.” If this is not the case, please feel free to reopen.
