### ISSUE TITLE
GFNFF geometry optimization

### ISSUE THREAD

**Issue by gnarw** [grimme-lab/xtb#453]
**Describe the bug**
Using geometry optimization on a 14-mer double stranded DNA using gfnff I don't get the
same structure for repeated calculations. I ran the same calculation 10 times and for 4 structure out of 10 the
root mean square deviation between structures was about 1.5 - 1.7 angstroms. The other 6 structures were practically identical.
xtb version 6.3.3 (5b13467)

**To Reproduce**
xtb --gfnff inputStructure.pdb --gbsa water --opt extreme

**Expected behaviour**
I expect that all 10 geometry optimized structures would be identical
I'm I wrong to expect this ?

**Comment by awvwgk** [comment]
@sespic do you have an idea what might be causing this issue?

**Comment by sespic** [comment]
This behavior is expected as geometry optimizations are not completely deterministic, especially for large systems with many degrees of freedom. I would also strongly discourage using extreme thresholds. For proteins in general loose optimization thresholds are recommended in combination with GBSA/ALPB.

**Comment by gnarw** [comment]
Thanks for the answer. Good to have this behaviour confirmed.
