### ISSUE TITLE
Install into a docker container

### ISSUE THREAD

**Issue by erbas** [grimme-lab/xtb#454]
Hi,

We use xtb in various places and as part of the continuous integration tests we build a docker container and run everything in there. I cannot figure out from the instructions on the website how to use the pre-compiled tar ball. There is no information about what goes where or what environment variables need to be set. It's also not clear how the xtb-python I install from Conda finds the installed xtb. 

Many thanks,
Keiran

**Comment by awvwgk** [comment]
Here is an example how `crest` is using `xtb` in its CI:
https://github.com/grimme-lab/crest/blob/86a7a3b523b1fa019fe60152a8e444e4db043a79/.github/workflows/build.yml#L70-L81

For usage of the Python API with conda, have a look at [QCEngine's `xtb` testing environment](https://github.com/MolSSI/QCEngine/blob/master/devtools/conda-envs/xtb.yaml) or this [`xtb` production environment](https://github.com/openforcefield/qca-dataset-submission/blob/master/devtools/prod-envs/qcarchive-worker-openff-xtb.yaml).

Also have you checked the setup documentation [here](https://xtb-docs.readthedocs.io/en/latest/setup.html)? Note that the Python API of `xtb` on conda-forge is only compatible with the `xtb` version available on conda-forge and will automatically install the latter if requested.

**Comment by awvwgk** [comment]
Is this still an issue?

**Comment by erbas** [comment]
Thank you for following up! I had not understood from the documentation that xtb-python also installed xterm. Once I cut it back to just that, everything worked.
