### ISSUE TITLE
Forces per particle

### ISSUE THREAD

**Issue by Dnasiul** [grimme-lab/xtb#46]
Thanks for open-sourcing this project. Is it possible to get the components of the forces on each particle as additional columns on the xyz(log) files? and/or potential energy per particle? I have browsed the docs, but I didn't see the option.

**Comment by awvwgk** [comment]
Right now the easiest way is to request a Turbomole `gradient` file using the `--grad` option, otherwise the forces are right now not available except for the gradient norm.

**Comment by Dnasiul** [comment]
Thanks!

**Comment by awvwgk** [comment]
I will close this issue than.
