### ISSUE TITLE
Units of force constant

### ISSUE THREAD

**Issue by AlessandroPonti** [grimme-lab/xtb#466]
Hello,
I would like to know the units of the force constant given as input in the $constrain section.
Is that hartree/bohr^2 or hartree/angstrom^2 or... ?
I could not figure that out by looking at constrain.f90

The reason I want to know is that I would like to explore the possibility of using the force constant in $constrain to mimick the thermal motion of a crystal slab using the experimental Debye-Waller parameters.

Thank you.
Best,
Alessandro

**Comment by awvwgk** [comment]
It's in atomic units, so hartree/bohr² is the correct unit.

**Comment by AlessandroPonti** [comment]
Thanks a lot!
Alessandro

**Comment by xinglong-zhang** [comment]
Hi, just want to follow up with a similar question on the units: when running `gradient` job, are the units of the gradient components in the output file "gradient" Hartree/Å instead of the atomic unit of Hartree/Bohr? Thanks!
