### ISSUE TITLE
Compilation fails on IBM Power AC922 cluster with Volta V100

### ISSUE THREAD

**Issue by AlessandroPonti** [grimme-lab/xtb#471]
**Describe the bug**
Dear All,
I've tried to compile xTB on a large HPC cluster but compilation using meson and ninja failed. Here follows the description of HW, SW, what I did and achieved.
I would be extremely grateful for any help
Best,
Alessandro

HW: IBM Power AC922 (Whiterspoon) cluster with 2x16 cores IBM POWER9 AC922 at 2.6(3.1) GHz and 4 x NVIDIA Volta V100 GPUs/node, Nvlink 2.0, 16GB 

SW:
uname -a: Linux login02 4.18.0-147.13.2.el8_1.ppc64le #1 SMP Wed May 13 15:23:36 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux
python 3.8.2
meson The Meson build system Version: 0.57.1
ninja --version: 1.10.0.git.kitware.jobserver-1
pgf90 (aka nvfortran) 21.3-0 linuxpower target on Linuxpower
pgcc (aka nvc) 21.3-0 linuxpower target on Linuxpower
CIDA 11.0

**To Reproduce**
Steps to reproduce the behaviour:
$ module load python
$ module load hpc-sdk
$ meson setup build_nv_ninja_xtb --prefix=$HOME/.local -Dla_backend=netlib -Dgpu=true -Dcusolver=true -Dgpu_arch=70
$ ninja -C build_nv_ninja_xtb

Output of ninja command
-----------------------------
ninja: Entering directory `build_nv_ninja_xtb'
[1/330] Module scanner.
ninja: build stopped: dyndep file 'xtb.p/depscan.dd' mentions output 'xtb.p/src_prog_main.F90.o' whose build statement does not have a dyndep binding for the file.

Output of meson command
-----------------------------
The Meson build system
Version: 0.57.1
Source dir: /m100_work/try21_Soave/xtb/my/xtb-6.4.0
Build dir: /m100_work/try21_Soave/xtb/my/xtb-6.4.0/build_nv_ninja_xtb
Build type: native build
Project name: xtb
Project version: 6.4.0
Fortran compiler for the host machine: pgf90 (pgi 20.11-0)
Fortran linker for the host machine: pgf90 pgi 20.11-0
C compiler for the host machine: pgcc (pgi 20.11-0)
C linker for the host machine: pgcc pgi 20.11-0
Host machine cpu family: ppc64
Host machine cpu: ppc64le
Program git found: YES (/usr/bin/git)
Program date found: YES (/usr/bin/date)
Program whoami found: YES (/usr/bin/whoami)
Program hostname found: YES (/usr/bin/hostname)
Configuring xtb_version.fh using configuration
Found pkg-config: /usr/bin/pkg-config (1.4.2)
Found CMake: /cineca/prod/opt/tools/cmake/3.20.0/none/bin/cmake (3.20.0)
Run-time dependency blas found: NO (tried pkgconfig and cmake)
Library blas found: YES
Run-time dependency lapack found: NO (tried pkgconfig and cmake)
Library lapack found: YES
Run-time dependency OpenMP found: YES 3.1
Run-time dependency threads found: YES
meson.build:117: WARNING: Shared library extension cannot be compiled with PGI
Program asciidoctor found: NO
Configuring config_env.bash using configuration
Configuring config_env.csh using configuration
Configuring xtb.pc using configuration
Configuring xtb.tcl using configuration
TESTSUITE/meson.build:53: DEPRECATION: ":" is not allowed in test name "Argparser: print version", it has been replaced with "_"
TESTSUITE/meson.build:54: DEPRECATION: ":" is not allowed in test name "Argparser: print help", it has been replaced with "_"
TESTSUITE/meson.build:55: DEPRECATION: ":" is not allowed in test name "Argparser: print license", it has been replaced with "_"
TESTSUITE/meson.build:56: DEPRECATION: ":" is not allowed in test name "Argparser: no arguments", it has been replaced with "_"
TESTSUITE/meson.build:78: DEPRECATION: ":" is not allowed in test name "Molecule: axis", it has been replaced with "_"
TESTSUITE/meson.build:79: DEPRECATION: ":" is not allowed in test name "Molecule: MIC", it has been replaced with "_"
TESTSUITE/meson.build:80: DEPRECATION: ":" is not allowed in test name "Lattice points: PBC-3D", it has been replaced with "_"
TESTSUITE/meson.build:107: DEPRECATION: ":" is not allowed in test name "PBC tools: convert", it has been replaced with "_"
TESTSUITE/meson.build:108: DEPRECATION: ":" is not allowed in test name "PBC tools: cutoff", it has been replaced with "_"
TESTSUITE/meson.build:110: DEPRECATION: ":" is not allowed in test name "Symmetry: Water", it has been replaced with "_"
TESTSUITE/meson.build:111: DEPRECATION: ":" is not allowed in test name "Symmetry: Li8", it has been replaced with "_"
TESTSUITE/meson.build:112: DEPRECATION: ":" is not allowed in test name "Symmetry: PCl3", it has been replaced with "_"
TESTSUITE/meson.build:113: DEPRECATION: ":" is not allowed in test name "Symmetry: large", it has been replaced with "_"
TESTSUITE/meson.build:115: DEPRECATION: ":" is not allowed in test name "Thermo: axis", it has been replaced with "_"
TESTSUITE/meson.build:116: DEPRECATION: ":" is not allowed in test name "Thermo: calculation", it has been replaced with "_"
TESTSUITE/meson.build:117: DEPRECATION: ":" is not allowed in test name "Thermo: print", it has been replaced with "_"
TESTSUITE/meson.build:119: DEPRECATION: ":" is not allowed in test name "Repulsion: 0D", it has been replaced with "_"
TESTSUITE/meson.build:120: DEPRECATION: ":" is not allowed in test name "Repulsion: 3D", it has been replaced with "_"
TESTSUITE/meson.build:122: DEPRECATION: ":" is not allowed in test name "Coulomb: point (0D)", it has been replaced with "_"
TESTSUITE/meson.build:123: DEPRECATION: ":" is not allowed in test name "Coulomb: point (3D)", it has been replaced with "_"
TESTSUITE/meson.build:124: DEPRECATION: ":" is not allowed in test name "Coulomb: GFN1 (0D)", it has been replaced with "_"
TESTSUITE/meson.build:125: DEPRECATION: ":" is not allowed in test name "Coulomb: GFN1 (3D)", it has been replaced with "_"
TESTSUITE/meson.build:126: DEPRECATION: ":" is not allowed in test name "Coulomb: GFN2 (0D)", it has been replaced with "_"
TESTSUITE/meson.build:127: DEPRECATION: ":" is not allowed in test name "Coulomb: GFN2 (3D)", it has been replaced with "_"
TESTSUITE/meson.build:128: DEPRECATION: ":" is not allowed in test name "Coulomb: Gauss. (0D)", it has been replaced with "_"
TESTSUITE/meson.build:129: DEPRECATION: ":" is not allowed in test name "Coulomb: Gauss. (3D)", it has been replaced with "_"
TESTSUITE/meson.build:131: DEPRECATION: ":" is not allowed in test name "EEQ model: water", it has been replaced with "_"
TESTSUITE/meson.build:132: DEPRECATION: ":" is not allowed in test name "EEQ model: 3D Ewald", it has been replaced with "_"
TESTSUITE/meson.build:133: DEPRECATION: ":" is not allowed in test name "EEQ model: GBSA", it has been replaced with "_"
TESTSUITE/meson.build:134: DEPRECATION: ":" is not allowed in test name "EEQ model: GBSA (salt)", it has been replaced with "_"
TESTSUITE/meson.build:135: DEPRECATION: ":" is not allowed in test name "EEQ model: GBSA (H-bond)", it has been replaced with "_"
TESTSUITE/meson.build:137: DEPRECATION: ":" is not allowed in test name "CN: latticepoints", it has been replaced with "_"
TESTSUITE/meson.build:138: DEPRECATION: ":" is not allowed in test name "CN: neighbourlist", it has been replaced with "_"
TESTSUITE/meson.build:139: DEPRECATION: ":" is not allowed in test name "DFT-D3: latticepoints", it has been replaced with "_"
TESTSUITE/meson.build:140: DEPRECATION: ":" is not allowed in test name "DFT-D3: neighbourlist", it has been replaced with "_"
TESTSUITE/meson.build:141: DEPRECATION: ":" is not allowed in test name "DFT-D3: threebody (LP)", it has been replaced with "_"
TESTSUITE/meson.build:142: DEPRECATION: ":" is not allowed in test name "DFT-D3: threebody (NL)", it has been replaced with "_"
TESTSUITE/meson.build:143: DEPRECATION: ":" is not allowed in test name "DFT-D4: latticepoints", it has been replaced with "_"
TESTSUITE/meson.build:144: DEPRECATION: ":" is not allowed in test name "DFT-D4: neighbourlist", it has been replaced with "_"
TESTSUITE/meson.build:145: DEPRECATION: ":" is not allowed in test name "DFT-D4: threebody (LP)", it has been replaced with "_"
TESTSUITE/meson.build:146: DEPRECATION: ":" is not allowed in test name "DFT-D4: threebody (NL)", it has been replaced with "_"
TESTSUITE/meson.build:148: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: Basic", it has been replaced with "_"
TESTSUITE/meson.build:149: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: Solvation", it has been replaced with "_"
TESTSUITE/meson.build:150: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: SCC", it has been replaced with "_"
TESTSUITE/meson.build:151: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: API", it has been replaced with "_"
TESTSUITE/meson.build:152: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: API (GBSA)", it has been replaced with "_"
TESTSUITE/meson.build:153: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: API (GBSA+salt)", it has been replaced with "_"
TESTSUITE/meson.build:154: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: d-Metal", it has been replaced with "_"
TESTSUITE/meson.build:155: DEPRECATION: ":" is not allowed in test name "GFN2-xTB: Freq", it has been replaced with "_"
TESTSUITE/meson.build:169: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: Basic", it has been replaced with "_"
TESTSUITE/meson.build:170: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: Solvation", it has been replaced with "_"
TESTSUITE/meson.build:171: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: SCC", it has been replaced with "_"
TESTSUITE/meson.build:172: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: API", it has been replaced with "_"
TESTSUITE/meson.build:173: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: XB", it has been replaced with "_"
TESTSUITE/meson.build:174: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: PBC", it has been replaced with "_"
TESTSUITE/meson.build:175: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: API (GBSA)", it has been replaced with "_"
TESTSUITE/meson.build:176: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: API (PCEM)", it has been replaced with "_"
TESTSUITE/meson.build:177: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: IPEA", it has been replaced with "_"
TESTSUITE/meson.build:178: DEPRECATION: ":" is not allowed in test name "GFN1-xTB: Freq", it has been replaced with "_"
TESTSUITE/meson.build:180: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: Basic", it has been replaced with "_"
TESTSUITE/meson.build:181: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: Solvation", it has been replaced with "_"
TESTSUITE/meson.build:182: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: SP", it has been replaced with "_"
TESTSUITE/meson.build:183: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: API", it has been replaced with "_"
TESTSUITE/meson.build:184: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: SRB", it has been replaced with "_"
TESTSUITE/meson.build:185: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: SP  (PBC)", it has been replaced with "_"
TESTSUITE/meson.build:186: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: API (PBC)", it has been replaced with "_"
TESTSUITE/meson.build:187: DEPRECATION: ":" is not allowed in test name "GFN0-xTB: SRB (PBC)", it has been replaced with "_"
TESTSUITE/meson.build:189: DEPRECATION: ":" is not allowed in test name "GFN-FF: Basic", it has been replaced with "_"
TESTSUITE/meson.build:190: DEPRECATION: ":" is not allowed in test name "GFN-FF: Solvation", it has been replaced with "_"
TESTSUITE/meson.build:191: DEPRECATION: ":" is not allowed in test name "GFN-FF: SP", it has been replaced with "_"
TESTSUITE/meson.build:192: DEPRECATION: ":" is not allowed in test name "GFN-FF: HB", it has been replaced with "_"
TESTSUITE/meson.build:193: DEPRECATION: ":" is not allowed in test name "GFN-FF: GBSA", it has been replaced with "_"
TESTSUITE/meson.build:194: DEPRECATION: ":" is not allowed in test name "GFN-FF: Scale-up", it has been replaced with "_"
TESTSUITE/meson.build:195: DEPRECATION: ":" is not allowed in test name "GFN-FF: PDB", it has been replaced with "_"
TESTSUITE/meson.build:196: DEPRECATION: ":" is not allowed in test name "GFN-FF: SDF", it has been replaced with "_"
Build targets in project: 3

Found ninja-1.10.0.git.kitware.jobserver-1 at /m100/home/userexternal/rsoave00/.local/bin/ninja

**Comment by awvwgk** [comment]
Duplicate of #442

**Comment by awvwgk** [comment]
This issue is related to a recent regression in meson 0.57.0 and 0.57.1 which has been fixed in 0.57.2

**Comment by awvwgk** [comment]
Could this issue be resolved by updating meson?

**Comment by AlessandroPonti** [comment]
Yes, thanks. Meson issue is solved. I found subsequent compilation errors but I'll come back for help on these.
Best,
Alessandro
