### ISSUE TITLE
Gradients for each optimization or MD step? 

### ISSUE THREAD

**Issue by TinacciL** [grimme-lab/xtb#484]
Hi! 

I do not found any way to see the gradients for each atom in each optimization step or in a MD step (using GFN2) also using ```--grad``` and ```--verbose``` keyword with xtb 6.4.0 version and the input file is a ```.xyz```. Is it possible? Because I can see this info only in the last structure.

Thanks for the great work you done.

**Comment by awvwgk** [comment]
This tends to be a lot of information that has to be dumbed via file output while running the optimization or dynamic, at least if printed in ascii formats, resulting in large files and IO overhead. Except for the Turbomole gradient format I'm not aware of a format that nicely supports storing gradients for a trajectory while also being concise.

It certainly can be done, but shouldn't be the default. If you need access to the values for analysis it might be easier to retrieve the gradient while driving the `xtb` program via the API (which currently means you cannot use the optimizer in `xtb`).

**Comment by TinacciL** [comment]
Of course I understand the point, and I was thinking to use ASE coupled with xtb-python to do that but before start I was only wondering if is it possible or not with some keyword: and you have already answer me. So I can rapidly close this request. 

Anyway a keyword in order to print the gradient file in ASCII for each MD step (not for the optimization) like in cp2k could be usefull in some situation/system. 

Really thanks and thanks for the great work you done.
