### ISSUE TITLE
Passing in a custom grid for ESP calculations

### ISSUE THREAD

**Issue by ayushsgupta** [grimme-lab/xtb#486]
**Describe the bug**
The [xcontrol documentation](https://github.com/grimme-lab/xtb/blob/master/man/xcontrol.7.adoc#write) lists the ability to pass in a custom grid (as opposed to the default VdW surface) when calculating ESP, using the "grid file" keyword in the $write section of the input file. However, when I try to pass in a custom grid, I get the following error message (I'm running version 6.3.3 on Windows):

########################################################################
[WARNING] Please study the warnings concerning your input carefully
-1- set_write: the key 'grid file' is not recognized by write
########################################################################

Is this feature deprecated, or is there a problem with the way I'm specifying my input (see below)?

**To reproduce**
1. Relevant files here: [esp_grid.zip](https://github.com/grimme-lab/xtb/files/6543155/esp_grid.zip)
2. Inside the folder, run: `xtb --input xtb.inp H2O.xyz --verbose`
3. My output looks like this: [out.txt](https://github.com/grimme-lab/xtb/files/6543163/out.txt)

**Expected behavior**
Instead of calculating ESP on the VdW surface, expected it to calculate only at specified points (in this case `(0.0, 0.0, 0.0)` just for testing purposes).

**Comment by awvwgk** [comment]
The actual and documented keyword mismatch here:
https://github.com/grimme-lab/xtb/blob/0245411f5b8595c8ac7655d72c105c055e1da837/src/set_module.f90#L1181

**Comment by ayushsgupta** [comment]
Ok great, thanks for the help - it no longer shows the same warning. Does the grid file need to have a particular file type or have the points be listed in a certain format?

**Comment by ayushsgupta** [comment]
Leaving this here for future reference: I was able to make it work by including the line `gridfile = esp_coord.xyz` in the $write section of the input file, and then inside `esp_coord.xyz` having three comma-separated values on each line representing the coordinates of each point (1 point / 3 values per line).
