### ISSUE TITLE
xtb 6.4.1 fails tests on aarch64 due to memory access violation

### ISSUE THREAD

**Issue by susilehtola** [grimme-lab/xtb#490]
Updating the Fedora package of xtb to 6.4.1, the tests fail on the aarch64 platform; full logs attached

[root.log](https://github.com/grimme-lab/xtb/files/6638821/root.log)
[build.log](https://github.com/grimme-lab/xtb/files/6638822/build.log)

There's one test that crashes due to a memory access violation
 82/101 GFN1-xTB API (PCEM)      FAIL           38.96s (killed by signal 11 SIGSEGV)
whereas several others fail due to NaNs; these might also be caused by memory access violation(s).

**Comment by awvwgk** [comment]
Thanks for the report. I did successfully build, test and package an aarch64 version on conda-forge for 6.4.1. Do you mind trying if this version works on your aarch64 machine?

**Comment by susilehtola** [comment]
The error occurs on the Fedora build farm, which is isolated from the Internet.

I do have a Raspberry Pi 4 at work which is running Fedora 34; I'll try to recompile xtb from scratch there and see if I can reproduce the errors in the tests.

**Comment by susilehtola** [comment]
Ok so oddly enough there are no problems on my Raspberry Pi 4… the package builds and the tests run cleanly. Odd

**Comment by awvwgk** [comment]
Thanks for checking, we will keep this issue open until we get to the ground of this.

**Comment by susilehtola** [comment]
Well, I'm guessing it was a hardware error on the build node; I just ran a new build and it completed successfully.
