### ISSUE TITLE
xtb-gaussian instructions

### ISSUE THREAD

**Issue by pwging13** [grimme-lab/xtb#495]
Where does one place the xtb-gaussian script?  With the xtb or gaussian executables? or just somewhere in the path?

Then is calling it as simple as including external='xtb-gaussian' as a keyword?

**Comment by kjelljorner** [comment]
As explained in the [installation instructions](https://github.com/aspuru-guzik-group/xtb-gaussian), you just need to have xtb and xtb-gaussian in your path. Of course setting the usual environment variables for xtb execution is also recommended. See the notes for xtb-gaussian on how to balance the number of processors for Gaussian and xtb. I think the instructions on the GitHub are sufficiently clear, but maybe @clavigne can comment further.

**Comment by pwging13** [comment]
I was looking at the readthedocs page for instructions, but I agree, the installation instructions you posted there are sufficiently clear.

**Comment by clavigne** [comment]
@pwging13 please let me know if you encounter any difficulty by opening an issue on the repo https://github.com/aspuru-guzik-group/xtb-gaussian . @awvwgk I think you can close this issue, thanks.
