### ISSUE TITLE
installing the program

### ISSUE THREAD

**Issue by rmonegato** [grimme-lab/xtb#510]
i followed the instructions in order to get the program at the link https://xtb-docs.readthedocs.io/en/latest/setup.html#getting-the-program, downloading the 6.4.1 version and using ubuntu 18.04 LTS on windows 10 but still doesn't work; when i write the command ">xtb --version" to print the banner, it print "--version command not found" and i can't understand why.
R.Monegato

**Comment by awvwgk** [comment]
You included the prompt when copying from the docs. Always remove the prompt when copying commands from the docs:
<a href="https://asciinema.org/a/jBph4iaWHki7grdzkmJHH8cjj" target="_blank"><img src="https://asciinema.org/a/jBph4iaWHki7grdzkmJHH8cjj.svg" /></a>

**Comment by rmonegato** [comment]
many thanks for your support, may i ask you why after typing the command, it print "command xtb not found"? i know that my questions may appear trivial but i just started studying xtb for my thesis.

**Comment by awvwgk** [comment]
`> xtb` was interpreted as a redirect for the shell rather than an actual command, you should find an empty file named `xtb` now in the current directory.
