### ISSUE TITLE
About the Deprecation of simulated annealing

### ISSUE THREAD

**Issue by xiki-tempula** [grimme-lab/xtb#516]
**Is your feature request related to a problem? Please describe.**
I'm interested in using xtb to run simulated annealing to generate the conformers that will be used for molecule mechanics force field fitting. Thus, I would need not only the energy minimised structure but also the relatively high energy state (e.g. angle not in the equilibrium angle and dihedral in relatively high energy state) such that the barrier height could be fitted.

**Describe the solution you'd like**
It would be nice if the simulated annealing could be brought back

**Describe alternatives you've considered**
I think this is not something that the current CREST workflow could produce (obviously I could be wrong), which only gives the energy minimum state.

**If possible state how you can assist in providing data or code to to implement the feature**
I could help testing it.

**Comment by awvwgk** [comment]
Isn't this possible with Crest as well? You would have to increase the energy window for keeping conformers, though.

**Comment by xiki-tempula** [comment]
Sorry, I might not have expressed my point clearly. Take water for example, the H-O-H angle is 104.5. To parameterise the force constant of this angle, I would need a conformer with H-O-H angle of 104 or 105.
I'm sorry that I might not have read the iMTD-GC workflow paper very carefully but I think at the end of metaD, another round of energy minimization would be run. Say if the metaD yield an angle of 104, the energy minimisation would change this angle to 104.5.

**Comment by awvwgk** [comment]
> Take water for example, the H-O-H angle is 104.5. To parameterise the force constant of this angle, I would need a conformer with H-O-H angle of 104 or 105.

But this isn't something a simulated annealing could do, is it? The resulting structures from the dynamics would be optimized in the end as well.

If you only want distorted structures you can run the meta-dynamics directly from xtb without using CREST.

**Comment by xiki-tempula** [comment]
I see. Thank you. I thought simulated annealing means that the temperature of the moleucle would gradually raise from 300K to 500K and then gradually cooled to 300K, where a snapshot is taken. The molecule is then heated to 500K and cooled to 300K for another snapshot. Then all the snapshots would be given as output.
Thanks for the suggestion, I will have a check of the metaD to see if it gives good reults.

**Comment by awvwgk** [comment]
If you need this kind of temperature ramps, have a look into using the xTB Hamiltonian in DFTB+. The dynamics module is quite sophisticated regarding temperature profiles and can be combined with plumed for metadynamics.

**Comment by xiki-tempula** [comment]
Thanks for the advice. The https://dftbplus-recipes.readthedocs.io/en/latest/moleculardynamics/annealing.html in DFTB+ is what I have in mind. I never know that DFTB+ support xTB.

**Comment by awvwgk** [comment]
> I never know that DFTB+ support xTB.

It's in fact a quite recent addition.

**Comment by xiki-tempula** [comment]
@awvwgk Thank you very much for help. I wonder if do you have any recommended template input file that could show how to use the xTB Hamiltonian?
DFTB+ recipes doesn't have a recipe for xTB
Though DFTB+ reference manual did mention xTB but didn't give any example and didn't discussed the problem.

Another question is I wonder if DFTB+ can use alpb as well or it is only gbsa?
Thank you so much for the help.

**Comment by awvwgk** [comment]
I implemented xTB a few months ago in DFTB+, therefore it is not yet released, but will be part of 21.2. The solvation models are already in 21.1. Working with bleeding edge software is always a bit tricky.
