### ISSUE TITLE
Missing break at Wiberg/Mayer bonding order

### ISSUE THREAD

**Issue by PatrickHHU** [grimme-lab/xtb#542]
Dear XTB-Team,

we're using XTB mainly for gradient calculation and binding analysis. After the calculation we parse the log file to get the needed information for our use. Therefore I found a minor bug, which let's struggle us by parsing. If there is an atom without binding (e.g. cation), the line break is missing and therefore our parsing is failing. So could you please add the missing line break?

I attached a very small simple example of only three Li-atoms without any meaning, but with showing clear the bug.

Running the calculation: xib --chrg -3 -uhf 3 geom.xyz

Showing the bug:
```
Wiberg/Mayer (AO) data.
largest (>0.10) Wiberg bond orders for each atom

 ---------------------------------------------------------------------------
     #   Z sym  total        # sym  WBO       # sym  WBO       # sym  WBO
 ---------------------------------------------------------------------------
     1   3 Li   0.000 --     2   3 Li   1.187 --     3 Li   1.187
     3   3 Li   1.187 --     2 Li   1.187
 ---------------------------------------------------------------------------
```
So the second Li atom starts not in a new line. 

Normally we use version 6.3.3, but I could reproduce the error also with the latest version.

[geom.xyz.txt](https://github.com/grimme-lab/xtb/files/7685273/geom.xyz.txt)
[out.txt](https://github.com/grimme-lab/xtb/files/7685275/out.txt)

Regards,
Patrick

**Comment by awvwgk** [comment]
Maybe related to https://github.com/grimme-lab/xtb/issues/397

**Comment by awvwgk** [comment]
The printout is generated here:

https://github.com/grimme-lab/xtb/blob/79825abcba525fcdf90b791dcacef51065a7a4e7/src/main/property.F90#L605-L616

line 615 which should generate the line break is not reached if there are no bonds to print.

Adding another case to handle zero neighbours can fix the problem:

```f90
if (ibmax == 0) write(iunit, '(a)')
```
