### ISSUE TITLE
Optimization terminates in error but only for certain molecules

### ISSUE THREAD

**Issue by jjkowalewski** [grimme-lab/xtb#566]
I have successfully run gfnff  optimization on about 900 molecules. However, there are around 50 that generate an error. 
I have provided a few sdf files here. 

**Here is the version info:**
xtb version 6.4.1 (23d549d) compiled by 'conda@3c73975816cd' on 2022-01-07

**Here  is a sample call:**
xtb Compound_11.sdf --namespace Compound_11 --opt --gfnff --alpb water

**Here are sample files:**
[Compound_1017.txt](https://github.com/grimme-lab/xtb/files/7967560/Compound_1017.txt)
[Compound_11.sdf.txt](https://github.com/grimme-lab/xtb/files/7967561/Compound_11.sdf.txt)
[Compound_1016.txt](https://github.com/grimme-lab/xtb/files/7967562/Compound_1016.txt)

**Here is the error:**
It follows right after the force field initialization 

 ** On entry to DSYTRF parameter number  7 had an illegal value
########################################################################
[ERROR] Program stopped due to fatal error
-7- Could not setup parameterisation
-6- main_setup_newCalculator: Could not construct new calculator
-5- main_setup_newGFFCalculator: Could not create force field calculator
-4- gfnff_setup: Failed to generate topology
-3- gfnff_ini: Failed to generate charges
-2- gfnff_ini2_goedeckera: Solving linear equations failed
-1- mctc_lapack_sytrf: Factorisation of matrix failed
########################################################################
abnormal termination of xtb
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
ERROR STOP

**Comment by awvwgk** [comment]
`xtb` does not support V3000 connection tables in SDF or molfiles, you have to use the V2000 format instead.

**Comment by jjkowalewski** [comment]
Thanks, I converted the files and was able to run through the batch successfully.
