### ISSUE TITLE
Fix dihedral during opt won't work

### ISSUE THREAD

**Issue by xiki-tempula** [grimme-lab/xtb#596]
**Describe the bug**
I want to do a geometry optimisation with the dihedral fixed to a certain value

**To Reproduce**
I have the input coordinate file
```
>>> cat input.xyz
4

H          -0.9009500    -0.5085100    -0.7673400
O          -0.7280500     0.0249600     0.0239800
O           0.7276200     0.0331600    -0.0269600
H           0.9078200    -0.4139400     0.8146500
```
And the input file
```
>>> cat input.inp 
$fix
dihedral: 1, 2, 3, 4, -120
$end
```
I run the xtb with `xtb input.xyz --opt --chrg 0 --uhf 0 --gfn 2 --parallel 10 --input input.inp`

**Expected behaviour**
I expect to see
```
 selected dihedral angles (degree)
 ---------------------------------
H4-O3-O2-H1=-120         
```

but I see
```
 selected dihedral angles (degree)
 ---------------------------------
H4-O3-O2-H1=180.31          
```

**Additional context**
xtb 6.4.1

**Comment by awvwgk** [comment]
Try to use `constraint` instead:

```
❯ cat input.xyz
4

H          -0.9009500    -0.5085100    -0.7673400
O          -0.7280500     0.0249600     0.0239800
O           0.7276200     0.0331600    -0.0269600
H           0.9078200    -0.4139400     0.8146500
$constrain
dihedral: 1, 2, 3, 4, -120
$end
❯ xtb --namespace 596 input.xyz --opt | rg selected\ dihedral\ angles -A 2
 selected dihedral angles (degree)
 ---------------------------------
H4-O3-O2-H1=237.11
```

**Comment by awvwgk** [comment]
You cannot hold a dihedral angle constant with `fix`, but you can use add a constraint in `constrain`. It's an issue of the keyword not existing for `fix`, so maybe a documentation issue.

Fixing a dihedral angle requires to project out the gradient which could deform this torsion and we don't implement this transformation in `xtb`.

**Comment by xiki-tempula** [comment]
@awvwgk Thanks.
