### ISSUE TITLE
Which kind of charges is written in "charges" file

### ISSUE THREAD

**Issue by licheng-xu-echo** [grimme-lab/xtb#598]
I'm curious about which kind of charges (Mulliken or another) is written in output file "charges", which has no reference in the document.

**Comment by awvwgk** [comment]
The `charges` file contains the atomic partial charges calculated by Mulliken population analysis. The `charges` directly map to the central quantity in tight-binding, which is the population at the atomic sides.

**Comment by epunzal2** [comment]
Can I use this _charges_ file (e.g. from GFN2) to affect charge distribution in _gfnff_charges_?
