### ISSUE TITLE
I am tryin to do frequency calculations in multinode I ran for 1 node and 10 nodes and I am getting the same times for those 2 calculations, is it possible that the calculation of the hessian is not parallelize?

### ISSUE THREAD

**Issue by lxsep** [grimme-lab/xtb#606]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

1. happens with input (include input files)
2. start `xtb` with (all the options here)
3. run `xtb` with your options and the `--verbose` flag
4. output showing the error

Please provide all input and output file such that we confirm your report.

**Expected behaviour**

**Additional context**

**Comment by awvwgk** [comment]
Please use the issue description for formulating your question and not the issue title.
