### ISSUE TITLE
Printing of xTB Hamiltonian matrix and other matrices

### ISSUE THREAD

**Issue by LucasLang** [grimme-lab/xtb#614]
Dear xtb developers,

I am interested in obtaining the xTB Hamiltonian matrix and other matrices (e.g. overlap) for the purpose of machine learning (see this paper as an example: https://arxiv.org/abs/2105.14655).
Do you think this feature might be interesting for the wider xtb userbase? Otherwise, I will simply implement it in a private fork.

Best wishes,
Lucas

**Comment by awvwgk** [comment]
I implemented a driver for calculating and storing matrices from xTB as `npy` files (see https://github.com/awvwgk/tblite-int). The driver is currently limited to pairs, but I can expand it arbitrary geometries if needed.

**Comment by LucasLang** [comment]
Dear Sebastian,

that sounds interesting. Would it be straightforward to obtain the complete (i.e., all pairs of atoms) core Hamiltonian matrix, full Hamiltonian matrix, overlap matrix, and density matrix for a converged GFN1-xTB or GFN2-xTB calculation?

**Comment by awvwgk** [comment]
Yes, this is easily possible with the [`tblite`](https://github.com/tblite/tblite) library, which provides a complete xTB implementation and will also in the near future replace the `xtb` intern implementation (see #514).

**Comment by LucasLang** [comment]
Great, thank you for the hint!
