### ISSUE TITLE
GFNFF calculation of NCI complexes only works with a charges file (taken from a GFN2-xTB calculation)

### ISSUE THREAD

**Issue by benbaed** [grimme-lab/xtb#624]
Upon trying to perform GFNFF single point calculations of large non-covalently bound complexes (between 500 and 3000 atoms) this error occurred in many cases:

```
[ERROR] Program stopped due to fatal error
-3- Single point calculation terminated
-2- gfnff_calculator_singlepoint: Force-field method terminated
-1- gfnff_eg: EEQ charge constrain error
```

The structures are mostly on GFN2-xTB level and definitely not a problem. After copying a `charges` file of a GFN2-xTB calculation of the same system in the folder, the GFNFF calculation works as intended. 

Before running the calculation I execute the following commands due to the system size

```
export OMP_NUM_THREADS=4,1
ulimit -s unlimited
export OMP_STACKSIZE=5G
```

The structure of one of the systems, where this bug occurs is attached 
[example.zip](https://github.com/grimme-lab/xtb/files/8686902/example.zip)

**Comment by awvwgk** [comment]
Can you try whether this problem is still present in the current development version (`module load xtb/unstable` on *majestix*)?

**Comment by benbaed** [comment]
For my systems, the problem is no longer present in the current development version.

**Comment by awvwgk** [comment]
That was an easy fix than.
