### ISSUE TITLE
Incomplete xtbtopo.mol file.

### ISSUE THREAD

**Issue by Rintontin** [grimme-lab/xtb#628]
Hi

The XTB-6.5.0 software writes an incomplete xtbtopo.mol file. The list of bonds between atoms is missing.

Best regards, Ariel G.

[input-output-files.zip](https://github.com/grimme-lab/xtb/files/8703725/input-output-files.zip)

**Comment by awvwgk** [comment]
Thanks for reporting. We'll have a look why this information is not copied over for writing.

**Comment by awvwgk** [comment]
Looks like I'm copying over the bond information at

https://github.com/grimme-lab/xtb/blob/d3f537047375ad5fa3e33335686ad8a98a7443fc/src/type/molecule.f90#L411-L417

but not set the total number of bonds for the writer.
