### ISSUE TITLE
test-drive dependency not found automatically

### ISSUE THREAD

**Issue by susilehtola** [grimme-lab/xtb#632]
xtb 6.5.0 introduced new dependencies, mctc-lib and test-drive.

I've been able to package mctc-lib (which also required packaging json-fortran) as well as test-drive.

However, the system installation of test-drive is not picked up by meson in the xtb build.

It is common policy in linux distributions that build farms are cut off from the internet for security reasons. test-drive should be detected if it is installed.

**Comment by awvwgk** [comment]
@susilehtola Also, thanks for packaging `xtb` and co for Fedora, we should include this information in the documentation or the README somewhere to make users aware of this option.

**Comment by awvwgk** [comment]
Sorry for that, reusing libraries turned out to be easier than reinventing the wheel ;). And apologies in advance as https://github.com/grimme-lab/xtb/pull/626 is going to land this summer with another dependency.
