### ISSUE TITLE
Charge and spin weights don't seem to work

### ISSUE THREAD

**Issue by small-bamboo** [grimme-lab/xtb#641]
Dear professors:

the  -c and -u Parameters do not seem to work， as the example for water ,when  --chrg 1 --uhf 3,  --chrg 1 --uhf 2 and  --chrg 0 --uhf 1 give the same result

**Comment by awvwgk** [comment]
Cannot confirm this behavior:

```
❯ xtb assets/inputs/xyz/caffeine.xyz --namespace test --chrg 1 --norestart
...
   * xtb version 6.5.0 (746241f) compiled by 'ehlert@majestix' on 2022-05-15
...
           -------------------------------------------------
          | TOTAL ENERGY              -41.662902621520 Eh   |
          | GRADIENT NORM               0.122210536202 Eh/α |
          | HOMO-LUMO GAP               3.504173259156 eV   |
           -------------------------------------------------
...
❯ xtb assets/inputs/xyz/caffeine.xyz --namespace test --chrg 0 --norestart
...
   * xtb version 6.5.0 (746241f) compiled by 'ehlert@majestix' on 2022-05-15
...
           -------------------------------------------------
          | TOTAL ENERGY              -42.147463127790 Eh   |
          | GRADIENT NORM               0.075211842304 Eh/α |
          | HOMO-LUMO GAP               3.362549611897 eV   |
           -------------------------------------------------
...

**Comment by small-bamboo** [comment]
> Cannot confirm this behavior:
> 
> ```
> ❯ xtb assets/inputs/xyz/caffeine.xyz --namespace test --chrg 1 --norestart
> ...
>    * xtb version 6.5.0 (746241f) compiled by 'ehlert@majestix' on 2022-05-15
> ...
>            -------------------------------------------------
>           | TOTAL ENERGY              -41.662902621520 Eh   |
>           | GRADIENT NORM               0.122210536202 Eh/α |
>           | HOMO-LUMO GAP               3.504173259156 eV   |
>            -------------------------------------------------
> ...
> ❯ xtb assets/inputs/xyz/caffeine.xyz --namespace test --chrg 0 --norestart
> ...
>    * xtb version 6.5.0 (746241f) compiled by 'ehlert@majestix' on 2022-05-15
> ...
>            -------------------------------------------------
>           | TOTAL ENERGY              -42.147463127790 Eh   |
>           | GRADIENT NORM               0.075211842304 Eh/α |
>           | HOMO-LUMO GAP               3.362549611897 eV   |
>            -------------------------------------------------
> ...
> ```

the uhf does not make sense
![image](https://user-images.githubusercontent.com/82574986/170837411-fe69be4a-a134-42e0-8234-fca773c6b7e6.png)

**Comment by awvwgk** [comment]
`xtb` will ignore the number of unpaired electrons if the resulting multiplicity is impossible with the available number of electrons.

**Comment by small-bamboo** [comment]
Dear professor ：


But what about the methyl radical system





------------------ Original ------------------
From: Sebastian Ehlert ***@***.***&gt;
Date: Sun,May 29,2022 2:09 AM
To: grimme-lab/xtb ***@***.***&gt;
Cc: small-bamboo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [grimme-lab/xtb] Charge and spin weights don't seem to work(Issue #641)





 
xtb will ignore the number of unpaired electrons if the resulting multiplicity is impossible with the available number of electrons.

**Comment by small-bamboo** [comment]
Like calculate the ground state of oxygen





------------------ Original ------------------
From: Sebastian Ehlert ***@***.***&gt;
Date: Sun,May 29,2022 2:09 AM
To: grimme-lab/xtb ***@***.***&gt;
Cc: small-bamboo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [grimme-lab/xtb] Charge and spin weights don't seem to work(Issue #641)





 
xtb will ignore the number of unpaired electrons if the resulting multiplicity is impossible with the available number of electrons.
