### ISSUE TITLE
xTB fails to install on Windows MingW64

### ISSUE THREAD

**Issue by TyBalduf** [grimme-lab/xtb#646]
**Describe the bug**
I was able to build Windows in a MingW64 environment (mostly, see https://github.com/grimme-lab/xtb/issues/645). The executable in the build directory seems to run just fine. However, when I try to install the program, I get the following:
```
$ ninja -C alt_build install
ninja: Entering directory `alt_build'
[0/1] Installing files.
Installing xtb-6.dll to C:/msys64/usr/bin

ERROR: File 'xtb.lib' could not be found
FAILED: meson-install
"C:/msys64/mingw64/bin/python3.exe" "C:/msys64/home/balduf/meson/meson.py" "install" "--no-rebuild"
ninja: build stopped: subcommand failed.
```
I can't find `xtb.lib` anywhere in the build directory. I'm don't know much about the meson build process, but the issue seems to have something to do with an \IMPLIB for `xtb.lib`  not working.

**To Reproduce**
I tried to follow the [meson build instructions](https://github.com/grimme-lab/xtb/blob/main/meson/README.adoc) as closely as possible to get the directory structure to turn out right.
`meson setup alt_build  --prefix=/usr   --bindir=bin   --libdir=lib   --includedir=include   --datadir=share   --mandir=man --buildtype release --optimization 2`.

This manages to copy `xtb-6.dll` to my /usr/bin/ directory, but then fails.

**Comment by TyBalduf** [comment]
I'm still looking into this, but I think the MSVC cl compiler requires a specific declaration for which functions/variables you want to export to an [import lib](https://docs.microsoft.com/en-us/cpp/build/reference/implib-name-import-library?view=msvc-170) and since these aren't (or don't seem to be) there, it doesn't make xtb.lib.

xTB can still run without this, but the various C API functions are inaccessible. I think it's possible to add a .def file to declare these functions to be exported, but I haven't yet figured out how to make meson read this file.

**Comment by TyBalduf** [comment]
Adding a def seemed to do the trick. I can get the install working and am able to interface with another program. I don't know if this is an actual "bug" or just a weird configuration on my end, but linking with an external program using `-lxtb`, it expects to find `libxtb.lib` rather than `xtb.lib` which is what meson produces once a def file is included. Simply renaming the file in the install location made things work for me.

**Comment by awvwgk** [comment]
It might help to add `dllexport` attributes in the C API for this cases.

- Intel: https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/a-to-z-reference/a-to-b/attributes/attributes-dllexport-and-dllimport.html
- GCC: https://gcc.gnu.org/onlinedocs/gcc-10.3.0/gfortran/ATTRIBUTES-directive.html#ATTRIBUTES-directive
