### ISSUE TITLE
xtb fails to build on Fedora rawhide / incompatibility with newest meson?

### ISSUE THREAD

**Issue by susilehtola** [grimme-lab/xtb#674]
xtb fails to build on Fedora rawhide.
https://koji.fedoraproject.org/koji/taskinfo?taskID=89932660

```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1861, in test_done
    f.result()
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1856, in run_test
    res = await test.run(self)
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1400, in run
    await self._run_cmd(harness, cmd)
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1466, in _run_cmd
    returncode, result, additional_error = await p.wait(self.runobj.timeout)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1290, in wait
    additional_error = await self._kill()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1251, in _kill
    await try_wait_one(p.wait(), timeout=0.5)
  File "/usr/lib/python3.11/site-packages/mesonbuild/mtest.py", line 1153, in try_wait_one
    await asyncio.wait(awaitables,
  File "/usr/lib/python3.11/asyncio/tasks.py", line 424, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
```

**Comment by susilehtola** [comment]
This could be a meson bug tho

**Comment by awvwgk** [comment]
I did built with the last version with meson 0.63.0 and Python 3.10 cleanly. Since you are using Python 3.11 for the build, there might again be a backwards incompatible change.

**Comment by awvwgk** [comment]
Also, please provide some information on the versions you are using for the build for such reports, its hard to guess from just a stack trace what you are trying to do.

**Comment by susilehtola** [comment]
All information is available in the build files.
https://kojipkgs.fedoraproject.org//work/tasks/2800/89932800/root.log

**Comment by awvwgk** [comment]
> All information is available in the build files.

Sure it is, but as somebody unfamiliar with Fedora packaging and build infrastructure it takes some time to find those logs. Depending on how long the logs are retained this issue will become unreproducible once the logs are gone, therefore I would much appreciate if a bug report is self-contained and I don't have to go hunt for the relevant information to reproduce it myself.

**Comment by awvwgk** [comment]
Okay, looks like your tests are timing out on the the 32bit arch. This can happen if you oversubscribe the available CPUs when running the testsuite in parallel and the tests itself multithreaded. The error you are observing is a bug in meson with 0.62.2 with Python 3.11 when awaiting a future due to handling the timeout.

Please set the timeout multiplier in your build script accordingly (``--timeout-multiplier <int>``) or reduce the number of parallel processed (``--num-processes 1``) or limit the number of OpenMP threads (``OMP_NUM_THREADS=2,1``). Checkout the documentation on ``meson test`` for more details.

**Comment by susilehtola** [comment]
Thanks, the problem indeed was just a test timeout induced by too much parallellism. Setting `OMP_NUM_THREADS=1` for the tests that are run in parallel by default solved the issue.
