### ISSUE TITLE
Ion Pair SCC Difficulties

### ISSUE THREAD

**Issue by corinwagen** [grimme-lab/xtb#678]
**Is your feature request related to a problem? Please describe.**
I'm struggling to converge ion pairs at large separation distances — the self-consistent charge iterations just don't work.

For instance, here's a Me4NCl structure which doesn't converge at GFN2-xtb:
````
18
tmacl
 C                 -5.12996550    0.88237190    0.00000000
 H                 -5.48661942    1.89118208    0.00000189
 H                 -5.48663807    0.37797482   -0.87365225
 H                 -5.48663857    0.37797197    0.87365040
 C                 -3.07664979   -0.56957923    0.00000000
 H                 -3.43332200   -1.07397719   -0.87365189
 H                 -2.00664979   -0.56959187    0.00000116
 H                 -3.43332333   -1.07397820    0.87365077
 C                 -3.07662328    1.60830920    1.25740497
 H                 -2.00662509    1.60660213    1.25838332
 H                 -3.43167984    2.61768222    1.25642758
 H                 -3.43489225    1.10504120    2.13105517
 C                 -3.07662328    1.60830920   -1.25740497
 H                 -2.00662329    1.60842572   -1.25732975
 H                 -3.43317414    1.10382386   -2.13105595
 H                 -3.43339975    2.61707605   -1.25748033
 N                 -3.58996550    0.88235293    0.00000000
 Cl                 8.67002652    8.03808016   -5.16543654
```` 

Running this input file with ``xtb --gfn 2 --chrg 0 --uhf 0 --parallel 16 --grad tmacl.xyz`` gives the following issue:

```
(truncated for length)
243    -22.2547461 -0.351557E-01  0.140E+00    4.43       1.0  T
 244    -22.2629857 -0.823957E-02  0.693E-01    1.18       1.0  T
 245    -21.4113545  0.851631E+00  0.460E+00    0.00       1.0  T
 246    -22.2274373 -0.816083E+00  0.259E+00   10.20       1.0  T
 247    -22.2575232 -0.300859E-01  0.121E+00    3.52       1.0  T
 248    -22.2630753 -0.555209E-02  0.680E-01    1.12       1.0  T
 249    -21.6253756  0.637700E+00  0.403E+00    0.00       1.0  T
 250    -22.2369807 -0.611605E+00  0.225E+00    8.63       1.0  T

   *** convergence criteria cannot be satisfied within 250 iterations ***

         #    Occupation            Energy/Eh            Energy/eV
      -------------------------------------------------------------
         1        2.0000           -1.0342747             -28.1440
       ...           ...                  ...                  ...
        14        2.0000           -0.4748731             -12.9220
        15        2.0000           -0.4720209             -12.8443
        16        2.0000           -0.4719705             -12.8430
        17        2.0000           -0.4718956             -12.8409
        18        2.0000           -0.4164228             -11.3314
        19        2.0000           -0.4164228             -11.3314
        20        2.0000           -0.4163692             -11.3300 (HOMO)
        21                         -0.0993177              -2.7026 (LUMO)
        22                         -0.0093068              -0.2533
        23                         -0.0092614              -0.2520
        24                         -0.0092108              -0.2506
        25                          0.0422255               1.1490
       ...                                ...                  ...
        41                          0.2609602               7.1011
      -------------------------------------------------------------
                  HL-Gap            0.3170515 Eh            8.6274 eV
             Fermi-level           -0.2578434 Eh           -7.0163 eV

 SCC (total)                   0 d,  0 h,  0 min,  0.386 sec
 SCC setup                      ...        0 min,  0.001 sec (  0.152%)
 Dispersion                     ...        0 min,  0.000 sec (  0.059%)
 classical contributions        ...        0 min,  0.001 sec (  0.153%)
 integral evaluation            ...        0 min,  0.001 sec (  0.305%)
 iterations                     ...        0 min,  0.382 sec ( 98.872%)
 molecular gradient             ...        0 min,  0.001 sec (  0.332%)
 printout                       ...        0 min,  0.000 sec (  0.095%)

########################################################################
[ERROR] Program stopped due to fatal error
-3- Single point calculation terminated
-2- xtb_calculator_singlepoint: Electronic structure method terminated
-1- scf: Self consistent charge iterator did not converge
########################################################################
```

I can solve this problem by adding ``--etemp 1000``, but trying to use the ``xtbrestart`` file to then rerun the calculation at a lower level of theory ([as suggested](https://xtb-docs.readthedocs.io/en/latest/sp.html#fermi-smearing)) doesn't work.

**Describe the solution you'd like**
I mean, this seems like it should be possible? I don't fully understand the considerations here, but it doesn't seem like this ought to be intrinsically impossible from an electronic-structure vantage point.

**Describe alternatives you've considered**
At this distance, it seems all interactions are mainly Coulombic, so maybe a fragment-based approach is best?

**If possible state how you can assist in providing data or code to to implement the feature**
I don't know Fortran, unfortunately, but happy to provide whatever data needed.

**Additional context**
(I run into this problem using *xtb* as part of a MD package)

**Comment by haneug** [comment]
From an electronic structure viewpoint, this is not a surprise at all. You can archive convergence when you turn on solvation.

**Comment by corinwagen** [comment]
Well, using Gaussian 16 I can easily run a Hartree-Fock calculation on this structure (it only takes 9 SCF cycles to achieve convergence in the gas phase), so I'm skeptical that it's a fundamental limitation of electronic structure theory...

**Comment by haneug** [comment]
GFNn-xTB approximates density functional theory which suffers from the so-called self-interaction error (SIE). HF on the other hand is SIE-free. This SIE makes it difficult for GFNn-xTB methods to converge on this system because charges are smeared out and difficult to localize. With an implicit solvation model, this is partly repaired. Could using the implicit alpb solvation model be a solution for your problem? In our [QCxMS](https://xtb-docs.readthedocs.io/en/latest/qcxms_doc/qcxms.html) we run our MDs by default with a higher electronic temperature. This helps with so-called static correlation as well as convergence. Is this approach a solution to your problem?

**Comment by corinwagen** [comment]
Hm, yeah, raising the electronic temperature seems like a good option. I don't want to use implicit solvation because I'm trying to use this as the "high" layer of an ONIOM multilayer model, so I'm already including solvent effects explicitly in the lower layer. 

Will raising ``etemp`` significantly change the forces or properties of the molecule?

**Comment by haneug** [comment]
This will have an effect on the properties and forces, but with a temperature of around 1000 K, you should be ok. You might have to test this. In the QCxMS we use 5000 K but these are high-temperature MDs.
