### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Elham-april** [grimme-lab/xtb#692]
Dear Friends,
I am very beginner in installing software. Could you please help me for installing CREST and XTB in ORCA environment? I work with ORCA.

Thank you so much
With Regards

**Comment by awvwgk** [comment]
Let's use the thread here: https://github.com/grimme-lab/xtb/discussions/684

**Comment by Elham-april** [comment]
Yes, but no one answered to me. Could you please help me?

Thank you so much
With Regards
