### ISSUE TITLE
Clarify xtb license in `man/xtb.1.adoc`

### ISSUE THREAD

**Issue by merkys** [grimme-lab/xtb#698]
File `man/xtb.1.adoc` retains restriction "For non-commerical, academia use only.". From #96 I gather that this restriction is lifted. Could this sentence be removed from `man/xtb.1.adoc`?

**Comment by MtoLStoN** [comment]
Sorry for the delay. Indeed this restriction was lifted and we are under an LGPL license now. I will clarify this in #753.
