### ISSUE TITLE
Documentation of GFN-FF charges

### ISSUE THREAD

**Issue by nielskm** [grimme-lab/xtb#699]
When running GFN-FF calculations, the program outputs a `gfnff_charges` file. It also prints a list of `qest` charges to `stdout` together with the atoms. Those two sets of charges are not identical, so what do they each correspond to?

**Comment by Thomas3R** [comment]
Hello Niels,
You are correct, the GFN-FF uses two different sets of charges. The first one is calculated in and used for the initialization of the force field parameters. Those are estimate charges ```qest``` calculated with a topology based electronegativity equilibrium model (EEQ). The second set is determined in the energy and gradient calculation, where the EEQ model takes the atom positions into account. These more accurate charges are then printed into the ```gfnff_charges``` file.
