### ISSUE TITLE
incorrect structure of 1,2-dimethoxybenzene

### ISSUE THREAD

**Issue by mkrompiec** [grimme-lab/xtb#710]
**Describe the bug**
The electronic structure of 1,2-dimethoxybenzene in GFN1 and GFN2 is incorrect, similar structures may be affected. Geometry optimisation leads to a highly twisted benzene ring, with two tetrahedral-like carbons (instead of a completely flat ring). 

**To Reproduce**

Steps to reproduce the behaviour:

1. happens with input [C8H10O2.xyz.zip](https://github.com/grimme-lab/xtb/files/9820053/C8H10O2.xyz.zip)
2. run `xtb` with "--opt" or "--opt --gfn 1"
output showing the error- see [xtbopt.xyz.zip](https://github.com/grimme-lab/xtb/files/9820054/xtbopt.xyz.zip)
xtb version: 6.5.1 (homebrew)

**Expected behaviour**
Flat benzene ring geometry.

**Comment by MtoLStoN** [comment]
I can't reproduce this behavior with the bleed version of xTB nor with the 6.5.1 release version. 
```
xtb_6.5.1 C8H10O2.xyz --opt
```
gives me a very reasonable [geometry](https://github.com/grimme-lab/xtb/files/9820223/6.5.1.xyz.zip).
