### ISSUE TITLE
Linking to ESSL?

### ISSUE THREAD

**Issue by ocelotStride** [grimme-lab/xtb#711]
There is a build failure at the testing stage when linking to essl (-lessl6464 v7.1) and lapack (lapack64.a v3.10.1) with gcc 12.2. I see that ppc64le is supported, is linking against the essl library not?

**Comment by awvwgk** [comment]
We don't have PowerPC systems for testing, so no it is not officially supported. You can sill link against ESSL by using `-Dla_backend=custom` and specify the libraries in `-Dcustom_libraries=essl6464,lapack64`. Be careful with the ABI choice though, we use LP64, if you need ILP64 please add the required command line option in `-Dfortran_flags` to use 64bit integers as default.

**Comment by ocelotStride** [comment]
I see, sorry for the assumption. I will try again with the ABI flag or perhaps the lp64 library instead. Thank you

**Comment by awvwgk** [comment]
If you can share the options you have used for building against ESSL or even provide a patch for the meson build files it might be possible to add an `la_backed` option for ESSL as well.

**Comment by ocelotStride** [comment]
Linking against the lp64 libraries works. I have tried two configurations where I link against each of the following:

1.  -lesslsmp
2.  -lessl

For some reason the smp version of the library fails all tests which is counter-intuitive considering I am building with OpenMP set to true. However, linking with -lessl works just fine.
