### ISSUE TITLE
Please make build of test executables conditional on a dedicated cmake variable

### ISSUE THREAD

**Issue by yurivict** [grimme-lab/xtb#717]
Production package builds don't need tests.

```BUILD_TESTING``` is a default variable for this purpose in cmake.

**Comment by awvwgk** [comment]
Even production package build should pass the test suite, building the tests has a small extra cost while providing a way to verify the functionality of the package.

**Comment by yurivict** [comment]
Package builds happen automatically and there is nobody there who runs tests.

**Comment by yurivict** [comment]
Tests are run manually by port maintainers.

**Comment by awvwgk** [comment]
For packaging ecosystems I'm familiar with like Arch, brew or conda-forge tests are run automatically as part of the packaging process. It is okay if FreeBSD follows a different philosophy here, you just don't have to call ctest in the build process.

**Comment by MtoLStoN** [comment]
I agree with @awvwgk here. The tests ensure that everything works as expected, even for production packages. Therefore, I see no reason for any change here.
