### ISSUE TITLE
Initial velocities in MD/MTD

### ISSUE THREAD

**Issue by mkrompiec** [grimme-lab/xtb#72]
**Is your feature request related to a problem? Please describe.**
When trying to model bimolecular reactions using MTD, there is no way to force selected molecules to collide.

**Describe the solution you'd like**
Set initial velocities for atom groups. For example, let's imagine we have molecules A and B. If I want molecule A to collide with molecule B, I initialize the velocities of A to be proportional to the vector (B_center_of_mass - A_center_of_mass). Of course, this initial velocity would have to be added to the random "thermal" initial velocity.

**Describe alternatives you've considered**
Reaction path functionality solves this problem for simple cases, but I'd like a more general one. 
Can this be done with ASE? Or by hand-modifying the mdrestart file?

**Comment by awvwgk** [comment]
I don't really see a use-case for this feature and it would require a more general concept of atom groups first (we have some basic fragment data in place, which could be (ab)used).

But you know it's an open source project, so feel free to open a PR.

**Comment by mkrompiec** [comment]
I guess hacking the mdrestart file could give me what I want... From what I've understood from the sources, this file contains positions and velocities of all atoms. What are the units of velocity in this file? A/fs or Bohr/(atomic unit of time)?

**Comment by awvwgk** [comment]
As far as I know, the dynamics module uses atomic units.

**Comment by mkrompiec** [comment]
Indeed, modification of mdrestart does the job.

**Comment by shuxiansheng2** [comment]
Dear developers of xtb:
runtype --reactor seems to be deprecated since 6.3 with $reactor group leaving in default xcontrol. how can I reproduce the results in DOI: 10.1021/acs.jctc.9b00143? I want to study some reactions using xtb, but there are no examples in xtb-docs. 
Moreover, if the RMSD-PP method is not recommended so the xtb-docs provides GSM method?

**Comment by awvwgk** [comment]
Please don't post off-topic in other closed threads, just open a new issue.

**Comment by tobigithub** [comment]
@mkrompiec @awvwgk I have to agree, initial velocities are part of many MD programs including Gaussian, Empire, QChem, CP2K. All of them have an option to define initial velocities. So this would be indeed a very useful option.

https://manual.q-chem.com/5.3/Ch9.S8.SS1.html
https://www.ceposinsilico.de/pdf/Empire20.pdf
http://gaussian.com/admp/
https://github.com/cp2k/cp2k/blob/master/src/motion/input_cp2k_md.F

So if the mdrestart file already contains this information, why not start with trajectory zero and let the user decide?
Also @mkrompiec can you explain with a simple example how you "hacked" and solved this issue.
Thanks!

**Comment by awvwgk** [comment]
@tobigithub The advice from above still applies, this is an open source project, feel free to open a PR implementing your suggested feature.

We now actually have a concept of atom groups, so it might be easier to archive than back when this came up.

**Comment by mkrompiec** [comment]
@tobigithub there you go:
```
data = []
with open('mdrestart') as mdrfile:
    for line in mdrfile:
        dl = line.replace("D", "E").split()
        if len(dl) < 2:
            continue
        data.append(dl)
velocities = np.asfarray(data)

#modify your velocities here 

def float_to_f(fl):
    if fl>=0:
        s= '  {:20.14E}'.format(fl)
    else:
        s= ' {:20.14E}'.format(fl)
    return s.replace("E","D")

with open('mdrestart','w') as mdrfile:
    mdrfile.write(" -1.0\n")
    for row in velocities:
        printrow="".join([float_to_f(fl) for fl in row])
        mdrfile.write(printrow+"\n")

```

**Comment by tobigithub** [comment]
> @tobigithub there you go:
> 
> ```
> data = []
@mkrompiec Thank you!

@awvwgk I tried to change the velocities in the mdrestart file, but was not successful, I think the current xtb implementation is different from classical trajectory based AIMD implementations in Gaussian, QChem or Empire (Gaussian and Empire can handle semiempirical AIMD). But again this is purely an observation, based on a few examples, so I might be wrong.
