### ISSUE TITLE
Badge for GH action status is broken

### ISSUE THREAD

**Issue by awvwgk** [grimme-lab/xtb#739]
The badge requested with

https://github.com/grimme-lab/xtb/blob/02854dbdb92703655d65dc0cb7c128230e8b913e/README.md?plain=1#L17

results in

[![Build Status](https://img.shields.io/github/workflow/status/grimme-lab/xtb/CI)](https://github.com/grimme-lab/xtb/actions)

See https://github.com/badges/shields/issues/8671

**Comment by MtoLStoN** [comment]
Thanks for reporting. I'll update this.
