### ISSUE TITLE
conda-forge build for Windows

### ISSUE THREAD

**Issue by shoubhikraj** [grimme-lab/xtb#740]
Hi,

Now that the windows build for xtb is released officially, might it be possible to put it on conda-forge as well? I am currently porting a package to windows, which uses conda with travis-CI to test. Being able to pull xtb would be very helpful in running the automated tests on windows. (It would also be helpful to windows users in general)

Thanks :)

**Comment by awvwgk** [comment]
No this is currently not planned, as the conda-forge Fortran toolchain for Windows is not able to support the features in xtb.
