### ISSUE TITLE
xtbout.json not written for GFN-FF

### ISSUE THREAD

**Issue by nielskm** [grimme-lab/xtb#745]
The `xtbout.json` file that should be written when passing the `--json` flag is not generated when running GFN-FF calculations.

**To Reproduce**
Running `xtb <some-molecule.xyz> --gfnff --json` produces no JSON output file.

**Additional context**
xtb version: 6.5.1

**Comment by MtoLStoN** [comment]
The "--json" flag is, at the moment, not used in conjunction with GFN-FF. We could use this flag to write all available information (replacing the need to use the --wrtopo flag with keywords). 
Is that what you had in mind?

**Comment by nielskm** [comment]
@MtoLStoN Thank you for taking the time to look at this. I was simply thinking if you could output a JSON containing total energy, etc. as done for the xTB methods.

**Comment by MtoLStoN** [comment]
I understand; I'll look into this. This should be relatively easy to do, if I find the time. If this is something you want faster, you are more than welcome to submit a patch.

**Comment by MtoLStoN** [comment]
Thanks to @Thomas3R, we have this implemented now!
