### ISSUE TITLE
Possible to set repulsion potential between two atoms?

### ISSUE THREAD

**Issue by 1234zou** [grimme-lab/xtb#746]
Hi,
Is it possible to set some repulsion potential between two atoms in GFN0/1/2-xTB methods? For example, to keep the distance between two atoms larger than 1.5 A？ Many thanks.

**Comment by MtoLStoN** [comment]
You can constrain the distance between two Atoms by utilizing a [harmonic potential](https://xtb-docs.readthedocs.io/en/latest/xcontrol.html#constraining-potentials).

However, this will work in both directions, so it will constrain the distance at the starting value while not fixing the exact coordinates.
