### ISSUE TITLE
charges file as input for GFN-FF

### ISSUE THREAD

**Issue by hillaper** [grimme-lab/xtb#749]
Dear xTB developers,

**Describe the bug**

from what I understood, based on the documentation and other issues posted, a "charges" file can be used to provide constraints for the atomic charges in the EEQ model of the GFN-FF method. Running xTB 6.5.1 GFN-FF MD with such a file in the same directory does not, however, seem to suffice as a constraint. Instead, following lines are printed to the output:

   fragment charges from < charges > :  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000,

after which xTB generates the partial charges for GFN-FF (gfnff_charges) that differ from the ones given, as if there was no charges file present. Is it even possible to constrain the atomic charges, or does the constraint only refer to the overall charge of certain fragments (which in the present case should be and are equal to 0)?

**To Reproduce**
All files are in the .txt format as the correct filetypes, .xyz and without one in the case of the charges file, were not attachable.

Steps to reproduce the behaviour:

1. happens with input [h2o_g2opted.txt](https://github.com/grimme-lab/xtb/files/10384560/h2o_g2opted.txt), [charges.txt](https://github.com/grimme-lab/xtb/files/10384608/charges.txt) and [xcontrol.txt](https://github.com/grimme-lab/xtb/files/10384622/xcontrol.txt).
2. start `xtb` with (xtb --gfnff --alpb water --input xcontrol.txt --md h2o_g2opted.xyz)
3. output showing the error [gftest.txt](https://github.com/grimme-lab/xtb/files/10384633/gftest.txt)

The charges file is taken directly from a GFN2 geometry optimization output on the same structure.

Best regards, hillaper

**Comment by MtoLStoN** [comment]
The charge handling in GFN-FF was updated in #558. GFN-FF now expects a .CHRG file with the molecule charge in line 1 and the fragment charges in line 2. 

However, this does not fully constrain the fragment charges. The fragment charges are however used as input for the estimation of the GFN-FF charges afaik.

Thanks for bringing this to out attention. We should certainly update the respective documentation.
