### ISSUE TITLE
Input not read by xtb

### ISSUE THREAD

**Issue by manuelperezesc** [grimme-lab/xtb#765]
Dear, I am trying to run a MD simulation with the following input (xtb.inp):

$md
   temp=298.15
   time= 10.0
   dump= 2.0
   step=  2.0
   velo=false
   nvt =true
   hmass=4
   shake=0
   sccacc=2.0
$end

And my command is:

$XTBHOME/bin/xtb --md --I xtb.inp xtbopt.xyz > "output.out"

However, when I do so, it seems that the default MD settings are used and my simulations are supposed to run for 50 ps, rather than 10, which are the ones I specifed above and in the file xtb.inp. 

If I remove the --md flag then the calculation just finished with a SCC cycle.

Is there anyting I am doing wrongly?

**Comment by haneug** [comment]
have you tried -I or --input instead of --I?

**Comment by manuelperezesc** [comment]
Thank you! It does work now @haneug
