### ISSUE TITLE
reactor?

### ISSUE THREAD

**Issue by jouteurestaque** [grimme-lab/xtb#770]
**Describe the bug**
I am looking for that -reactor option described in the paper of metadynamic..
cannot find it anywhere on the doc, by the search option, I am pretty sure it was there before

**Comment by MtoLStoN** [comment]
Currently, there is no automated nano reactor functionality implemented in the xTB code. However, there is a workaround for this using ``crest``. You can find this workaround on the official [CREST documentation](https://crest-lab.github.io/crest-docs/page/examples/utilities/utils_6.html#preparing-a-xtb-nanoreactor-calculation).

**Comment by jouteurestaque** [comment]
Thanks so much, here it was
