### ISSUE TITLE
--acc flag causes numerical issues and hangs

### ISSUE THREAD

**Issue by sheepforce** [grimme-lab/xtb#772]
**Describe the bug**
The xtb 6.6.0 release seems to introduce some problematic behaviour with the `--acc` flag. A numerical hessian calculation may arbitrarily hang, segfault or crash with erros that numerical thresholds can not be reached.
We found this behaviour when [updating xtb in NixOS-QChem](https://github.com/Nix-QChem/NixOS-QChem/pull/250), but I can reproduce the behaviour also on Debian.
Interestingly everything works fine when the `--acc` flag is removed. The actual value of acc does not matter for the behaviour at all.

**To Reproduce**
Steps to reproduce the behaviour:
After building on a fresh Debian OCI-Container via
```
sudo apt install gfortran cmake build-essential git libopenblas-dev
git clone https://github.com/grimme-lab/xtb.git && cd xtb
cmake -B build -DCMAKE_BUILD_TYPE=Release
make -C build
make -C build test
sudo make -C build install
```
or with Nix via `nix run github:sheepforce/nixos-qchem/xtb#xtb -- xtb.xyz --hess --input xcontrol --chrg 0 --uhf 0 --gfn 2 --acc 1.0`

1. happens with input (include input files)
`xtb.xyz`
```
4

  H -0.35738652 -2.42732105  0.01869782
  H -0.55575507  0.31681832  1.27512527
  O -0.71404094 -1.41851105  0.01869782
  O -0.20069873 -0.69255477  1.27610279
```
`xcontrol`
```
$write
            json=true
        $end
```

3. start `xtb` with (all the options here)
``` 
xtb xtb.xyz --hess --input xcontrol --chrg 0 --uhf 0 --gfn 2 --acc 1.0
```
4. run `xtb` with your options and the `--verbose` flag
5. output showing the error
[vebose.txt](https://github.com/grimme-lab/xtb/files/10734486/vebose.txt)

The behaviour is not reproducible. The very same calculation may error with the shown messages, segfault or hang infinitely from the same input with any number of OpenMP threads.

**Expected behaviour**
Reproducible behaviour, terminating calculation and correct behaviour with respect to the `--acc` flag. 

**Additional context**
The problem seems not to occur with the downloadable binary, which I assume is built with the Ifort compiler.
The BLAS implementation does not matter (tested OpenBlas, MKL and a generic BLAS).
XTB and all its dependencies pass all cmake tests.

**Comment by sheepforce** [comment]
The problem seems to be somewhere deeper, possibly in threading? I could produce another hanging case (same inputs as above):

This one hangs:
```
OMP_NUM_THREADS=1,1 xtb xtb.xyz  --chrg 0 --uhf 0 --gfn 1 --hess
```

This one runs fine:
```
OMP_NUM_THREADS=1,1 xtb xtb.xyz  --chrg 0 --uhf 0 --gfn 1 --hess --input xcontrol
```

Thus, it is not only the `--acc` flag.

**Comment by MtoLStoN** [comment]
Thank you for taking your time to report these issues (and also for the detailed report)!
I'm out of office right now till next Tuesday, but I'll look into this asap when I'm back. Of course, if you are getting more insights on what exactly produces the error until then, this would be very helpful.
So, just to confirm: None of these errors were reproducible with the static binaries I built?

**Comment by sheepforce** [comment]
> Of course, if you are getting more insights on what exactly produces the error until then, this would be very helpful.

If I find something I will report :) From the behaviour I would expect some threading stuff but currently I really have no idea, currently.

>  So, just to confirm: None of these errors were reproducible with the static binaries I built?

Exactly, yes. Just tested again and this one behaves as expected in the described cases. Thus, I would suspect some difference in Ifort vs gfortran optimisations or something like this.

**Comment by MtoLStoN** [comment]
@sheepforce I could only reproduce the hang but not the segfault. Could you check if #774 fixes your errors?

**Comment by sheepforce** [comment]
I can confirm that this solves the two hanging tests :partying_face: The segfaults seemingly occured randomly, I could also not always reproduce it. However, seems to work so far.

The debug build still fails the two test cases.

**Comment by MtoLStoN** [comment]
Nice, that this works. 
I'll look into the debug cases - however this seems unrelated to this specific bug.
