### ISSUE TITLE
.param_gbsa.solvent file location

### ISSUE THREAD

**Issue by tobigithub** [grimme-lab/xtb#78]
Hi,
I wonder where the .param_gbsa.solvent file is located, which is referenced here,
or is that something the user has to provide to activate the correct solvent?

````
$gbsa
~~~~~
*solvent*='string'::
    solvent for the generalized born (GB) model with solvent accessable
    surface area (SASA), requires `.param_gbsa.solvent` in `XTBPATH`.
    Does not activate GBSA (use commandline).
````
https://github.com/grimme-lab/xtb/blob/master/man/man7/xcontrol.7.txt

Thank you
Tobias

**Comment by awvwgk** [comment]
All GBSA parameter files are compiled into the source, so there is currently no need to track this files, therefore I did not add them to the repository in the first place. On the other hand, if somebody wishes to modify those parameters by hand (like in #79) than it would be nice to have a version available.

**Comment by awvwgk** [comment]
So the general question is, should there be GBSA parameter files in the repository?

The only application would be the modification of parameters or adding custom parameters, yet the format is only available from the reader in the implementation and not really documented:

https://github.com/grimme-lab/xtb/blob/a869138d60c6fd0759046d6ec1af4ea58d3898d0/xtb/gbobc.f90#L446-L461

There is indeed a way to load custom parameters via the API and use them in C or Python projects.

https://github.com/grimme-lab/xtb/blob/a869138d60c6fd0759046d6ec1af4ea58d3898d0/include/xtb.h#L147-L159

So generally I think we don't need the parameter files for GBSA in the repository.

**Comment by tobigithub** [comment]
@awvwgk 

> should there be GBSA parameter files in the repository?

I was looking for parameters to do SAS scaling and pKa predictions.
Because there is no information on the parameters its hard to determine what is what.
If there would be small addition like **soset** is this and that, **thos** is this and that, it could be helpful.

**Comment by awvwgk** [comment]
@tobigithub Yeah, we should add some documentation there. Right now it is scatter in comments in the source code.

**Comment by awvwgk** [comment]
Parameters are now available in https://github.com/grimme-lab/gbsa-parameters
