### ISSUE TITLE
How does aiss calculate the single-point interaction energy

### ISSUE THREAD

**Issue by boyuezhong** [grimme-lab/xtb#780]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**If possible state how you can assist in providing data or code to to implement the feature**
A short description of what you can provide to make the feature possible.

**Additional context**
Add any other context about the feature request here.

**Comment by Albkat** [comment]
1) **Your question is not a bug/new feature of xTB**. Please open a new discussion in the future if you have similar questions about the methods used in xTB. 
2) Please try to follow the provided guidelines.
