### ISSUE TITLE
aISS xtbiff decomposition energies

### ISSUE THREAD

**Issue by WentongZhou** [grimme-lab/xtb#782]
Hi there,
Is it possible to export the xtbiff decomposition energies (like the old `xtbiff` binary) using the new docking module `aISS` in `xTB`?

Thanks 
Wentong Zhou

**Comment by cplett** [comment]
Hi,
Currently, the docking module `aISS` cannot be used with external energy expressions. However, it evaluates the structures based on the old `xtbiff` energy, which is now integrated into the current `xtb` version. 
The charges should also be considered with the `aISS,` but in version 6.6.0 they can be set only with the `.CHRG` file. The file should have three lines: the first contains the total charge of fragment A + B, the second line contains the charge of fragment A, and the third of fragment B.

**Comment by marcelmbn** [comment]
@cplett FYI, closed this one as an extension towards this feature is not planned, if I'm correct?
