### ISSUE TITLE
Parameterized non-standard solvent 

### ISSUE THREAD

**Issue by Fedelau** [grimme-lab/xtb#791]
Hi there,

I want to use the implicit solvent model ALPB in xtb calculation but with cyclopentyl methyl ether, that there isn't in the parameterized solvents available. So, I was wondering if is it possible to give to the program a specific parameter to model the requied solvent in the command line or as an input. 

Any suggestions? 
Thank you in advance!

**Comment by MtoLStoN** [comment]
Hi @Fedelau,

the implicit solvent models used in xTB (ALPB and GBSA) are highly parametrized for specific solvents based on theoretical and experimental data. You can find more information about this parametrization in the [respective publication](https://doi.org/10.1021/acs.jctc.1c00471).

As such, there is no readily available parameter that could be given as a command-line input to model new solvents. Given the accuracy of the implicit solvent models, I would suggest just using a similar solvent that is already parametrized.
