### ISSUE TITLE
Exact fixing not working for gfnff geometry optimization

### ISSUE THREAD

**Issue by pwging13** [grimme-lab/xtb#809]
using exact fixing with $fix with a gfnff optimization fails with the xtb 6.6.0 binaries.

```
 * calculating model hessian...
Using GFN-FF Lindh-Hessian
 * fragmented diagonalization... 10 fragments
 Shifting diagonal of input Hessian by   2.006057175050955E-002
 Lowest  eigenvalues of input Hessian
   -0.000061   -0.000028   -0.000000   -0.000000   -0.000000   -0.000000
   -0.000000   -0.000000   -0.000000   -0.000000   -0.000000   -0.000000
   -0.000000   -0.000000   -0.000000   -0.000000   -0.000000   -0.000000
 Highest eigenvalues
    2.884734    2.956798    2.972934    3.108546    3.121327    3.239710

 k=         144   nvar=        3087
 ANC generation failed
================
 final structure:

```

**Comment by TariniHardikar** [comment]
Hello! I was wondering if you ever found a fix for this issue? I'm running into the same problem with xtb 6.7.0, and I'm trying to do fixing as follows:
$fix
 elements=[N,Zn]
 freeze=[1, 4, ..., etc]

**Comment by pwging13** [comment]
> Hello! I was wondering if you ever found a fix for this issue? I'm running into the same problem with xtb 6.7.0, and I'm trying to do fixing as follows: $fix elements=[N,Zn] freeze=[1, 4, ..., etc]

Unfortunately no, I have the same issue still.

**Comment by TariniHardikar** [comment]
Hey @pwging13, the solution mentioned here: https://github.com/grimme-lab/xtb/issues/800 worked for me.
