### ISSUE TITLE
Install the manual as well

### ISSUE THREAD

**Issue by pierre-24** [grimme-lab/xtb#81]
**Is your feature request related to a problem? Please describe.**
`xcontrol`  and other [manual entries](https://github.com/grimme-lab/xtb/tree/master/man) are not installed.

**Describe the solution you'd like**
Either they should be (through meson), or this should go in [the documentation](https://xtb-docs.readthedocs.io/en/latest/contents.html), no?

**Describe alternatives you've considered**
*Nothing*.

**If possible state how you can assist in providing data or code to to implement the feature**
*That depends on the solution* (there may be way to include manual page in Sphinx, though)

**Additional context**
*None*.

**Comment by pierre-24** [comment]
(additionally, just a thought: having the Read the docs and xtb repo separated may be a good idea for some stufs [because there is 3 differents program in 3 differents repos, which is good] but may introduce delay and incoherences in the documentation-versus-actual-version of the program)

**Comment by awvwgk** [comment]
The manuals are actually installed if you provide the `a2x` generator.

https://github.com/grimme-lab/xtb/blob/57a2aeab560add45a3f4ce061f9d07576d98a759/meson.build#L397-L402

You might need the `asciidoc` or any compatible generator available on your system.

**Comment by pierre-24** [comment]
Yes, indeed, when installed it works :)
