### ISSUE TITLE
Can I convert GFNFF into CHARMM format?

### ISSUE THREAD

**Issue by OkKakao** [grimme-lab/xtb#816]
Hi

I simulated a molecule has keggin structure with gfnff forcefield.

But I want to simulate this with openmm.

can I convert this forcefield into CHARMM?

I fount that the following command can provide topological infomation.

```xtb --gfnff methionine.xyz --wrtopo nb,bpair,alist,blist,tlist,vtors,vbond,vangl```

Can I utilize these information to convert the forcefield?

Thank you

**Comment by haneug** [comment]
To my knowledge, this has not been implemented, and I believe we will not add it in the foreseeable future because we do not use CHARMM in our group.

**Comment by OkKakao** [comment]
> 

Then Can I modify the topology file that xtb generated automatically?

There are several mismatches that i didn't intended.

For example, xtb creates K-O bond when I simulated KCl with cyclodextrin.
