### ISSUE TITLE
Using external program with xTB 6.6.0

### ISSUE THREAD

**Issue by amavr78** [grimme-lab/xtb#819]
In xtb 6.6.0 , the program crashes with a segmentation fault , when I try to call ORCA as an external program with xTB .
This is during a calculation with censo, but the error is due to the xtb .
This is not happening with xtb 6.5.1

I am trying to execute with the command:  xtb coord --orca -I opt.inp 

The contents of the opt.inp are:
$opt
maxcycle=8
microcycle=8
average conv=true
hlow=0.01
s6=30.00
engine=lbfgs
$external
   orca input file= inp
   orca bin= /data1/bin/ORCA/orca_5_0_4_linux_x86-64_openmpi411/orca
$end

When  I execute , I get the following segmentation fault:
           -------------------------------------------------
          |                Calculation Setup                |
           -------------------------------------------------

          program call               : xtb coord --orca -I opt.inp
          coordinate file            : coord
          omp threads                :                    40

   ID    Z sym.   atoms
    1    6 c      1-4, 6-9, 11-13, 20, 25, 28, 31, 34, 35, 38
    2    7 n      5, 10
    3    1 h      14-19, 21-24, 26, 27, 29, 30, 32, 33, 36, 37, 39, 40, 42,
                  43, 45, 46
    4   16 s      41, 44
    5    8 o      47-52
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
xtb                000000000046D41A  Unknown               Unknown  Unknown
xtb                00000000037F12A0  Unknown               Unknown  Unknown
xtb                0000000000D05C22  xtb_extern_orca_m         198  orca.f90
xtb                00000000006B39A3  xtb_main_setup_mp         160  setup.f90
xtb                000000000042C7EE  xtb_prog_main_mp_         526  main.F90
xtb                0000000000450642  MAIN__                     57  primary.f90
xtb                00000000004067F2  Unknown               Unknown  Unknown
xtb                00000000037F2740  Unknown               Unknown  Unknown
xtb                00000000004066D7  Unknown               Unknown  Unknown

I am using the precompiled binaries.
I thought that the error could be related to the optimization , but it is not. 
It is crashing, even If I ask to do an energy calculation.

The xtb 6.5.1 is running fine without any errors.

**Comment by MtoLStoN** [comment]
I can replicate this issue. A binary built from c6e56db7e7453024e64d6c7e1fb7ba74b0a7120c does not have this issue; a binary built from 9f0c28cec5e233bb1c30c69fe88b5966e6a77ea2 does. So the error has been introduced in #763. @Albkat, could you have a look?
