### ISSUE TITLE
Missing libxtb.so in the xtbwrapper.py routine

### ISSUE THREAD

**Issue by bbraunsfeld** [grimme-lab/xtb#82]
Hi, 
thank you for open-sourcing this project.

I tried to use the xtbwrapper.py and got an error because of a missing file "libxtb.so".

I used a conda enviroment with python 3.7 and the "setup.py install" to get xtb. The packages  ase/numpy/ctypes were already installed and updated.

Then I used the following python code  from the provided example:

```
from ase.io import read
from xtb import GFN2

mol = read('coord')
mol.set_calculator(GFN2())
energy = mol.get_potential_energy()
forces = mol.get_forces()
```
The error occurs after mol.set_calculator(GFN2()) is called.

The error:
"OSError: libxtb.so: cannot open shared object file: No such file or directory"

Is the libxtb.so something i have to create manually?

Best regards
Benedict

**Comment by awvwgk** [comment]
Installing the Python package still requires a version of `xtb. There has to be a `xtb` installation present and available on your system. That means the shared object should be somewhere in your `LD_LIBRARY_PATH`.

**Comment by awvwgk** [comment]
Closing this as stale.
