### ISSUE TITLE
Halogen angle incorrectly calculated

### ISSUE THREAD

**Issue by hanimustafa** [grimme-lab/xtb#829]
There seems to be a bug in the calculation of the halogen bond angle in xtb/halogen.f90:

 75       ! angle part. term = cos angle B-X-A
 76       XY = SQRT(D2BX*D2AX)
 **77       TERM = (D2BX+D2AX-D2AB) / XY**
 78       aterm = (0.5_wp-0.25_wp*term)**alp
 79       t13 = r0ax/rax

line 77 should be:

TERM = (D2BX+D2AX-D2AB) / (2*XY)

**Comment by hanimustafa** [comment]
I see that the issue is with the old paper I was using as a reference (https://pubs.acs.org/doi/10.1021/acs.jctc.7b00118 equation 13)

It is clear from the most recent paper (https://doi.org/10.1002/wcms.1493 equation 35) that this is not a bug.

**Comment by Albkat** [comment]
Hi, exactly. Thank you for contributing this.
