### ISSUE TITLE
Segmentation fault after exceeding certain number of atoms

### ISSUE THREAD

**Issue by smheidrich** [grimme-lab/xtb#83]
Sorry in advance if this turns out to be something stupid like insufficient memory on my system (doesn't look like it to me, but who knows).

**Describe the bug**

If the number of atoms in the system to be calculated is greater than a certain element-specific number (e.g. 255 for H atoms), the code segfaults.

**To Reproduce**

Minimal reproducible example using the Python interface:

```python
import ase
import numpy as np
from xtb import GFN0 as XTB

N = 256 # 255 works fine

a = ase.Atoms(["H"]*N)
a.positions[:] = np.random.random((N,3))*500
c = XTB()
a.set_calculator(c)
a.get_potential_energy()
```

**Expected behaviour**
This looks to me like it's caused by some hardcoded limit(s) in the code - it would be great if there was information on this in the docs, so that people can recompile the code with increased limits.

**Additional context**
Tested on the 6.3.0 pre-release.

**Comment by awvwgk** [comment]
We don't have hard coded limits in `xtb`. Is https://xtb-docs.readthedocs.io/en/latest/setup.html#setting-up-xtb relevant here?

**Comment by awvwgk** [comment]
Since you are using GFN0, could you check this with the stable version (v6.2.2) instead of the preview. Let's hope it is not an issue introduced by my tampering with the Hamiltonian in the preview.

**Comment by smheidrich** [comment]
> We don't have hard coded limits in `xtb`. Is https://xtb-docs.readthedocs.io/en/latest/setup.html#setting-up-xtb relevant here?

Yep, that was it. ``ulimit`` didn't help, but setting ``OMP_STACKSIZE=1G`` and decreasing ``OMP_NUM_THREADS`` fixed it on my system.

Thank you very much for the help & sorry for wasting your time!
