### ISSUE TITLE
Different single-point GFN-FF energy with and without argument --verbose

### ISSUE THREAD

**Issue by dargen3** [grimme-lab/xtb#835]
Hello,
I'd like to report a potential bug. TOTAL ENERGY for the same structure differs with and without the --verbose flag. The version of xtb is 6.6.0.

**To Reproduce**

[P85371.zip](https://github.com/grimme-lab/xtb/files/12126591/P85371.zip)

`xtb P85371.pdb --gfnff --alpb water`
results in TOTAL ENERGY = -35.183991089038 Eh

`xtb P85371.pdb --gfnff --alpb water --verbose`
results in TOTAL ENERGY = -35.353063192998 Eh

In both cases, I also get the warning but without an idea, of how to handle it and whether is it related to the error described above.
[WARNING] Runtime exception occurred
-1- gfnff_setup: Could not read topology file.

If the error is on my part, please guide me. 
Thank you,
Ondřej

**Comment by Albkat** [comment]
Hi, thank you for reporting this.
It seems to be a bug.

**Comment by dargen3** [comment]
Thank you for your prompt reply. Do you have any idea which energy is correct, please?

**Comment by Albkat** [comment]
So the energy that comes from the SCC routine:  `TOTAL ENERGY = -35.183991089038 Eh`, which is most likely the right energy. 
But I recommend waiting until this issue is debugged.

**Comment by dargen3** [comment]
Hello, i have bad news. The bug is also in the 6.5.1 version. And it affects also structure optimization. 

`xtb P85371.pdb --gfnff --alpb water --opt
`
`xtb P85371.pdb --gfnff --alpb water --opt --verbose
`
[optimized_structures.zip](https://github.com/grimme-lab/xtb/files/12131422/optimized_structures.zip)

I know that it is pretty difficult to say, but is there any estimation, of when this issue can be debugged, please? Week, month, half of the year? I'm sorry to be in such a hurry, but this is quite critical for me and I have to decide what to do next. I'd try to look into it myself, but I'm completely out of Fortran.

**Comment by MtoLStoN** [comment]
Thank you for reporting this Issue. The difference in the output stems from here:
https://github.com/grimme-lab/xtb/blob/27203a8a97659db45b30be196c3f99b0c9fe51df/src/gfnff/gfnff_ini.f90#L918-L931

These routines are only activated when ``pr`` is set to ``true``, which is essentially the same as setting the verbosity level with ``set%verbose``. If these lines are commented out, the energy output will be the same whether or not the ``--verbose`` option is used, as it should be.

At the moment, I am not entirely confident with the force field code and cannot immediately identify the error (and it's late right now).@Thomas3R, do you have any idea?

**Comment by MtoLStoN** [comment]
So, I just checked with @sespic, and this actually seems to be a bug, that thankfully only hits a few specific pi systems. I will prepare a PR, that fixes this.

@dargen3 To answer your question, the energies and geometries, that are obtained with the ``--verbose`` should be the ones you would obtain without this bug.

**Comment by dargen3** [comment]
Thank you for the message and for working on the bug!

**Comment by dargen3** [comment]
Hello, thank you for resolving the error. I want to ask, how do I calculate for the correct energy? With or without the --verbose argument? Or are both options affected and I have to wait for the next version?

**Comment by MtoLStoN** [comment]
Hi @dargen3,
Both versions were affected. The error was fixed in #836. You can use xTB 6.6.1, which was released today.
