### ISSUE TITLE
Dirty source release v6.6.1

### ISSUE THREAD

**Issue by bjoe2k4** [grimme-lab/xtb#840]
Not a bug with the code, so i deleted the Issue template.

1. The [source release](https://github.com/grimme-lab/xtb/releases/download/v6.6.1/xtb-6.6.1-source.tar.xz) has pre-populated `subprojects` and a superfluous `.git` folder. The previous releases did not. 
2. The source release references a subproject version `subprojects/*.wrap` newer than in the git repo (toml-f v0.4.1, but git HEAD still has v0.2.3) . 
3. some subprojects could be updated (test-drive v0.3.0 -> v0.4.0; s-dftd3 v0.6.0 -> v1.0.0; dft-d4 v3.4.0 -> v3.5.0).

Intentional or oversight?

**Comment by MtoLStoN** [comment]
Thank you for bringing this to my attention and reporting it. You were correct in identifying an oversight. I replaced the source release with a new and clean one. Additionally, I will prepare a PR to update the subprojects to ensure everything is up to date.
