### ISSUE TITLE
Wrong principal quantum numbers for Cs/Ba

### ISSUE THREAD

**Issue by marcelmbn** [grimme-lab/xtb#842]
The principal quantum numbers in the following files are incorrect for caesium and barium as they refer to the 5s/5p shell instead of the 6s/6p shell (probably they were copied from Rb/Sr, but not modified). However, direct change of these numbers would lead to consequences for the parameterization.

For a more detailed discussion on this issue, see also the following PR in the `tblite` repository: https://github.com/tblite/tblite/pull/123

https://github.com/grimme-lab/xtb/blob/8d0f1dd02f9d00324d95662d90f3fa123bf01e1f/param_gfn1-xtb.txt#L746-L770
https://github.com/grimme-lab/xtb/blob/8d0f1dd02f9d00324d95662d90f3fa123bf01e1f/src/xtb/gfn1.f90#L255-L269

**Comment by awvwgk** [comment]
Since this requires a change in the parametrization it is probably not worth to update those without a refit.
