### ISSUE TITLE
segmentation fault error

### ISSUE THREAD

**Issue by danieleveclani** [grimme-lab/xtb#846]
Dear xtb developers,

I'm trying to optimize a system of about 1500 atoms, however when I try to run the calculation I get a segmentation fault.

I installed the program through conda environment as you recommended, in my slurm scirpt file ([script.txt](https://github.com/grimme-lab/xtb/files/12344879/script.txt)) I set:
ulimit -s unlimited
export OMP_STACKSIZE=60G

However I always get the same error. On smaller systems I don't get this error

Could you help me to solve this problem??

Waiting for your kind reply.
Best,
Daniele Veclani

**Comment by MtoLStoN** [comment]
Dear @danieleveclani,

in general, it would be best if you could provide the input files you are using to make it possible for us to evaluate your error. However, looking at your script, I can probably already guess what is happening here. 
For the ulimit setting to have any effect on the behaviour of the xTB binary, they need to be changed before starting the actual calculation. You could therefore try to reorder the commands in your script, e.g. like this
```
ulimit -s unlimited

xtb Complex.xyz --acc 0.2 --opt vtight --charge 24 --pop --dipole  > out.log 
```
Let me know if this works for you. If you still have problems, it would be great if you could provide your input files.

**Comment by danieleveclani** [comment]
Yes, 

you are right, indeed t I noticed the error as soon as I sent the previous message, now the calculation goes but in the output file I get something strange:
"molecular fragmentation (1/2 indicates fragments):
111111111111111111111111111111111111111111111111111111111111111111111111
111111111111111111111111111111111111111111111111111111111111111111111111
111111111111111111111111111111111111111111111111111111111111111111111111
111111111111111111111111111111111111111111111111111111111111111111111111
111111111111111111111111111111111122222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
222222222222222222222222222222222222222222222222222222222222222222222222
2222222222222222222222222222222222222222222222222222222222
# atoms in fragment 1/2:   322  1104
 fragment masses (1/2) :     2392.83    10403.07
CMA distance (Bohr)    :   3.053
constraining FC (au)   :  0.0500"

I am attaching the complex.xyz ([Complex.txt](https://github.com/grimme-lab/xtb/files/12345332/Complex.txt)), out.out ([out.txt](https://github.com/grimme-lab/xtb/files/12345334/out.txt)) and new script files ([script.txt](https://github.com/grimme-lab/xtb/files/12345337/script.txt)) created.

I really thank you for your help.

Best,
Daniele.

**Comment by MtoLStoN** [comment]
Perfect, I'm happy that it works for you now! 
The fragmentation section is indeed the intended output if xTB detects multiple fragments and just gives you additional information about your complex.
I agree that the presentation could be way better, we actually have a very old Issue on this (#321).
