### ISSUE TITLE
ifort vs gfortran: charge constrain error 

### ISSUE THREAD

**Issue by Albkat** [grimme-lab/xtb#852]
**Describe the bug**
The optimized binaries, compiled using gfortran and ifort, perform not in the same manner for the same structure. 
Despite ifort running smoothly, gfortran encounters an error during charge equilibration.

**To Reproduce**
Steps to reproduce the behaviour:

1. happens with **ptcomp.xyz**
2. `meson setup --buildtype=debugoptimized _build_`
3. `_build_/xtb ptcomp.xyz`
4. Error:
```fortran
Error termination. Backtrace:
-2- Global environment terminated
-1- (goedecker_solve) charge constrain error
```

**Expected behaviour**
The identical performance for both compilers 

**add**
Both binaries were compiled from the latest source code available at the time of encountering the issue.

[grfotran_ifort.zip](https://github.com/grimme-lab/xtb/files/12410457/grfotran_ifort.zip)

**Comment by Albkat** [comment]
I will try to fix this later myself, but feel free to contribute

**Comment by MtoLStoN** [comment]
I tried to reproduce this behaviour with ``gfortran12`` and ``gfortran13``, but I am not able to (I have the normal behaviour, same as with ``ifort``). Which version of ``gfortran`` did you use?

**Comment by marcelmbn** [comment]
However, if this can help: I had to set `OMP_STACKSIZE` and `ulimit -s unlimited` on all platforms to make it work. Could be interesting also for https://github.com/grimme-lab/xtb/issues/653.
