### ISSUE TITLE
Raman calculations dont show Raman frequencies and/or intensities

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [grimme-lab/xtb#861]
After testing a molecule (Benzene) and using --hess, the results show infrared spectrum but no intensities for raman spectrum. After checking the file `vibspectrum` in the section `selection rules`  all frequencies display  for IR and Raman as YES for all. It doesnt discriminate if is Raman or IR active.
[vibspectrum.txt](https://github.com/grimme-lab/xtb/files/12584027/vibspectrum.txt)

**Comment by Andrew-S-Rosen** [comment]
@AndresOrtegaGuerrero: You can find the Raman intensities in the stdout and also in the `g98.out` file.

**Comment by awvwgk** [comment]
The Raman printout has been removed

**Comment by AndresOrtegaGuerrero** [comment]
> @AndresOrtegaGuerrero: You can find the Raman intensities in the stdout and also in the `g98.out` file.

Thank you @Andrew-S-Rosen  , then it seems the calculations shows no active Raman freq. , yet this issue was closed
