### ISSUE TITLE
COSMO Screening Charge and Volume

### ISSUE THREAD

**Issue by aketo2023** [grimme-lab/xtb#863]
I have encountered two issues when using XTB COSMO outputs with other COSMO related programs, surface charges and volume. 

After performing some XTB COSMO calculations and comparing them with DFT calculations, I have noticed that the COSMO surface charges appear to be for the molecule charge and not the screening charge. For example in the case of water, the surface charge near oxygen is negative but the screening charge of the solvent should be positive (see attached). It would be useful if there was an option to switch the COSMO output from molecule to screening charge, as is convention. This would allow other programs which use COSMO files to easily use XTB COSMO output.

The other issue is that while XTB outputs an area during the COSMO calculation, other COSMO programs output a volume which can be used in further calculations. It would be useful if volume was included in the XTB COSMO output.

Thanks,
Angus

![XTB_COSMO_Water_Surface SigmaProfile](https://github.com/grimme-lab/xtb/assets/144824522/982277fc-e02f-423a-ab94-1c0c3c56dd7b)

**Comment by MtoLStoN** [comment]
Thank you for reporting this. We will add a keyword, that allows the usage of the Turbomole convention for the writing of ``.cosmo`` files (see #864). 

I will also look into the possibility of adding a volume to the output file.

**Comment by MtoLStoN** [comment]
Just to follow up, starting from #864, you should have the possibility to choose the Turbomole convention for writing ``cosmo`` files with the flag ``--tmcosmo``. I also implemented a new ``ddvolume`` module to calculate the volume of a solute and print it out, when the Turbomole convention is requested. 
This should fix your issue.

**Comment by aketo2023** [comment]
That's great, thank you so much!
