### ISSUE TITLE
xtb as a MTD driver for Turbomole/Orca

### ISSUE THREAD

**Issue by mkrompiec** [grimme-lab/xtb#87]
**Is your feature request related to a problem? Please describe.**
xtb's metadynamics implementation is unique, and it would be great to be able to use it with other methods than dftb

**Describe the solution you'd like**
I can see that (at least in some situations) xtb can be used as a driver for Turbomole or Orca. However, attempts to run MTD with Turbomole (xtb --tm) lead to a catastrophe: although Turbomole control files are created correctly and ridft/rdgrad are called, the geometry seems to wander off uncontrollably. Any chance this could be made to work? Alternatively, would it be possible to (re)implement xtb’s RMSD-based MTD in ASE?

**Comment by awvwgk** [comment]
Have you checked the time step for the DFT calculation? xTB methods can effort an incredibly large time step of 5 fs, which might be an order of magnitude to large for DFT.

**Comment by mkrompiec** [comment]
You are right, it works fine provided that the time step is low. It seems the crash on my side was caused by both too high a time step and miscofiguration of TM.
