### ISSUE TITLE
Specifying total charge makes GFN-FF segfault using PDB input

### ISSUE THREAD

**Issue by nielskm** [grimme-lab/xtb#872]
**Describe the bug**
When running GFN-FF on a PDB file, `xtb` segfaults if a total charge is given as command-line input.

**To Reproduce**
[complex.pdb.txt](https://github.com/grimme-lab/xtb/files/12697984/complex.pdb.txt)

Run on attached input (probably rename to `.pdb` first)
`$ xtb complex.pdb --gfnff -c -7`

This produces:
[error.log](https://github.com/grimme-lab/xtb/files/12698040/error.log)

**Additional context**
System information:
Ubuntu 22.04
xtb version 6.6.1 installed from conda-forge (I also built and checked with the latest main branch).

**Comment by MtoLStoN** [comment]
Thanks for reporting this. It seems that this issue stems from the fact, that by manually altering the charge of the molecule the fragment charges read in from the pdb files are invalid as well. The corresponding lines of code can be found here:
https://github.com/grimme-lab/xtb/blob/c31a1ca5e9dcb5ee9b0b9da19a077136c3b57963/src/gfnff/gfnff_ini.f90#L503-L506
and here
https://github.com/grimme-lab/xtb/blob/c31a1ca5e9dcb5ee9b0b9da19a077136c3b57963/src/gfnff/gfnff_ini.f90#L519-L528

I'll look into this if I find the time, however I'm out of office until october 4th. As a workaround, you can just transfer the pdb file to any other format where xTB does not expect fragment charge information for the moment.
