### ISSUE TITLE
Link to `xtb-python` should be to `tblite`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [grimme-lab/xtb#874]
https://xtb-docs.readthedocs.io/en/latest/python.html

The link here points to `xtb-python`, but the `xtb-python` repo says it's not maintained anymore and to use `tblite`. The `xtb` docs should point to `tblite` instead.

**Comment by MtoLStoN** [comment]
I agree and added a warning box to the respective section including a link to tblite.
