### ISSUE TITLE
[BUG] segfault when running large system

### ISSUE THREAD

**Issue by chem-william** [grimme-lab/xtb#877]
**Describe the bug**
When running a GFN-FF system with 801 atoms (a molecule with a transition metal + a bunch of water), I get a segmentation fault. If I remove most of the water, the calculation runs fine. I've tried installing with GCC compilers with MKL installed through conda. I've also tried downloading the binary from the releases page, but both segfaults.
With the binary from the releases and the following command:
```bash
./xtb-6.6.1/bin/xtb ./big_system.xyz --gfnff --omd --verbose
```
I get:
```bash
     |                       L-ANC optimizer                     |
      -----------------------------------------------------------
          low memory version by Sebastian Ehlert

          ...................................................
          :                      SETUP                      :
          :.................................................:
          :   energy convergence        0.5000000E-04 Eh    :
          :   grad. convergence         0.4000000E-02 Eh/a0 :
          :   optimization log               true           :
          :   writing optlog all                1     steps :
          :   Hessian reset                    20     steps :
          :   maximium step len.        1.0000000     a0    :
          :   LBFGS images                     20           :
          ...................................................
 * calculating model hessian...
Using GFN-FF Lindh-Hessian
 * fragmented diagonalization... 8 fragments
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
xtb                0000000002A93150  Unknown               Unknown  Unknown
xtb                0000000000D1EF46  xtb_gfnff_fraghes         374  frag_hess.f90
xtb                0000000000A4876C  xtb_relaxation_en         645  relaxation_engine.f90
xtb                00000000008AFCF2  xtb_geoopt_mp_geo         126  geoopt_driver.f90
xtb                00000000004364DB  xtb_prog_main_mp_         686  main.F90
xtb                000000000044BF82  MAIN__                     57  primary.f90
xtb                000000000040336D  Unknown               Unknown  Unknown
xtb                0000000002A95420  Unknown               Unknown  Unknown
xtb                000000000040324E  Unknown               Unknown  Unknown
```

**To Reproduce**
Steps to reproduce the behaviour:
1. download the binary from the releases page
2. download the structure I've included 
3. run the following command: ./xtb-6.6.1/bin/xtb ./big_system.xyz --gfnff --omd --verbose
4. a segfault should happen

Please provide all input and output file such that we confirm your report.

**Expected behaviour**
I expected it run a full MD trajectory with the GFN-FF

**Additional context**
[xtb.zip](https://github.com/grimme-lab/xtb/files/12742629/xtb.zip)

It seems to be a weird memory issue. I submit the big system (801 atoms) with 80GB of memory. That crashes. If I then remove 12 water molecules (771 atoms in total), suddenly the job runs partially with no more than 5GB of memory, but still crashes with a segfault. I have included the partial output as an attachment.
At 708 atoms seems to be the breaking point below which it runs and above which it crashes - no matter the amount of memory (I tried up to 80GB).

**Comment by chem-william** [comment]
It seems to only happen with the L-BFGS Approximate Normal Coordinate optimizer (L-ANCopt) (which is chosen by default). If I change to the Approximate Normal Coordinate Rational Function optimizer (ANCopt) optimizer everything works

**Comment by MtoLStoN** [comment]
Which operating system are you using? Did you already set your "OMP_STACKSIZE" variable (e.g. ``export OMP_STACKSIZE=10GB``) and set the ulimit to unlimited? (``ulimit -s unlimited``). May be related to #191.

**Comment by chem-william** [comment]
Oh, the `ulimit -s unlimited` did the trick! Thank you very much!

I'll leave the rest of the info for others in case that's helpful

`OMP_STACKSIZE` was set to match the allocated memory from SLURM. The following env variables was set:
```bash
export OMP_STACKSIZE=80G
export OMP_NUM_THREADS=1,1
export MKL_NUM_THREADS=1
```
I'm on ```bash
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core
``
