### ISSUE TITLE
Brew installation issue

### ISSUE THREAD

**Issue by mirekrub** [grimme-lab/xtb#880]
**Describe the bug**
Upon building through (brew install xtb) on  MacOS-Sonoma/M1/. The xtb the compilation is interrupted by: 
meson.build:14:0: ERROR: Unable to detect linker for compiler `/opt/homebrew/bin/gfortran -Wl,--version`
ld: unknown options: --version 

I am using the gfortran compiler installed via brew.  

Thanks for the help.

**Comment by MtoLStoN** [comment]
This sounds like a problem with the support of the GNU ``ld`` linker in MacOS. Maybe related to [this](https://github.com/Homebrew/homebrew-core/issues/17794) issue?

As we do not have systems running macOS, I can't really replicate this issue. But you may try unlinking the brew binutils to restore to the system default linker by running
```
brew unlink binutils
```

**Comment by mirekrub** [comment]
Thanks
