### ISSUE TITLE
How can I make two molecules separated during the optimization?

### ISSUE THREAD

**Issue by OkKakao** [grimme-lab/xtb#883]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**If possible state how you can assist in providing data or code to to implement the feature**
A short description of what you can provide to make the feature possible.

**Additional context**
Add any other context about the feature request here.

Hi.

I optmized the initial structure of two Phosphotungstic acid molecules with the following command.

```xtb --opt PTA-dimer.xyz tight```

However, two molecules were merged during the optimization process.

Is there any method that I can make them seprated during the optimization process?

Here's the files that I used and output file.

input: PTA_dimer.xyz

output: PTA_dimer_opt.xyz

[PTA_files.zip](https://github.com/grimme-lab/xtb/files/12858308/PTA_files.zip)

**Comment by haneug** [comment]
You can optimize the monomers separately and then put them in one xyz file. Alternatively you can try to use the [GFN-FF](https://xtb-docs.readthedocs.io/en/latest/gfnff.html).

**Comment by OkKakao** [comment]
> You can optimize the monomers separately and then put them in one xyz file. Alternatively you can try to use the [GFN-FF](https://xtb-docs.readthedocs.io/en/latest/gfnff.html).

I tried the methods that you suggested, but it didn't work.

So I picked some structures in the trajectory file, and performed some simulations.

Thanks for helping me!
