### ISSUE TITLE
Need improvement in the speed of MD simulation

### ISSUE THREAD

**Issue by OkKakao** [grimme-lab/xtb#886]
Hi.

I'm trying to simulate system with ~650 atoms, however, it takes 2 days for 50 ps simulation.

I want to improve the speed of calculation.

The questions are:

1. Does GPU version improves the speed of calculation?
2. Does the command below produces exhaustive list of the parameters of the system?
    ``` xtb --gfnff methionine.xyz --wrtopo nb,bpair,alist,blist,tlist,vtors,vbond,vangl```

If the latter is true, I will convert the parameters and simulate it with other program that provides GPU acceleration.

**Comment by haneug** [comment]
Hi,

to my knowledge no GPU support is available for the GFN-FF. Also, you can not use the GFN-FF in any other program that has not explicitly implemented it, since it includes some special components for an FF such as a Hückel guess.

Best
Hagen
