### ISSUE TITLE
Dock output structures format

### ISSUE THREAD

**Issue by icamps** [grimme-lab/xtb#893]
How can I force the `dock` module in such a way that the output structures format be the same as the input structure format as in the other methods/modules?

My input structures are `PDB` files, but the output from dock are in `XYZ`.

**Comment by MtoLStoN** [comment]
Hi @icamps,

the docking module is written as a subprogram and uses it's own output procedure. As far as I can see, the output format is hard-coded and will therefore be enforced (i.e. there is no possibility to request another output format). I will use this Issue to open up a related feature request. Maybe @cplett can have a look at that, if he finds the time. 

All the best
Marcel

**Comment by icamps** [comment]
Thanks.

**Comment by icamps** [comment]
Thanks.
