### ISSUE TITLE
Oniom GFN2:GFN-FF screws up structure

### ISSUE THREAD

**Issue by cneiss** [grimme-lab/xtb#897]
**Describe the bug**
xTB optimization using ONIOM with GFN2 as high-level and GFN-FF as low-level method yields unreasonable structure for certain atomic groups (here: silyl groups)

**To Reproduce**
Please find in the attached 
[files.zip](https://github.com/grimme-lab/xtb/files/13279434/files.zip)
an example structure of a molecule with some toluene molecules around (start_solvate.xyz).
I am running xtb by issueing

xtb start_solvate.xyz --oniom gfn2:gfnff 1-40 --opt

I have tried the xtb versions 6.5.1 (579679a) and 6.6.1 (98043ed). 

After optimization, the silyl groups are clearly unphysically distorted, see xtbopt.xyz and/or inner_region.xyz (see attached files.zip above).

**Expected behaviour**
Reasonable geometry after optimization.

**Comment by MtoLStoN** [comment]
This seems to be more related to GFN2-xTB rather than the ONIOM method, as an optimization with pure GFN2-xTB yields a similar structure. For the moment, I would recommend using (angle) constraints, that keep the structure more reasonable while optimizing.

**Comment by cneiss** [comment]
Dear Marcel,
I found the error: while processing the initial structure, openbabel transformed Si atoms into S atoms... Therefore, the input structure is corrupt, it's not a xtb related bug.
Sorry for the inconvenience.

**Comment by MtoLStoN** [comment]
Dear Christian,
glad that worked out for you (and also that it's not a bug).
Cheers
Marcel
