### ISSUE TITLE
Sp-GFN2-xTB

### ISSUE THREAD

**Issue by Siyavash-Moradi** [grimme-lab/xtb#899]
Hi,

I have a problem with running a calculation with sp-gfn2xtb when I wanna run a spin polarized calculation for a single carbon it gets stuck and the job gets killed, here is the command that I use: 

xtb c.xyz --spinpol --tblite --uhf 2

and here is the coordinate:

1

C       0.000000    0.000000    1.000000

**Comment by Albkat** [comment]
Hello, 
I cannot reproduce this behavior on the 6.6.1.
Could you provide the calculation printout?

**Comment by Siyavash-Moradi** [comment]
Hi,
thank you so much for your answer. 
there is no printout. When I run the command, it does nothing, it waits for a couple of minutes then it gets killed.
Would you please send me your printout for this coordinate that I sent?

here is the picture

![output](https://github.com/grimme-lab/xtb/assets/140794254/ee610a96-970d-4585-bf8f-364ac364a0d0)

**Comment by Albkat** [comment]
That is my xtb output:
[xtb.txt](https://github.com/grimme-lab/xtb/files/13412982/xtb.txt)

**Comment by Siyavash-Moradi** [comment]
@Albkat, Thank you so much for your response,
But -1.79 is the energy for Carbon when we run a closed shell, with an open shell and with two unpaired electrons it should give -1.83 (if we run it with the old version the closed-shell one we also get -1.79).

**Comment by Albkat** [comment]
Sorry, I forgot to switch the tblite on. 
Please see the file attached. 
[xtb.txt](https://github.com/grimme-lab/xtb/files/13414882/xtb.txt)

**Comment by Siyavash-Moradi** [comment]
@Albkat, How did you switch the tblite on?

**Comment by Albkat** [comment]
Which xtb version you are using?
The old ones do not support polarization, as it was introduced in v6.6.1 ( #736 )

**Comment by Siyavash-Moradi** [comment]
Dear @Albkat, 

I am using xtb-6.6.1-linux-x86_64.tar.xz which is in this link: https://github.com/grimme-lab/xtb/releases/tag/v6.6.1

**Comment by Albkat** [comment]
That is strange. I've just tested it, and it works fine.
Can you check, if you are really using this binary? 
It happens often, that one uses some old xtb version sourced in bash environment.

**Comment by Albkat** [comment]
You are welcome.
