### ISSUE TITLE
PDB structures without H atoms

### ISSUE THREAD

**Issue by icamps** [grimme-lab/xtb#909]
**Is your feature request related to a problem? Please describe.**
When using PDB files without H, we got an error message, and the calculation stopped:

```
########################################################################
[ERROR] Program stopped due to fatal error
-2- reading geometry input 'CO2.pdb' failed
-1- io_reader_readMolecule: PDB structure without hydrogen atoms found, aborting due to incomplete input geometry
########################################################################
```

**Describe the solution you'd like**
PDB without H atoms be allowed to continue all the calculation types supported by xTB.

**Describe alternatives you've considered**
Using other file formats, but we lose the idea of having "residues" in further analysis.

**If possible state how you can assist in providing data or code to to implement the feature**
Any PDB without H atoms will give this error. I think that stopping checking for H atoms in PDB will "fix" the error.

**Additional context**

**Comment by MtoLStoN** [comment]
Thank you for reporting this Issue. I have opened a PR (#910) to raise a warning instead of an error, to allow the usage of pdb files without hydrogen atoms. This should fix your Issue.

All the best
Marcel
