### ISSUE TITLE
Allow .tmol or .coord in angstrom

### ISSUE THREAD

**Issue by matterhorn103** [grimme-lab/xtb#915]
Given that xtb functions fine when an `.xyz` file with coordinates in angstrom is passed to it, and the program actually (so far as I can tell) runs successfully when a `.coord` or `.tmol` file with coordinates in angstrom is passed, would it be possible to officially support the use of angstrom over bohr when `$coord angs` is present?

In particular, it would be nice if whenever the input is in angstrom, any time the geometry is printed or saved it is also in angstrom. At the moment, all output in `.coord` format is in bohr.

**Comment by awvwgk** [comment]
Support for $coord angs is provided via mctc-lib. In principle mctc-lib can roundtrip most information about the input, however in xtb we do not preserve all metadata from the read for writing again.

**Comment by MtoLStoN** [comment]
I just took a dive in the code and it seems, we are already correctly roundtrip this information, but ``mctc-lib`` is not able to process it. I opened up a [PR](https://github.com/grimme-lab/mctc-lib/pull/62) in ``mctc-lib``. 

I already tested this with our current xTB bleed version and this should word.

**Comment by MtoLStoN** [comment]
The underlying library was fixed and therefore, this should be supported now in our latest [bleed](https://github.com/grimme-lab/xtb/releases/tag/bleed) version. It will be integrated in our next planned release.

**Comment by matterhorn103** [comment]
Many thanks!
