### ISSUE TITLE
Writing mdrestart file every desired step

### ISSUE THREAD

**Issue by moabe84** [grimme-lab/xtb#922]
Dear xtb developers,
Can the xtb code be instructed to generate the "mdrestart" file every specified steps during MD simulations? It's very helpful for the situation that the job gets cancelled/killed. This is related to the [issue #444](https://github.com/grimme-lab/xtb/issues/444).   

Thanks,
Mostafa

**Comment by MtoLStoN** [comment]
Hi @moabe84,
we already added this option in #760. The option
```
forcewrrestart=true
```
in a suitable [detailed input](https://xtb-docs.readthedocs.io/en/latest/xcontrol.html#detailed-input) will force ``xTB`` to write a restart file at every dump step. A suitable input could look like this:
```
$md
   temp=298.15 # in K
   time= 50.0  # in ps
   dump= 4.0  # in fs
   step=  4.0  # in fs
   velo=false
   nvt =true
   hmass=4
   shake=2
   sccacc=2.0
   forcewrrestart=true
$end
```

All the best
Marcel
