### ISSUE TITLE
XTB gives segmentation fault (core dumped) for protein-ligand complex

### ISSUE THREAD

**Issue by sbembenek18** [grimme-lab/xtb#925]
I have a protein ligand complex that I am trying to get a single point energy on. but I get a 
segmentation fault. I've tried with a couple different proteins, but it's the same issue. 

Not sure why.

**Comment by MtoLStoN** [comment]
Hi there,

This sounds like it could be related to the Stacksize (#877). Did you already try that?

**Comment by sbembenek18** [comment]
Yes, this fixed it. Thanks.
