### ISSUE TITLE
Constraint Options

### ISSUE THREAD

**Issue by sbembenek18** [grimme-lab/xtb#926]
rather than using the keywords 'atoms' or 'elements' for $constrain, is it possible to simply have 'all' as an option  -- as in all atoms in the file.

**Comment by MtoLStoN** [comment]
We provide already the possibility to constrain all bonds, torsions and angles by setting a [detailed input](https://github.com/grimme-lab/xtb/blob/main/man/xcontrol.7.adoc) as:
```
$constrain
   all bonds=true
   all angles=true
   all torsions=true
```
Is this sufficient for your use case or do you need another option?

**Comment by sbembenek18** [comment]
Thanks
