### ISSUE TITLE
Optimization of structures with exact fixing

### ISSUE THREAD

**Issue by OkKakao** [grimme-lab/xtb#927]
I'm trying to find optimized structure of quite large system.
I takes about 2 hours for tight optimization.
Therefore, what I want is partial optimization of the system, not entire system.

I tried detailed input.
```
$fix
  elements: C, O, H
$end
```
But exact fixing did not work.
Can I exactly fix the atoms during the optimization process?

**Comment by MtoLStoN** [comment]
At first glance, this should work. Can you share the system in question and your input (CLI and xcontrol)?

**Comment by Albkat** [comment]
And please use `--verbose` print-level, when working with constraints. 
This will show you exactly the type of applied constrains and the list of constrained atoms.
