### ISSUE TITLE
Fix optimization does not really fix 

### ISSUE THREAD

**Issue by Viba97** [grimme-lab/xtb#932]
**Describe the bug**
When I try to run the fix optimization some atoms at the end of the fixed list still move

**To Reproduce**
xtb_version --> 6.5.1

intial geometry file -->  start_geom_xyz.txt
[start_geom_xyz.txt](https://github.com/grimme-lab/xtb/files/13718148/start_geom_xyz.txt)

input file -->  xtb_inp.txt 
[xtb_inp.txt](https://github.com/grimme-lab/xtb/files/13718112/xtb_inp.txt)

output file (truncated) --> output.txt
[output.txt](https://github.com/grimme-lab/xtb/files/13718176/output.txt)

trajectory file --> movie_xyz.txt
[movie_xyz.txt](https://github.com/grimme-lab/xtb/files/13718186/movie_xyz.txt)

run xtb file --> run_xtb.sh
[run_xtb_sh.txt](https://github.com/grimme-lab/xtb/files/13718129/run_xtb_sh.txt)

command line --> sbatch run_xtb.sh --input xtb.inp start_geom.xyz --opt extreme --verbose

**Expected behaviour**
Reading from the manual I've understood that the $constrain optimization should still give some degrees of freedom to the "fix" atoms, while the $fix optimization should keep the "fix" fixed by setting the gradient to 0.

However when I try to optimize with the $fix option there are still some atoms moving. In particular, looking at the trajectory file (movie_xyz.txt) atoms (counting from zero) 585,586,587,588,589,590,591,592,593,594,595,596,597,598,599 and probably other are still moving. Nevertheless, the atoms inside the above list should be exactly fixed, see input file (xtb_inp.txt )
Unfortunately, I do need to have the fix part to be real  fixed in order to run a NEB calculation on top of that geometry. 

 Is this related to the fix option or a problem in my input?

**Additional context**
When I try to run the exact same calculation but using the $constrain keyword the optimization converges after 27 cycles, while the above test overpass the 50 cycles without any convergence.

**Comment by Albkat** [comment]
Hello,

I can reproduce this behavior.
It seems to be related to the L-BFGS update that is automatically turned on for the large systems.
Until this problem is fixed, I can recommend using the normal ANCopt, which I have tested using your input. Please add these instructions to your xtb.inp file:
```
$opt 
engine=rf
$end
```
