### ISSUE TITLE
Importing `interface.py` requires ASE anyway

### ISSUE THREAD

**Issue by pierre-24** [grimme-lab/xtb#95]
**Describe the bug**
I'm trying to achieve [an interface between `gaussian` and `xtb`](https://github.com/pierre-24/g2xtb_interface) in order to perform `xtb:QM` onium calculations. Until recently (since it wasn't possible for me to compile `xtb` in the past), I was using [a custom interface](https://github.com/pierre-24/g2xtb_interface/blob/master/g2xtb_interface/XTB.py) inspired by the previous python file (which does not work with the current version, for this reason), but I would prefer to rely on your implementation of the [`interface.py` file](https://github.com/grimme-lab/xtb/blob/master/python/xtb/interface.py).

I don't really want to  have `ASE` as a dependence for that, since I only need to perform a bridge between the two codes. Not that ASE is a heavy dependence, but it would be weird to require it.

**To Reproduce**
Steps to reproduce the behaviour:

1. I add the `python` directory to `PYTHONPATH`
2. In the python code, I use `from xtb import interface`

The result is, obviously,

```
Traceback (most recent call last):
  File "/home/pbeaujea/g2xtb_interface/interface.py", line 11, in <module>
    from xtb import interface as xtb_interface
  File "/home/pbeaujea/.install_stda/xtb/python/xtb/__init__.py", line 20, in <module>
    from xtb.calculators import GFN1, GFN2, GFN0
  File "/home/pbeaujea/.install_stda/xtb/python/xtb/calculators.py", line 24, in <module>
    from ase.calculators.calculator import Calculator, all_changes
ImportError: No module named 'ase'
```

... Since `__init__.py` is always imported.

**Expected behaviour**

I get why you included `calculators` in  `__init__.py` , but in my case, it is problematic: I could always copy/paste `interface.py` from your repo to mine, but that would not be very elegant (and its probably not the best way due to licencing stuffs).

**Comment by awvwgk** [comment]
Probably the best way would be to separate the Python API from the ASE calculator for this, maybe even in separate repositories. We should discuss this.

**Comment by pierre-24** [comment]
It depends on what you are trying to achieve with it. For me (and in my case), having a `interface.py` file in a `xtb` package is ok, since it is easy to import it this way. The ASE calculator would be an example to show that you can then interface `xtb` with anything, and would be a little bit "higher level abstraction".

But that's my point of view :)

**Comment by awvwgk** [comment]
I thought including dependencies would ensure that they are present downstream:

https://github.com/grimme-lab/xtb/blob/ad49de1a24edbb8645acb0811509a5c0a2dd2485/python/setup.py#L36

Right now ASE ensures that structures are represented in a meaningful way, the `Atoms` class is by far the most easy and complete way to address this problem. An alternative could be something like QCSchema, which has other drawbacks, like it is missing PBCs (see https://github.com/MolSSI/QCSchema/issues/66). A couple of ndarrays is the least preferable way, at least in my opinion.

BTW, ASE offers a QM:MM functionality and a Gaussian calculator.

**Comment by awvwgk** [comment]
So at this point it is unlikely that we will drop the ASE dependency, but we might guard the import in the `__init__.py` in case it is not present. Would that help?

**Comment by pierre-24** [comment]
That might probably work, indeed :)

**Comment by awvwgk** [comment]
@pierre-24 wouldn't it be easier to implement the Gaussian input and output format directly in `xtb`? Looking at your project, you have almost more code dealing with the `xtb` interface than with the Gaussian interface.

Adding the reader for the input format would require the file extension to be detected correctly in [`file_figure_out_ftype`](https://github.com/grimme-lab/xtb/blob/master/xtb/tbmod_file_utils.f90) and a specific reader for such format in [`xtb/molecule_reader.f90`](https://github.com/grimme-lab/xtb/blob/master/xtb/tbmod_file_utils.f90). Writing could occur like for the Turbomole `gradient` file at
https://github.com/grimme-lab/xtb/blob/ad49de1a24edbb8645acb0811509a5c0a2dd2485/xtb/program_main.f90#L786-L787
Anything else?

For maybe obvious reasons I can't implement nor test such interface, but it would still be an unique contribution opportunity, to put it that way ;).

**Comment by pierre-24** [comment]
Mmmh, I didn't know (or more probably, I forgot) that it was possible to
interface the xtb program directly. That may be indeed an interesting idea
:)

**Comment by dgasmith** [comment]
+1 here. It would be great to have python basic ctypes interface without the ASE requirement. Happy to take on the extra formatting onus. If you could ensure the `interface.py` is at least somewhat stable we could copy that as well.

**Comment by awvwgk** [comment]
Since I am currently reworking the C-API in #102, I could also look over the Python-API again. There is certainly a way to add optional dependencies for Python modules and than separate the ASE calculator implementation from the basic Python-API.

**Comment by dgasmith** [comment]
A way to accomplish this would be something like the following:

In the `setup.py`:

```python
    extras_require={
        "ase": ["ase"]
    }
```

The `xtb/__init__.py would not have `import ase` so then access would be via:
```python
import xtb.ase
xtb.ase.calculator()
```

or

```python
from xtb.ase import ase_calculator
ase_calculator()
```

The `ase.py` could have something like
```python
try:
    import ase
except ModuleNotFoundError:
    raise MolduleNotFoundError("This submodule requires ASE, please install via 'pip install ase'")
```

**Comment by awvwgk** [comment]
Thanks, I'll give this a try after finishing #102.

**Comment by awvwgk** [comment]
Finally decided that the Python API is not going to a part off this repository anymore. We will keep the `ctypes` interface for testing purposes, but it shouldn't be used for production.

**Comment by pierre-24** [comment]
Just to be clear, you'll rely on a fully C API, then ?

**Comment by awvwgk** [comment]
Yes, this repository will only expose a C API. The `ctypes` API has a lot of shortcomings, in my opinion the easiest way to avoid those is to not have a `ctypes` API for Python.

There will still be a Python API to `xtb`, but this is another project for another repository, probably I will use CFFI or SWIG for this purpose.

**Comment by pierre-24** [comment]
As long as there is an API, it is fine by me :)

**Comment by awvwgk** [comment]
The basic Python API is now successfully migrated to https://github.com/grimme-lab/xtb-python.
