### ISSUE TITLE
Keyword for Octanol (wet)

### ISSUE THREAD

**Issue by sbembenek18** [grimme-lab/xtb#959]
What is the keyword for 'Octanol (wet)' when using the implicit solvent

**Comment by Albkat** [comment]
hello,
it is `--alpb woctanol`

**Comment by sbembenek18** [comment]
thanks!

And it looks like the other ones are pretty much as written on readthedocs (e.g., Acetone, Acetonitrile ... CH2Cl2, ... Water) -- yes? 

--> https://xtb-docs.readthedocs.io/en/latest/gbsa.html

**Comment by Albkat** [comment]
Yes, they are the same
