### ISSUE TITLE
Clarify xtb license

### ISSUE THREAD

**Issue by susilehtola** [grimme-lab/xtb#96]
From the looks of it, xtb appears to be licensed under LGPLv3+.
However, this is not reflected in the output of the program.

The problem is the dumped header
```
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
   
   FOR NON-COMMERCIAL, ACADEMIA USE ONLY.
```
which prevents the program from being packaged into *nix distributions; the output arises from
https://github.com/grimme-lab/xtb/blob/ad49de1a24edbb8645acb0811509a5c0a2dd2485/xtb/header.f90#L51

Would you mind removing the restrictions to non-commercial academic use in the sources and any possible example/reference log files?

**Comment by awvwgk** [comment]
These are still legacies from the days back when `xtb` was proprietary. This project is now committed to the open source idea.
