### ISSUE TITLE
ifort has been deprecated

### ISSUE THREAD

**Issue by jevandezande** [grimme-lab/xtb#961]
[Intel announced](https://community.intel.com/t5/Blogs/Tech-Innovation/Tools/Deprecation-of-The-Intel-Fortran-Compiler-Classic-ifort/post/1541699) the deprecation of ifort on 2023-11-17, and it will be discontinued in "late 2024". Intel has recommended a move to the Intel Fortran Compiler (ifx).

Does **xtb** have a recommended compiler to switch to?

**Comment by Albkat** [comment]
Hi, this will be covered by this issue #908.
