### ISSUE TITLE
Spin Polarization - Spin Constants for Hydrogen using GFN1

### ISSUE THREAD

**Issue by eliseoruiz** [grimme-lab/xtb#968]
Dear Colleagues,

   I have a problem using the SpinPolarization option with the external tmol file generated with tblite and tbdf+ because in your paper devoted to the xtb spin polarization, there is only one spin constant for hydrogen with the 1s orbital. This is fine for GFN2 because there is only this orbital, however with GFN1, there is also a 2s orbital. In such case, which is the Spin Constant that should be employed with such orbital.

           best wishes, thanks in advance

                               Eliseo

**Comment by haneug** [comment]
Just set the spin constants to zero for the 2s.

Best Hagen
