### ISSUE TITLE
Build xTB 6.7.0 failure when OpenMP disabled

### ISSUE THREAD

**Issue by t0saki** [grimme-lab/xtb#983]
**Describe the bug**

When building xTB with OpenMP disabled using the meson option `-Dopenmp=false`, the build fails with the error message `ninja: build stopped: subcommand failed`.

**To Reproduce**

The issue can be reproduced on both Debian 11 with gcc 10.2.1/gfortran 10.2.1 and Ubuntu 23.10 with gcc 13.2.0/gfortran 13.2.0.

```bash
export FC=gfortran CC=gcc
meson setup build -Dopenmp=false
ninja -C build test
```

output:
```bash
ninja: build stopped: subcommand failed
```

**Expected behavior**

The build should complete successfully when OpenMP is disabled using the meson option `-Dopenmp=false`.

**Additional context**

The following error message is observed:
```fortran
  5 ../src/extern/orca.f90:284:20:
  6
  7   284 |       num_threads = omp_get_num_threads()
  8       |                    1
  9 Error: Function 'omp_get_num_threads' at (1) has no IMPLICIT type
```

**Comment by Albkat** [comment]
Hello, I can reproduce this, thank you for sharing.
